/* One local display scene; shared canvas renderer also owns PNG export. */
(function(root){
'use strict';
const P=BondProfile,H=BondHaven,cache=new Map();
let draft=null,returnFocus=null,serial=0;
const dialog=document.createElement('dialog');dialog.id='haven-dialog';dialog.setAttribute('aria-labelledby','haven-title');document.body.append(dialog);
function markup(){const s=P.snapshot(),power=BondFarm.power(s),f=s.farm,forecast=BondFarm.forecast(s);return '<section class="haven-display" aria-label="Inner Sea display"><div class="haven-overview"><div class="haven-heading"><div><p class="eyebrow">YOUR HOMESTEAD · SEA LV '+(1+Math.floor(power/100))+'</p><h3>A place to come home.</h3></div><span class="haven-power"><small>INNER SEA POWER</small><strong>'+power+'</strong></span></div><div class="haven-landscape"><canvas id="haven-scene" width="960" height="540" role="img" aria-label="Your Inner Sea"></canvas><div class="haven-habitat-labels">'+Object.entries(BondFarm.habitats).map(([id,h])=>'<button data-sea-habitat="'+id+'" style="--x:'+BondFarmView.places[id].x/9.6+'%;--y:'+(BondFarmView.places[id].y+24)/5.4+'%" aria-label="Manage '+h.name+'">'+h.name+'<small>Lv '+f.levels[id]+'</small></button>').join('')+'</div></div><div class="haven-caption"><span class="haven-condition '+(f.damaged?'damaged':'')+'">'+(!f.owned?'A home waiting for you':f.damaged?'Repairs needed':Date.now()>=f.cleanUntil?'Time to tidy up':'Clean & training')+'</span><span>☽ '+forecast.name+'</span></div><div class="haven-scene-actions"><button class="button secondary" data-haven-edit>Arrange scene</button><button class="button secondary" data-haven-export>Save picture</button></div><p class="haven-status" role="status"></p></div>'+BondFarmView.markup()+'</section>';}
function loadArt(type){if(['hunter','swordsman'].includes(type))return CharacterRig.portraitSource(type);if(type==='apprentice'){const c=P.snapshot().character,key='painted-apprentice:'+JSON.stringify([c?.look,c?.weapon]);if(!cache.has(key))cache.set(key,BondApprenticePreview.source(c?.look,c?.weapon));return cache.get(key);}const box=document.createElement('div');box.innerHTML=CharacterRig.art(type);const img=box.querySelector('img'),svg=box.querySelector('svg'),url=img?.getAttribute('src')||(svg?'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(svg)):null);if(cache.has(url)){const cached=cache.get(url);cache.delete(url);cache.set(url,cached);return cached;}const task=new Promise((resolve,reject)=>{if(!url){reject(Error('Portrait unavailable'));return;}const image=new Image(),timer=setTimeout(()=>{image.src='';reject(Error('Portrait timed out'));},8000);image.onload=()=>{clearTimeout(timer);resolve(image);};image.onerror=()=>{clearTimeout(timer);reject(Error('Portrait could not load'));};image.src=url;});cache.set(url,task);while(cache.size>8)cache.delete(cache.keys().next().value);task.catch(()=>{if(cache.get(url)===task)cache.delete(url);});return task;}
function ellipse(ctx,x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function decor(ctx,id,x,y){ctx.save();ctx.translate(x,y);if(id==='cairn'){for(let i=0;i<4;i++)ellipse(ctx,0,-i*13,29-i*5,10,['#697d7d','#a5b4a9','#d3d6ba','#ecdfbc'][i]);}else if(id==='lantern'){ctx.strokeStyle='#8a7460';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-8,0);ctx.lineTo(-8,-78);ctx.quadraticCurveTo(18,-100,33,-72);ctx.stroke();ctx.fillStyle='#ecd794';ctx.fillRect(18,-68,29,34);ctx.strokeStyle='#8a7460';ctx.lineWidth=4;ctx.strokeRect(18,-68,29,34);ellipse(ctx,32,-51,8,12,'#fff4c3');}else if(id==='bloom'){ctx.strokeStyle='#557c62';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-46);ctx.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3;ellipse(ctx,Math.cos(a)*15,-52+Math.sin(a)*15,12,12,'#eabdad');}ellipse(ctx,0,-52,10,10,'#ffeab4');ellipse(ctx,-15,-19,17,6,'#64906e');}ctx.restore();}
async function draw(canvas,layout,s){const token=++serial;canvas.dataset.render=String(token);canvas.dataset.ready='false';const ctx=canvas.getContext('2d'),palette=H.styles[layout.style];ctx.clearRect(0,0,960,540);
 const entries=Object.values(BondFarm.residents(s)),trainer=root.BondApp?.getBuild()[0][0]?.type||'apprentice';
 const actors=[{type:trainer,x:480,y:276,size:76},...entries.map(m=>{const h=BondFarmView.places[BondFarm.habitat(m.type)];return {type:m.type,x:h.x,y:h.y,size:82};})];
 try{const [background,images]=await Promise.all([BondFarmView.background(),Promise.all(actors.map(a=>loadArt(a.type)))]);if(canvas.dataset.render!==String(token))return false;BondFarmView.paint(ctx,s,layout,background);actors.forEach((a,i)=>{ellipse(ctx,a.x,a.y-2,24,6,'#29464544');const image=images[i],ratio=image.width/image.height,w=ratio>=1?a.size:a.size*ratio,h=ratio>=1?a.size/ratio:a.size;ctx.drawImage(image,a.x-w/2,a.y-h,w,h);});layout.slots.forEach((id,i)=>{if(id)decor(ctx,id,[362,585,650][i],[323,287,405][i]);});canvas.dataset.ready='true';canvas.setAttribute('aria-label',H.styles[layout.style].name+' Inner Sea with your trainer'+entries.filter(Boolean).map(m=>', '+P.label(m)).join('')+' and '+layout.slots.filter(Boolean).map(id=>H.decorations[id].name).join(', '));return true;}catch(_){if(canvas.dataset.render===String(token)){ctx.fillStyle='#fff4df';ctx.textAlign='center';ctx.font='18px sans-serif';ctx.fillText('Portrait unavailable — retry when connected.',480,260);canvas.dataset.ready='error';}return false;}}
function refresh(){const canvas=document.querySelector('#haven-scene');if(!canvas)return;const s=P.snapshot();draw(canvas,H.clean(s.haven,s),s).then(ok=>{if(canvas.isConnected)canvas.closest('.haven-display').querySelector('.haven-status').textContent=ok?'':'A portrait could not load. Use Save picture to retry.';});}
function edit(){returnFocus=document.activeElement;const s=P.snapshot();draft=H.clean(s.haven,s);dialog.innerHTML='<div class="haven-heading"><h2 id="haven-title">Arrange your Inner Sea</h2><button class="button secondary" data-haven-cancel>Cancel</button></div><canvas width="960" height="540" id="haven-preview" role="img" aria-label="Scene preview"></canvas><label class="haven-style">Sky<select id="haven-style">'+Object.entries(H.styles).map(([id,v])=>'<option value="'+id+'">'+v.name+'</option>').join('')+'</select></label><p class="haven-status">Each habitat displays its highest-level resident.</p><div class="haven-sockets">'+[0,1,2].map(i=>'<label>Decoration '+(i+1)+'<select data-haven-slot="'+i+'"><option value="">Empty</option>'+Object.entries(H.decorations).map(([id,d])=>'<option value="'+id+'" '+(!H.available(s).includes(id)?'disabled':'')+'>'+d.name+(H.available(s).includes(id)?'':' — '+d.source)+'</option>').join('')+'</select></label>').join('')+'</div><p class="haven-status" role="status"></p><button class="button primary" data-haven-save>Save scene</button>';dialog.querySelector('#haven-style').value=draft.style;dialog.querySelectorAll('[data-haven-slot]').forEach(n=>n.value=draft.slots[+n.dataset.havenSlot]||'');dialog.showModal();renderDraft();}
function renderDraft(){if(!draft)return;draw(dialog.querySelector('canvas'),draft,P.snapshot());dialog.querySelectorAll('[data-haven-companion]').forEach(b=>{const m=P.getCompanion(draft.companions[+b.dataset.havenCompanion]);b.textContent=m?P.label(m):'Choose companion '+(+b.dataset.havenCompanion+1);});}
async function exportPicture(){const canvas=document.querySelector('#haven-scene'),status=canvas?.closest('.haven-display').querySelector('.haven-status');if(!canvas)return false;const s=P.snapshot();if(!await draw(canvas,H.clean(s.haven,s),s)){status.textContent='Could not load the scene. Retry when connected.';return false;}try{const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('No image');BondSettings.download(blob,'bond-and-bolt-inner-sea.png');status.textContent='Picture saved.';return true;}catch(_){status.textContent='Could not save the picture. Try again.';return false;}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.seaHabitat){const card=document.querySelector('[data-habitat="'+b.dataset.seaHabitat+'"]');card?.scrollIntoView({block:'nearest',behavior:'instant'});card?.focus({preventScroll:true});}if(b.hasAttribute('data-haven-edit'))edit();if(b.hasAttribute('data-haven-export'))exportPicture();if(b.hasAttribute('data-haven-cancel'))dialog.close();if(b.hasAttribute('data-haven-save')){if(P.setHaven(draft)){dialog.close();refresh();}else dialog.querySelector('.haven-status').textContent=P.error()||'This selection is no longer available.';}if(b.dataset.havenCompanion!==undefined&&draft){const slot=+b.dataset.havenCompanion;BondPicker.open({title:'Display companion '+(slot+1),allowEmpty:true,selected:draft.companions[slot],returnSelector:'[data-haven-companion="'+slot+'"]',onChoose:id=>{if(id&&draft.companions.includes(id)){const other=1-slot;[draft.companions[slot],draft.companions[other]]=[draft.companions[other],draft.companions[slot]];}else draft.companions[slot]=id||null;renderDraft();return true;}});}});
dialog.addEventListener('change',e=>{if(!draft)return;if(e.target.id==='haven-style')draft.style=e.target.value;if(e.target.dataset.havenSlot!==undefined)draft.slots[+e.target.dataset.havenSlot]=e.target.value||null;renderDraft();});
dialog.addEventListener('close',()=>{draft=null;if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else document.querySelector('[data-haven-edit]')?.focus({preventScroll:true});});
root.BondInnerSea={markup,refresh,edit,draw,exportPicture};
})(globalThis);
