/* One local display scene; shared canvas renderer also owns PNG export. */
(function(root){
'use strict';
const P=BondProfile,H=BondHaven,cache=new Map();
let draft=null,returnFocus=null,serial=0;
const dialog=document.createElement('dialog');dialog.id='haven-dialog';dialog.setAttribute('aria-labelledby','haven-title');document.body.append(dialog);
function markup(){return '<section class="haven-display" aria-label="Inner Sea display"><div class="haven-heading"><div><p class="eyebrow">YOUR INNER SEA</p><h3>A place to come home.</h3></div><div><button class="button secondary" data-haven-edit>Arrange scene</button><button class="button secondary" data-haven-export>Save picture</button></div></div><canvas id="haven-scene" width="960" height="540" role="img" aria-label="Your Inner Sea"></canvas><p class="haven-status" role="status"></p></section>';}
function loadArt(type){if(type==='apprentice'){const c=P.snapshot().character,key='painted-apprentice:'+JSON.stringify([c?.look,c?.weapon]);if(!cache.has(key))cache.set(key,BondApprenticePreview.source(c?.look,c?.weapon));return cache.get(key);}const box=document.createElement('div');box.innerHTML=CharacterRig.art(type);const img=box.querySelector('img'),svg=box.querySelector('svg'),url=img?.getAttribute('src')||(svg?'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(svg)):null);if(cache.has(url)){const cached=cache.get(url);cache.delete(url);cache.set(url,cached);return cached;}const task=new Promise((resolve,reject)=>{if(!url){reject(Error('Portrait unavailable'));return;}const image=new Image(),timer=setTimeout(()=>{image.src='';reject(Error('Portrait timed out'));},8000);image.onload=()=>{clearTimeout(timer);resolve(image);};image.onerror=()=>{clearTimeout(timer);reject(Error('Portrait could not load'));};image.src=url;});cache.set(url,task);while(cache.size>8)cache.delete(cache.keys().next().value);task.catch(()=>{if(cache.get(url)===task)cache.delete(url);});return task;}
function ellipse(ctx,x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function decor(ctx,id,x,y){ctx.save();ctx.translate(x,y);if(id==='cairn'){for(let i=0;i<4;i++)ellipse(ctx,0,-i*13,29-i*5,10,['#697d7d','#a5b4a9','#d3d6ba','#ecdfbc'][i]);}else if(id==='lantern'){ctx.strokeStyle='#8a7460';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-8,0);ctx.lineTo(-8,-78);ctx.quadraticCurveTo(18,-100,33,-72);ctx.stroke();ctx.fillStyle='#ecd794';ctx.fillRect(18,-68,29,34);ctx.strokeStyle='#8a7460';ctx.lineWidth=4;ctx.strokeRect(18,-68,29,34);ellipse(ctx,32,-51,8,12,'#fff4c3');}else if(id==='bloom'){ctx.strokeStyle='#557c62';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-46);ctx.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3;ellipse(ctx,Math.cos(a)*15,-52+Math.sin(a)*15,12,12,'#eabdad');}ellipse(ctx,0,-52,10,10,'#ffeab4');ellipse(ctx,-15,-19,17,6,'#64906e');}ctx.restore();}
async function draw(canvas,layout,s){const token=++serial;canvas.dataset.render=String(token);canvas.dataset.ready='false';const ctx=canvas.getContext('2d'),palette=H.styles[layout.style];ctx.clearRect(0,0,960,540);const gradient=ctx.createLinearGradient(0,0,0,540);gradient.addColorStop(0,palette.sky);gradient.addColorStop(.54,palette.water);gradient.addColorStop(1,palette.deep);ctx.fillStyle=gradient;ctx.fillRect(0,0,960,540);ellipse(ctx,738,98,45,45,layout.style==='dusk'?'#eee3bb':'#ffefbd');for(let i=0;i<18;i++){ctx.strokeStyle=i%2?'#e9f6e622':'#d7ede933';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(480,320+i*11,100+i*31,10+i*2,0,0,Math.PI*2);ctx.stroke();}ellipse(ctx,480,405,304,70,'#213f5055');ellipse(ctx,480,377,294,64,'#759383');ellipse(ctx,480,358,288,61,'#d8d5ac');ellipse(ctx,480,349,266,52,'#e8e2bb');ctx.strokeStyle='#fff0cc88';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(480,349,202,32,0,0,Math.PI*2);ctx.stroke();
 const entries=layout.companions.map(id=>s.companions.find(m=>m.id===id)||null),trainer=root.BondApp?.getBuild()[0][0]?.type||'apprentice';
 const actors=[{type:trainer,x:480,y:341,size:180},...entries.map((m,i)=>m?{type:m.type,x:i?646:315,y:368,size:175}:null).filter(Boolean)];
 try{const images=await Promise.all(actors.map(a=>loadArt(a.type)));if(canvas.dataset.render!==String(token))return false;actors.forEach((a,i)=>{ellipse(ctx,a.x,a.y-2,36,8,'#29464533');const image=images[i],ratio=image.width/image.height,w=ratio>=1?a.size:a.size*ratio,h=ratio>=1?a.size/ratio:a.size;ctx.drawImage(image,a.x-w/2,a.y-h,w,h);});layout.slots.forEach((id,i)=>{if(id)decor(ctx,id,[252,480,712][i],[399,407,395][i]);});ctx.fillStyle='#f3f2de';ctx.font='14px Georgia';ctx.textAlign='center';ctx.fillText('BOND & BOLT · INNER SEA',480,502);canvas.dataset.ready='true';canvas.setAttribute('aria-label',H.styles[layout.style].name+' Inner Sea with your trainer'+entries.filter(Boolean).map(m=>', '+P.label(m)).join('')+' and '+layout.slots.filter(Boolean).map(id=>H.decorations[id].name).join(', '));return true;}catch(_){if(canvas.dataset.render===String(token)){ctx.fillStyle='#fff4df';ctx.textAlign='center';ctx.font='18px sans-serif';ctx.fillText('Portrait unavailable — retry when connected.',480,260);canvas.dataset.ready='error';}return false;}}
function refresh(){const canvas=document.querySelector('#haven-scene');if(!canvas)return;const s=P.snapshot();draw(canvas,H.clean(s.haven,s),s).then(ok=>{if(canvas.isConnected)canvas.parentElement.querySelector('.haven-status').textContent=ok?'':'A portrait could not load. Use Save picture to retry.';});}
function edit(){returnFocus=document.activeElement;const s=P.snapshot();draft=H.clean(s.haven,s);dialog.innerHTML='<div class="haven-heading"><h2 id="haven-title">Arrange your Inner Sea</h2><button class="button secondary" data-haven-cancel>Cancel</button></div><canvas width="960" height="540" id="haven-preview" role="img" aria-label="Scene preview"></canvas><label class="haven-style">Sky<select id="haven-style">'+Object.entries(H.styles).map(([id,v])=>'<option value="'+id+'">'+v.name+'</option>').join('')+'</select></label><div class="haven-companions">'+[0,1].map(i=>'<button class="button secondary" data-haven-companion="'+i+'">Choose companion '+(i+1)+'</button>').join('')+'</div><div class="haven-sockets">'+[0,1,2].map(i=>'<label>Decoration '+(i+1)+'<select data-haven-slot="'+i+'"><option value="">Empty</option>'+Object.entries(H.decorations).map(([id,d])=>'<option value="'+id+'" '+(!H.available(s).includes(id)?'disabled':'')+'>'+d.name+(H.available(s).includes(id)?'':' — '+d.source)+'</option>').join('')+'</select></label>').join('')+'</div><p class="haven-status" role="status"></p><button class="button primary" data-haven-save>Save scene</button>';dialog.querySelector('#haven-style').value=draft.style;dialog.querySelectorAll('[data-haven-slot]').forEach(n=>n.value=draft.slots[+n.dataset.havenSlot]||'');dialog.showModal();renderDraft();}
function renderDraft(){if(!draft)return;draw(dialog.querySelector('canvas'),draft,P.snapshot());dialog.querySelectorAll('[data-haven-companion]').forEach(b=>{const m=P.getCompanion(draft.companions[+b.dataset.havenCompanion]);b.textContent=m?P.label(m):'Choose companion '+(+b.dataset.havenCompanion+1);});}
async function exportPicture(){const canvas=document.querySelector('#haven-scene'),status=canvas?.parentElement.querySelector('.haven-status');if(!canvas)return false;const s=P.snapshot();if(!await draw(canvas,H.clean(s.haven,s),s)){status.textContent='Could not load the scene. Retry when connected.';return false;}try{const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('No image');BondSettings.download(blob,'bond-and-bolt-inner-sea.png');status.textContent='Picture saved.';return true;}catch(_){status.textContent='Could not save the picture. Try again.';return false;}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-haven-edit'))edit();if(b.hasAttribute('data-haven-export'))exportPicture();if(b.hasAttribute('data-haven-cancel'))dialog.close();if(b.hasAttribute('data-haven-save')){if(P.setHaven(draft)){dialog.close();refresh();}else dialog.querySelector('.haven-status').textContent=P.error()||'This selection is no longer available.';}if(b.dataset.havenCompanion!==undefined&&draft){const slot=+b.dataset.havenCompanion;BondPicker.open({title:'Display companion '+(slot+1),allowEmpty:true,selected:draft.companions[slot],returnSelector:'[data-haven-companion="'+slot+'"]',onChoose:id=>{if(id&&draft.companions.includes(id)){const other=1-slot;[draft.companions[slot],draft.companions[other]]=[draft.companions[other],draft.companions[slot]];}else draft.companions[slot]=id||null;renderDraft();return true;}});}});
dialog.addEventListener('change',e=>{if(!draft)return;if(e.target.id==='haven-style')draft.style=e.target.value;if(e.target.dataset.havenSlot!==undefined)draft.slots[+e.target.dataset.havenSlot]=e.target.value||null;renderDraft();});
dialog.addEventListener('close',()=>{draft=null;if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else document.querySelector('[data-haven-edit]')?.focus({preventScroll:true});});
root.BondInnerSea={markup,refresh,edit,draw,exportPicture};
})(globalThis);
