/* Shared field medicine and physical village services. No build shortcuts. */
(function(root){
'use strict';
const P=BondProfile,T=BondAdventure,W=BondWorld;
const dialog=document.createElement('dialog');dialog.id='recovery-dialog';dialog.setAttribute('aria-labelledby','recovery-title');document.body.append(dialog);
let mode='field',item='leafdraught',returnFocus=null,notice='';
const percent=n=>Math.round(n/100)+'%';
function members(){const s=P.snapshot();return [{id:'trainer',name:'Trainer',type:root.BondApp?.getBuild()[0][0].type||'druid'},...s.companions.map(m=>({id:m.id,name:P.label(m),type:m.type}))];}
function bars(party){const s=P.snapshot();return '<div class="travel-vitality">'+party.filter(Boolean).map((u,i)=>{const id=i===0?'trainer':u.instanceId,hp=T.health(s,id);return '<div class="travel-health '+(!hp?'fallen':'')+'"><span>'+ (i===0?'Trainer':P.label(P.getCompanion(id)))+'</span><b>'+percent(hp)+'</b><meter min="0" max="10000" value="'+hp+'" aria-label="'+(i===0?'Trainer':BondContent.UNITS[u.type].name)+' health"></meter></div>';}).join('')+'</div>';}
function render(){const s=P.snapshot(),locked=!!s.encounterSave,near=mode==='field'||P.canService(mode);const focus=document.activeElement?.dataset;
 dialog.innerHTML='<p class="eyebrow">'+(mode==='shop'?'SUPPLIES':mode==='sanctuary'?'REST FOR THE ROAD':'YOUR TRAVEL SATCHEL')+'</p><h2 id="recovery-title">'+(mode==='shop'?'Supply Store':mode==='sanctuary'?'Forest camp':'Recovery items')+'</h2><p>'+(mode==='shop'?'Supplies for the road.':mode==='sanctuary'?'Restore your party.':'Choose who to heal.')+'</p><p class="recovery-notice" role="status">'+(notice||(locked?'Finish the current battle first.':!near?'Walk up to the camp to rest.':mode==='sanctuary'?'Free rest':s.coins+' trail coins'))+'</p>';
 if(mode==='shop')dialog.innerHTML+='<div class="supply-grid">'+Object.entries(T.prices).map(([id,price])=>'<article class="supply-card"><span class="supply-icon" aria-hidden="true">'+W.ITEMS[id].icon+'</span><h3>'+W.ITEMS[id].name+'</h3><p>'+W.ITEMS[id].description+'</p><small>'+(s.inventory[id]||0)+' in bag</small><button class="button primary" data-store-buy="'+id+'" '+(locked||!near||s.coins<price?'disabled':'')+'>Buy · '+price+' coins</button></article>').join('')+'</div>';
 else if(mode==='sanctuary')dialog.innerHTML+=bars(root.BondApp?.getBuild()[0]||[])+'<button class="button primary" data-sanctuary-rest '+(locked||!near?'disabled':'')+'>Heal party · free</button>';
 else{dialog.innerHTML+='<div class="recovery-choices">'+Object.keys(T.items).map(id=>'<button class="button secondary '+(item===id?'selected':'')+'" data-recovery-item="'+id+'" aria-pressed="'+(item===id)+'">'+T.items[id].name+' ×'+(s.inventory[id]||0)+'</button>').join('')+'</div><p>'+T.items[item].description+'</p><div class="recovery-targets">'+members().map(m=>{const hp=T.health(s,m.id),usable=T.items[item].revive?hp===0:hp>0&&hp<10000;return '<article class="recovery-target"><div class="recovery-portrait">'+CharacterRig.art(m.type)+'</div><div><h3>'+m.name+'</h3><p>'+(!hp?'Fallen':percent(hp)+' HP')+'</p><meter min="0" max="10000" value="'+hp+'" aria-label="'+m.name+' health"></meter></div><button class="button secondary" data-recovery-target="'+m.id+'" '+(locked||!s.inventory[item]||!usable?'disabled':'')+'>'+(T.items[item].revive?'Revive':'Heal')+'</button></article>';}).join('')+'</div><p class="item-note">Buy supplies inside city shops. Entering a city restores your party; forest camp rest is also free.</p>';}
 dialog.innerHTML+='<button class="text-button recovery-close">Back to adventure</button>';
 if(focus?.storeBuy)dialog.querySelector('[data-store-buy="'+focus.storeBuy+'"]')?.focus({preventScroll:true});if(focus?.recoveryItem)dialog.querySelector('[data-recovery-item="'+focus.recoveryItem+'"]')?.focus({preventScroll:true});if(focus?.recoveryTarget)dialog.querySelector('[data-recovery-target="'+focus.recoveryTarget+'"]')?.focus({preventScroll:true});
}
dialog.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('.recovery-close')){dialog.close();return;}if(b.dataset.storeBuy){notice=P.buy(b.dataset.storeBuy)?W.ITEMS[b.dataset.storeBuy].name+' added to your bag. '+P.snapshot().coins+' coins remaining.':P.error()||'Purchase unavailable. Your coins were kept.';render();}if(b.dataset.recoveryItem){item=b.dataset.recoveryItem;notice='';render();}if(b.dataset.recoveryTarget){notice=P.recover(item,b.dataset.recoveryTarget)?'Recovery applied. '+(P.snapshot().inventory[item]||0)+' remaining.':P.error()||'Cannot use that item on this target now.';render();}if(b.hasAttribute('data-sanctuary-rest')){notice=P.rest()?'Your trainer and all companions are fully recovered. Ready for the road.':P.error()||'Recovery is unavailable while an encounter is reserved.';render();}};
dialog.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else document.querySelector('#region-map')?.focus({preventScroll:true});});
document.addEventListener('click',e=>{if(e.target.closest('[data-open-recovery]'))open('field',e.target.closest('[data-open-recovery]').dataset.openRecovery);});
function open(next='field',selected){if(next==='sanctuary'&&P.snapshot().map!==BondOpening.start.map)next='field';mode=['field','shop','sanctuary'].includes(next)?next:'field';if(T.items[selected])item=selected;notice='';returnFocus=document.activeElement;render();if(!dialog.open)dialog.showModal();const title=dialog.querySelector('h2');title.tabIndex=-1;title.focus({preventScroll:true});dialog.scrollTop=0;}
root.BondRecovery={open,bars};
})(globalThis);
