'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({});
for(const file of JSON.parse(fs.readFileSync(path.join(root,'data/simulator-modules.json'),'utf8')))vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
let checks=0;
function check(code,message){assert.equal(vm.runInContext(code,ctx),true,message);checks++;console.log('PASS '+message);}
vm.runInContext(`const A=BondApprenticeTree,G=BondGrowth,R=BondProgress;
const full=Object.fromEntries(A.nodes.map(n=>[n.id,3]));
function fixture(level=18,ranks=full){return {character:{name:'Apprentice',weapon:'dagger'},trainerXP:R.threshold(level),progression:{specialization:null},growth:{apprentice:{...ranks}},attributes:{str:10,agi:5,vit:5,int:5,dex:5,leadership:10},companions:[{id:'m',type:'acornboar',xp:0,growth:{}}]};}
function battle(s,extra={}){const build=BondGame.soloBuild(s.progression.specialization||'apprentice');build[0][1]={type:'acornboar',instanceId:'m',skills:[...BondContent.UNITS.acornboar.default]};return new BondGame.Battle(build,{profile:s,seed:314,...extra});}
function summary(b){return JSON.stringify({events:b.events,units:b.units.map(u=>({id:u.id,hp:u.hp,maxHp:u.maxHp,interval:u.interval,growth:u.growth,effective:u.effective})),winner:b.winner});}`,ctx);
check(`[1,2,17,18,20,60].every(l=>G.budget(fixture(l),'apprentice')===Math.min(l,18))`,'One point per level from one, capped at eighteen');
check(`A.nodes.length===6&&A.nodes.every(n=>n.max===3)&&A.nodes.filter(n=>n.parent).length===3&&G.used(A.clean(full,17))===17&&G.used(A.clean(full,18))===18`,'Six three-rank talents finish at level eighteen, never seventeen');
check(`!A.gate('apprentice:force',{'apprentice:practice':2})&&A.gate('apprentice:force',{'apprentice:practice':3})&&Object.keys(A.clean({'apprentice:force':3},18)).length===0`,'Second talents require the first at full rank');
check(`(()=>{const raw={...full,'apprentice:practice':2,'apprentice:health':-3,'apprentice:footwork':'3',bond:10},r=A.clean(raw,4);return G.used(r)===2&&!r['apprentice:force']&&!r.bond&&JSON.stringify(A.clean(r,4))===JSON.stringify(r);})()`,'Cleaning rejects orphan, malformed, obsolete and over-budget ranks');
check(`(()=>{const v=A.bonuses(full);return Math.abs(v.attack-.12)<1e-10&&Math.abs(v.hp-.18)<1e-10&&v.agi===6;})()`,'Full tree gives twelve percent damage, eighteen percent HP and six AGI');
check(`(()=>{const on=battle(fixture()),off=battle(fixture(18,{})),a=on.trainer(0),b=off.trainer(0);return a.maxHp===Math.round(b.maxHp*1.18)&&a.effective.agi===b.effective.agi+6&&a.interval<b.interval&&Math.abs(a.growth.attack-.12)<1e-10;})()`,'Battle initialization applies HP and classic AGI bonuses once');
check(`(()=>{for(const weapon of ['dagger','bow'])for(const active of [false,true]){const strikes=[];for(const ranks of [{},full]){const s=fixture(18,ranks);s.character.weapon=weapon;const build=BondGame.soloBuild('apprentice');build[0][0]=BondOpening.build(s.character);const b=new BondGame.Battle(build,{profile:s,seed:17}),u=b.trainer(0),t=b.units.find(u=>u.side===1);u.position={...t.position};b.effects.direct=(source,target,amount)=>{strikes.push(amount);return {hit:true,damage:amount,absorbed:0};};const skill=active?BondContent.SKILLS[u.skills.find(k=>BondContent.SKILLS[k].kind==='hit')]:undefined;if(active&&!skill)return false;b.strike(u,t,active?skill.amount:u.power,'Training test',skill);}if(Math.abs(strikes[1]/strikes[0]-1.12)>1e-10)return false;}return true;})()`,'Training damage scales dagger and bow basics and active hits by exactly twelve percent');
check(`(()=>{const s=fixture(),before=JSON.stringify(s.attributes),on=battle(s),off=battle(fixture(18,{}));return before===JSON.stringify(s.attributes)&&JSON.stringify(on.units.slice(1).map(u=>[u.maxHp,u.effective,u.growth,u.interval]))===JSON.stringify(off.units.slice(1).map(u=>[u.maxHp,u.effective,u.growth,u.interval]));})()`,'Allocated attributes, Leadership sharing, companions and enemies stay unchanged');
check(`(()=>{for(const type of BondContent.CLASSES){const s=fixture(20);s.progression.specialization=type;const archived=battle(s);s.growth.apprentice={};if(summary(archived.run())!==summary(battle(s).run())||G.unlocked(s,'apprentice')||G.budget(s,type)!==2)return false;s.trainerXP=R.threshold(60);if(G.budget(s,type)!==15)return false;}return true;})()`,'All four class battles ignore archived training and keep separate point budgets');
check(`(()=>{const old=fixture();old.growth.apprentice={bond:3,might:2};const legacy=battle(old,{apprenticeTrees:0}).trainer(0),current=battle(old).trainer(0);return legacy.growth.hp===.06&&legacy.growth.attack===.05&&current.growth.hp===0&&current.growth.attack===0&&legacy.effective.agi===current.effective.agi;})()`,'Version zero retains retired Apprentice ranks without new training effects');
check(`summary(battle(fixture(),{apprenticeTrees:0}).run())===summary(battle(fixture(18,{}),{apprenticeTrees:0}).run())`,'Legacy battles cannot pick up new Apprentice ranks');
check(`summary(battle(fixture()).run())===summary(battle(fixture()).run())`,'Seeded Apprentice combat is deterministic');
check(`G.unlocked(fixture(),'apprentice')&&!G.unlocked({},'apprentice')&&!G.unlocked({character:{legacy:true}},'apprentice')`,'Only an existing unascended Apprentice can spend training points');
console.log('PASS '+checks+' Apprentice rules and combat regressions');
