/* Behavioral contracts for workbook mechanics; shared by Node and browser. */
(function(root){
'use strict';
function run(){
 const checks=[];const check=(name,condition)=>{checks.push({name,ok:!!condition});if(!condition)throw Error(name);};
 function blank(){const b=new BondGame.Battle(BondGame.defaultBuild(),{seed:5});for(const u of b.units){u.hp=u.maxHp=1000;u.passive=null;u.statRules=false;u.growth={armor:0,attack:0};u.effective={str:0,agi:0,vit:0,int:0,dex:0};u.pools=[];u.shield=0;u.effects={};u.kit={number:0,losses:[]};u.talents={};u.cds=u.skills.map(()=>999);u.actionRemaining=999;u.regenPerSecond=0;}b.effects.entities=[];b.effects.queue=[];b.events=[];return b;}
 {const b=blank(),f=b.effects,t=b.trainer(0),a=b.units[1],e=b.trainer(1);f.shield(a,t,100,4,'First');f.shield(t,t,300,2,'Second');check('Distinct shields share a 25% HP ceiling',t.shield===250);b.damage(e,t,180,'hit',true,{category:'magic',direct:true});check('Earliest shield expires/absorbs first',t.hp===1000&&t.pools.length===1&&t.pools[0].label==='First'&&t.shield===70);b.time=4;f.syncShield(t);check('Shields expire on their exact deadline',t.shield===0);}
 {const b=blank(),t=b.trainer(0),e=b.trainer(1);b.effects.shield(t,t,125,4,'ward');b.damage(e,t,100,'shield breaker',true,{category:'magic',shieldBonus:.25});check('Shield-only bonus can break without HP spill',t.shield===0&&t.hp===1000);b.effects.shield(t,t,125,4,'ward');b.damage(e,t,200,'shield breaker',true,{category:'magic',shieldBonus:.25});check('Shield-only bonus cannot amplify overflow',t.hp===925);}
 {const b=blank(),f=b.effects,t=b.trainer(0),g=b.units[1],other=b.units[2],e=b.trainer(1);g.hp=20;f.put(g,g,'Intercept','intercept',.3,3,{target:t.id});f.put(other,other,'Intercept','intercept',.2,3,{target:t.id});f.shield(t,t,100,5,'ward');b.damage(e,t,300,'hit',true,{category:'magic'});check('Exactly one guardian, capped by remaining HP, after shields',t.hp===820&&g.hp===0&&other.hp===1000);}
 {const b=blank(),f=b.effects,t=b.trainer(0),g=b.units[1],e=b.trainer(1);b.effect(g,g,'guard',3);b.damage(e,t,200,'hit',true,{category:'magic'});check('Legacy Guard follows approved 35% cap',t.hp===870&&g.hp===930);}
 {const b=blank(),f=b.effects,u=b.units[1];u.position={x:30,y:50};const e=BondCombatEntities.spawn(f,u,'soldier-ant');check('Summon lives outside encounter actor collection',!!e&&!b.units.includes(e)&&!e.encounterActor);const core=f.core(u);check('Ordinary support excludes temporary entities',!core.includes(e)&&core.length===3);b.time=e.until;BondCombatEntities.step(f);check('Expiry emits no eligible defeat',e.hp===0&&!b.events.some(v=>v.kind==='defeat'&&v.target===e.id));}
 {const b=blank(),f=b.effects,u=b.units[1];const a=BondCombatEntities.spawn(f,u,'trickster-spirit'),c=BondCombatEntities.spawn(f,u,'guardian-spirit',{assigned:b.trainer(0)}),third=BondCombatEntities.spawn(f,u,'trickster-spirit');check('Spirit variants share one owner cap',!!a&&!!c&&!third);b.damage(b.trainer(1),u,2000,'kill',true,{category:'magic'});check('Owner death clears every owned entity',!alive(a)&&!alive(c));}
 {const b=blank(),f=b.effects,u=b.units[1],t=b.trainer(1);u.position={x:30,y:50};t.position={x:38,y:50};const e=BondCombatEntities.spawn(f,u,'imperial-hearth');for(let i=0;i<100;i++){b.time=i*.05;BondCombatEntities.step(f);}check('Hearth has exactly four pulses and cannot be targeted',b.events.filter(v=>v.kind==='pulse'&&v.entity===e.id).length===4&&!f.enemies(t).includes(e));}
 {const b=blank(),f=b.effects,u=b.trainer(0),t=b.trainer(1);u.position={x:30,y:50};t.position={x:36,y:50};u.critChance=1;const hit=f.direct(u,t,100,'crit',{category:'melee',guaranteed:true});check('Landed physical critical deals 1.4x',hit.critical&&hit.damage===140);const magic=f.direct(u,t,100,'magic',{category:'magic',guaranteed:true});check('Magic does not critically hit',!magic.critical&&magic.damage===100);const proc=f.proc(u,t,100,'melee','proc',{guaranteed:true});check('Secondary packets cannot critically hit',!proc.critical&&proc.damage===100);}
 {const b=blank(),f=b.effects,t=b.trainer(0),e=b.trainer(1);t.hp=1;f.later(t,t,.1,()=>f.heal(t,t,1000,'future'));b.damage(e,t,100,'terminal',true,{category:'magic'});check('Trainer death cancels pending recovery immediately',b.ended&&t.hp===0&&f.queue.length===0);}
 {const b=blank(),f=b.effects,t=b.trainer(0),e=b.trainer(1);t.talents={KB4:2,KB5:1};b.damage(e,t,100,'stagger',true,{category:'magic'});check('Stagger splits only post-defense HP damage',t.hp===920&&Math.abs(t.debt.reduce((n,d)=>n+d.amount,0)-20)<.001);f.heal(t,t,20,'heal');check('Citadel removes debt from effective healing only',Math.abs(t.debt.reduce((n,d)=>n+d.amount,0)-15)<.001);f.shield(t,t,200,5,'ward');b.time=1;f.tick();check('Debt ticks bypass new shields',t.shield===200&&t.hp<940);}
 {const b=blank(),f=b.effects,u=b.units[1],t=b.trainer(1);u.position={x:30,y:50};t.position={x:40,y:50};f.dot(u,t,'test burn',60,3,'magic');for(let i=1;i<=60;i++){b.time=i*.05;f.tick();}check('Damage-over-time honors the endpoint tick',t.hp===940);}
 {const b=blank(),f=b.effects,t=b.trainer(0),e=b.trainer(1),a=b.units[1];a.position={x:32,y:50};t.position={x:10,y:50};e.position={x:38,y:50};check('Nearest core target is selected',b.target(e)===a);a.position={x:70,y:50};b.units[2].position={x:88,y:75};check('Normal targeting follows live nearest distance',b.target(e)===t);}
 {for(const type of BondContent.CLASSES){const nodes=BondClassTrees.nodes(type),prefix=nodes[0].id.slice(0,-1);check(type+' rejects a capstone without its branch',!BondClassTrees.gate(type,prefix+'5',{[prefix+'1']:2,[prefix+'2']:2}));const ranks={[prefix+'1']:2,[prefix+'2']:2,[prefix+'3']:1,[prefix+'4']:2};check(type+' accepts seven branch points plus full advanced',BondClassTrees.gate(type,prefix+'5',ranks));}}
 check('All signatures and general moves have authored mechanics',BondCombatKits.definitions.size===315&&Object.keys(BondCombatCatalog.skills).every(id=>BondCombatKits.definitions.has(id)));
 check('All species preserve five or more valid options',BondRules.validate().length===0);
 {const b=blank(),f=b.effects,u=b.units[1],t=b.trainer(1),id='sig-stormowl-thunderhead-totem';u.position={x:30,y:50};t.position={x:35,y:50};u.skills=[id];u.cds=[0];b.obstacles=[{x:50,y:50,radius:100}];const casts=u.casts;check('Blocked deployment spends neither cooldown nor action and emits no cast',!b.cast(u,BondContent.SKILLS[id])&&u.cds[0]===0&&u.casts===casts&&!b.events.some(e=>e.kind==='cast'));}
 {const b=blank(),f=b.effects,u=b.trainer(0),t=b.trainer(1);u.type='hunter';u.talents={HT1:2};u.position={x:30,y:50};t.position={x:35,y:50};t.effective.agi=10000;const c=new BondCombatKits.Context(f,u,{id:'shot',kind:'hit'});c.primary={kind:'damage',target:t};c.results=[{primary:true,hit:true,target:t}];BondClassTalents.afterCast(f,c);b.random=()=>0;b.time=2;f.tick();check('An attached snare cannot miss a second time',b.events.some(e=>e.kind==='damage'&&e.text==='Anchorline'&&e.amount>0)&&!b.events.some(e=>e.kind==='dodge'));}
 {const b=blank(),f=b.effects,u=b.trainer(0);u.storyMaster=true;for(const ally of b.team(0).filter(a=>a!==u))ally.hp=0;const c=new BondCombatKits.Context(f,u,{id:'mend',kind:'heal'});BondClassTalents.afterCast(f,c);b.time=2;f.tick();check('The rescue master cannot queue a heal for an absent player party',f.queue.length===0);}
 {const b=blank(),f=b.effects,t=b.trainer(0),e=b.trainer(1);f.barriers.push({owner:t,amount:100,until:5});b.damage(e,t,40,'poison',false,{dot:true,direct:false,category:'magic'});check('Shared barrier absorbs damage-over-time after personal shields',t.hp===1000&&f.barriers[0].amount===60);}
 {const b=blank(),f=b.effects,u=b.units[1],t=b.trainer(1);u.kit.number=6;u.hp=500;u.position={x:30,y:50};t.position={x:35,y:50};const M=f.stats(u).M;f.put(u,t,'Drowsy','activeWeakness',.15,3,{harmful:true});f.begin();f.direct(t,u,100,'spell',{category:'magic',active:true,guaranteed:true});check('Dream Sipper waits for active damage',u.hp===415);f.finish();check('Dream Sipper heals its living owner once',u.hp===415+Math.round(.35*M));}
 {const b=blank(),f=b.effects,u=b.units[1],t=b.trainer(1);f.put(u,t,'Drowsy','activeWeakness',.15,3,{harmful:true});check('Cleanse removes harmful positive-valued marks',f.cleanse(t,t)===1&&!f.has(t,'Drowsy'));}
 {const b=blank(),f=b.effects,u=b.trainer(0),t=b.trainer(1);u.talents={HD1:2,HD4:2};u.kit.Focus=3;f.put(u,u,'Patient Aim','crit',.15,75);const c=new BondCombatKits.Context(f,u,{id:'shot',kind:'hit'});c.mods={bonus:0};BondClassTalents.beforeCast(f,c);check('Spending Focus lowers critical chance immediately',u.kit.Focus===2&&Math.abs(f.value(u,'crit')-.1)<1e-9);}
 {const b=blank(),f=b.effects,u=b.trainer(0),t=b.trainer(1);u.position={x:30,y:50};t.position={x:35,y:50};u.talents={HD5:1};const c=new BondCombatKits.Context(f,u,{id:'shot',kind:'hit'});c.primary={kind:'damage',target:t};c.results=[{primary:true,hit:false,target:t}];c.mods={perfectArrow:true};const before=t.hp;BondClassTalents.afterCast(f,c);check('Perfect Arrow resolves even when the primary shot misses',t.hp===before-Math.round(.9*f.stats(u).A));}
 {const b=blank(),f=b.effects,u=b.units[1],t=b.trainer(1);f.put(t,u,'Brittle','shieldWeakness',.25,3,{harmful:true});f.shield(u,u,100,3,'ward');check('Brittle reduces only the next shield by 25%',u.shield===75&&!f.has(u,'Brittle'));}
 {const b=blank(),f=b.effects,u=b.units[1],t=b.trainer(1);u.kit.number=12;u.kit.Ribs=3;u.position={x:30,y:50};t.position={x:35,y:50};f.begin();f.direct(t,u,100,'area',{category:'magic',area:true});const cut=b.events.length;f.direct(t,b.units[2],100,'area',{category:'magic',area:true,ignoreRange:true});f.finish();const counter=b.events.findIndex(e=>e.kind==='damage'&&e.text.includes('Rib Reserve'));check('Area packets precede their retaliation',counter>=cut&&b.events.slice(cut,counter).some(e=>e.kind==='damage'&&e.target===b.units[2].id));}
 {const b=blank(),f=b.effects,u=b.trainer(0);u.hp=500;b.heal(u,u,50,'heal');check('A heal appears once in performance events',b.events.filter(e=>e.kind==='heal').length===1);}
 const executions=[];
 for(const d of BondCombatKits.definitions.values()){
  let accepted=false;
  for(let variant=0;variant<6&&!accepted;variant++){
   const b=blank(),f=b.effects,u=b.units[1],type=d.owner||'glowcap',base=BondContent.UNITS[type];Object.assign(u,{type,basePower:base.power,attackBase:base.attackBase,basicCategory:base.basicCategory,delivery:base.delivery,range:base.range,workbookNumber:base.workbookNumber,passive:base.passive,skills:[d.id],cds:[0]});u.kit.number=base.workbookNumber;if(variant===5)b.time=4;
   for(const [i,a] of b.units.entries()){a.position={x:a.side?43:35,y:48+(i%3)*4};a.previousPosition={...a.position};a.hp=variant===1?1000:variant===2?600:500;a.delivery='ranged';a.targetId=u.id;}
   u.position={x:38,y:48};if(variant===4){b.trainer(0).position={x:40,y:48};for(const enemy of b.team(1))enemy.position.x=55;}b.refreshTargets();if(variant===3)f.shield(u,u,100,5,'test');
   f.put(u,u,'Remembered Note','record',1,3,{record:{kind:variant===4?'heal':'damage',amount:100,category:'magic'}});
   const skill=BondContent.SKILLS[d.id];accepted=b.cast(u,skill);if(accepted){for(let i=1;i<=130&&!b.ended;i++){b.time+=.05;f.tick();}if([...b.units,...f.entities].some(x=>!Number.isFinite(x.hp)||!Number.isFinite(x.shield)))throw Error('Nonfinite skill output: '+d.id);}
  }
  if(!accepted)throw Error('No valid fixture casts '+d.id);executions.push(d.id);
 }
 check('Every one of the 315 moves executes under a legal condition',executions.length===315);
 const metrics=[];
 for(const build of BondCombatCatalog.builds){
  const type=build.owner,skills=build.skills.map(name=>[...BondCombatKits.definitions.values()].find(s=>s.name===name&&(s.owner===type||s.owner===null)).id),team=[{type:'swordsman',skills:[...BondContent.UNITS.swordsman.default]},{type,skills},{type:'glowcap',skills:[...BondContent.UNITS.glowcap.default]}];
  if(type==='glowcap')team[2]={type:'emberfox',skills:[...BondContent.UNITS.emberfox.default]};
  const b=new BondGame.Battle([team,BondGame.defaultBuild()[1]],{seed:57});for(let i=0;i<240&&!b.ended;i++)b.step();
  if(b.units.some(u=>!Number.isFinite(u.hp)||u.hp<0)||b.effects.entities.some(u=>!Number.isFinite(u.hp)))throw Error('Invalid state: '+type+' '+build.name);
  metrics.push({type,name:build.name,tick:b.tick,casts:b.units[1].casts,entities:b.events.filter(e=>e.kind==='summon'&&e.actor===b.units[1].id).length});
 }
 check('All 200 proposed monster loadouts simulate with finite state',metrics.length===200);
 for(const build of BondCombatCatalog.allocations){
  const nodes=BondClassTrees.nodes(build.type),ranks=Object.fromEntries(nodes.map((n,i)=>[n.id,build.ranks[i]])),team=[{type:build.type,skills:[...BondContent.UNITS[build.type].default]},{type:'glowcap',skills:[...BondContent.UNITS.glowcap.default]},{type:'elderroot',skills:[...BondContent.UNITS.elderroot.default]}];
  const b=new BondGame.Battle([team,BondGame.defaultBuild()[1]],{seed:91});b.trainer(0).talents=BondClassTrees.clean(build.type,ranks);for(let i=0;i<400&&!b.ended;i++)b.step();
  check(build.type+' talent build: '+build.name,b.units.every(u=>Number.isFinite(u.hp)&&u.hp>=0)&&b.effects.entities.every(e=>Number.isFinite(e.hp)));
 }
 return {checks,metrics};
}
const alive=u=>u&&u.hp>0&&!u.eliminated;
root.BondWorkbookTests={run};
})(globalThis);
