"""Move knowledge, city services and the Inner Sea hierarchy in disposable saves."""
import argparse, functools, json, threading, traceback
from http.server import ThreadingHTTPServer
from browser_check import ROOT, ARTIFACTS, QuietServer, find_browser, legacy_adventure, sync_playwright

parser=argparse.ArgumentParser();parser.add_argument('--browser',default='chrome',choices=['chrome','edge']);args=parser.parse_args()
server=ThreadingHTTPServer(('127.0.0.1',0),functools.partial(QuietServer,directory=str(ROOT)))
threading.Thread(target=server.serve_forever,daemon=True).start()
checks=[];errors=[]
def check(name,ok):
    checks.append({'name':name,'pass':bool(ok)});print(('PASS ' if ok else 'FAIL ')+name,flush=True)

with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=find_browser(args.browser),headless=True)
    page=browser.new_page(viewport={'width':390,'height':844});legacy_adventure(page)
    page.add_init_script("localStorage.setItem('bond-bolt-profile-v7','normal-save-sentinel')")
    page.on('pageerror',lambda e:errors.append(str(e)))
    try:
        page.goto(f'http://127.0.0.1:{server.server_port}/?test=1');page.wait_for_function('!!window.BondApp')
        check('All 100 species start with one signature and two basics, finish at 48, and have spaced basic lessons',page.evaluate("""()=>BondContent.MONSTERS.every(type=>{const M=BondCompanionMoves,p=M.plan(type),start=M.initial(type),sign=M.signatures(type),a={type,xp:0,movesVersion:1,skills:start};return start.length===3&&start.filter(M.signature).length===1&&new Set(p.map(x=>x.id)).size===p.length&&Math.max(...p.map(x=>x.level))===48&&p.filter(x=>!x.signature&&x.level>1).length===(sign.length===4?3:2)&&M.learned(a).length===3&&sign.every(id=>M.learned({...a,xp:BondProgress.threshold(48)}).includes(id));})"""))
        page.evaluate("""()=>{const P=BondProfile,s=P.fresh();s.character={name:'Rowan',weapon:'dagger'};s.journey.early.introFightWon=true;s.journey.early.mageGate=true;s.journey.early.tidecrown=false;s.trainerXP=BondProgress.threshold(20);P.testing.replace(s);window.first=P.summon('acornboar','apprentice',P.testing.grantEcho('acornboar',1));window.second=P.summon('astralfox','apprentice',P.testing.grantEcho('astralfox',1));BondApp.changeUnit(0,1,first.instanceId);BondApp.changeUnit(0,2,second.instanceId);window.atService=kind=>{const s=P.snapshot(),map=BondAtlas.get('clearing-hub'),npc=map.residents.find(r=>r.service===kind);s.map=map.id;s.area=map.region;s.position={x:npc.x,y:npc.y};P.testing.replace(s);BondApp.switchTab('region');return npc.id;};}""")
        check('New summon loadouts have exactly one signature',page.evaluate('BondProfile.companions().every(m=>m.skills.filter(BondCompanionMoves.signature).length===1)'))
        check('Duplicate Echo stays owned and original receipt retries remain idempotent',page.evaluate("""()=>{const P=BondProfile,id=P.testing.grantEcho('acornboar',9),before=P.snapshot();return !P.summon('acornboar','apprentice',id)&&P.snapshot().echoes.acornboar.length===before.echoes.acornboar.length&&P.summon('acornboar','apprentice',first.id).repeated===true&&P.companions('acornboar').length===1;}"""))
        check('Locked signatures cannot be equipped',page.evaluate("!BondProfile.setSkills(first.instanceId,BondContent.UNITS.acornboar.default)"))
        check('Earned moves survive XP loss without changing the chosen loadout',page.evaluate("""()=>{const P=BondProfile,id=first.instanceId,skills=P.getCompanion(id).skills.join();P.testing.setXP(id,BondProgress.threshold(48));const learned=BondCompanionMoves.learned(P.getCompanion(id));P.testing.setXP(id,0);return learned.join()===BondCompanionMoves.learned(P.getCompanion(id)).join()&&P.getCompanion(id).skills.join()===skills;}"""))
        check('Each city has reachable tutor and reset NPCs',page.evaluate("BondAtlas.maps.filter(m=>m.kind==='hub').every(m=>['moves','talents'].every(kind=>{const r=m.residents.find(r=>r.service===kind);return r&&!BondAtlas.collision(m.id,r)&&BondNav.find(m.id,m.entry,r).ok;}))"))
        page.evaluate("window.tutor=atService('moves');BondCityView.resident(tutor)")
        check('Tutor lists only the two active companions and all eleven General moves',page.locator('[data-service-companion]').count()==2 and page.locator('[data-teach-move]').count()==11)
        page.locator('[data-teach-move="general-greater-heal"]').click()
        check('A tutor lesson persists and becomes equipable across species pools',page.evaluate("BondProfile.getCompanion(first.instanceId).taughtMoves.includes('general-greater-heal')&&BondProfile.setSkills(first.instanceId,['general-greater-heal',...BondCompanionMoves.initial('acornboar').slice(0,2)])"))
        check('Learned move is disabled against double clicks',page.locator('[data-teach-move="general-greater-heal"]').is_disabled())
        check('Teaching failures never spend or learn',page.evaluate("""()=>{const P=BondProfile,before=P.export(),set=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('full')};let result;try{result=P.teachMove(tutor,first.instanceId,'general-heavy-attack');}finally{Storage.prototype.setItem=set;}return !result&&P.export()===before;}"""))
        check('Tutored General moves run in deterministic combat',page.evaluate("""()=>{const build=BondApp.getBuild(),profile=BondProfile.snapshot(),one=new BondGame.Battle(build,{profile,seed:11}).run(),two=new BondGame.Battle(build,{profile,seed:11}).run();return one.ended&&two.ended&&JSON.stringify(one.events)===JSON.stringify(two.events)&&one.units.every(u=>Number.isFinite(u.hp));}"""))
        page.locator('[data-service-close]').click()
        check('Remote, invalid and inactive tutor commands are rejected',page.evaluate("""()=>{const P=BondProfile;BondApp.changeUnit(0,1,null);const inactive=!P.teachMove(tutor,first.instanceId,'general-heavy-attack');BondApp.changeUnit(0,1,first.instanceId);const invalid=!P.teachMove(tutor,first.instanceId,BondCompanionMoves.signatures('astralfox')[0]);P.travel('clearing-hub',{x:400,y:400});return inactive&&invalid&&!P.teachMove(tutor,first.instanceId,'general-heavy-attack');}"""))
        page.evaluate("window.resetNPC=atService('talents');BondProfile.learn(first.instanceId,BondGrowth.nodes('acornboar')[0].id);BondCityView.resident(resetNPC)")
        check('Free companion reset is unavailable',page.evaluate('!BondProfile.respec(first.instanceId)'))
        check('Failed reset persistence preserves the Echo and ranks',page.evaluate("""()=>{const P=BondProfile,before=P.export(),set=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('full')};let result;try{result=P.resetCompanionTalents(resetNPC,first.instanceId);}finally{Storage.prototype.setItem=set;}return !result&&P.export()===before;}"""))
        page.locator('[data-service-reset]').click()
        check('Reset consumes one matching Echo and refunds all talents once',page.evaluate("!BondGrowth.used(BondProfile.getCompanion(first.instanceId).growth)&&BondProfile.snapshot().echoes.acornboar.length===0&&!BondProfile.resetCompanionTalents(resetNPC,first.instanceId)"))
        page.locator('[data-service-close]').click()
        check('Reset without an Echo leaves invested talents intact',page.evaluate("""()=>{const P=BondProfile,id=BondGrowth.nodes('acornboar')[0].id;P.learn(first.instanceId,id);return !P.resetCompanionTalents(resetNPC,first.instanceId)&&P.getCompanion(first.instanceId).growth[id]===1;}"""))
        check('All four class choices refund attributes and keep companion progress',page.evaluate("""()=>{const P=BondProfile,original=P.snapshot(),ok=BondContent.CLASSES.every(type=>{const s=structuredClone(original);s.progression.specialization=null;s.journey.early.tidecrown=true;s.journey.early.demonstrations=Object.values(BondCampaign.DEMONSTRATIONS);s.journey.early.trials[type]=true;s.attributes.str=10;P.testing.replace(s);const companion=JSON.stringify(P.snapshot().companions);if(!P.specialize(type))return false;const now=P.snapshot();return BondProgress.ATTRS.every(k=>now.attributes[k]===1)&&JSON.stringify(now.companions)===companion;});P.testing.replace(original);return ok;}"""))
        check('Legacy saves keep individuals and their separately saved valid loadout',page.evaluate("""()=>{const P=BondProfile,original=P.snapshot(),build=BondApp.getBuild(),s=P.fresh(),type='acornboar';s.companions=[{id:'old:one',type,xp:0,skills:BondContent.UNITS[type].default,growth:{}},{id:'old:two',type,xp:0,skills:BondContent.UNITS[type].default,growth:{}}];P.testing.replace(s);const skills=['general-heavy-attack',...BondContent.UNITS[type].default.slice(0,2)],team=BondGame.soloBuild()[0];team[1]={type,skills};const migrated=P.migrateParty(team),ok=P.companions().length===2&&migrated[1].instanceId==='old:one'&&migrated[1].skills.join()===skills.join()&&BondCompanionMoves.learned(P.getCompanion('old:one')).includes(skills[0]);P.testing.replace(original);for(const i of [1,2])BondApp.changeUnit(0,i,build[0][i]?.instanceId||null);return ok;}"""))
        page.evaluate("BondApp.switchTab('loadout');BondMenu.open('inventory')")
        check('Bag contains Inventory without management tabs',page.locator('.game-menu-heading h2').inner_text()=='Inventory' and page.locator('#teams>.menu-nav').count()==0)
        page.locator('[data-frame-menu="collection"]').click()
        check('Inner Sea has the three requested top-level tabs',page.locator('[data-sea-tab]').all_text_contents()==['Sea land','Trainer','Party'])
        page.locator('[data-sea-tab="trainer"]').click()
        check('Trainer holds attributes, Class Skill Tree and Equipment',page.locator('[data-stat]').count()==6 and page.locator('[data-collection-mode]').all_text_contents()==['Class Skill Tree','Equipment'])
        page.locator('[data-sea-tab="party"]').click()
        check('Party has the three requested subsections',page.locator('[data-collection-mode]').all_text_contents()==['My companions','Formation','Species Guide'])
        check('Companion overview is concise with mastery above the portrait',page.evaluate("()=>{const p=document.querySelector('.companion-profile');return p.firstElementChild.matches('[data-open-tree]')&&!p.querySelector('.creature-subtitle,[data-open-recovery],[data-add],[data-summon],.habitat-source')&&!p.textContent.includes('#1');}"))
        check('Signature moves have distinct styling',page.locator('.ability-choice.signature-move').count()==3 and page.locator('.priority-slot.signature-move').count()==1)
        page.evaluate("()=>{const s=BondProfile.snapshot();s.inventory['held:acornboar']=1;BondProfile.testing.replace(s);}")
        check('Empty held slot advertises a compatible free item',page.locator('[data-open-equipment] > .upgrade-dot').count()==1)
        page.locator('[data-open-equipment]').click();page.locator('[data-equip-item]').click();page.evaluate("BondApp.switchTab('loadout');BondMenu.open('companions')")
        check('Equipped held item is pictured and named on the companion page',page.locator('.gear-quick .item-art').count()==1 and page.evaluate("BondEquipment.get('held:acornboar').name") in page.locator('.gear-quick').inner_text() and page.locator('.gear-quick > .upgrade-dot').count()==0)
        check('Held badges ignore incompatible items and copies already assigned elsewhere',page.evaluate("""()=>{const s=BondProfile.snapshot();s.companions.push({...structuredClone(s.companions[0]),id:'held:other',heldItem:null});const unavailable=!BondUpgradeNotices.read(s).held.has('held:other');s.inventory['held:acornboar']=2;const available=BondUpgradeNotices.read(s).held.has('held:other');const restricted=BondEquipment.list().find(i=>i.kind==='held'&&i.allowedSpecies.length&&i.allowedSpecies.length<100);s.inventory={[restricted.id]:1};s.companions.at(-1).type=BondContent.MONSTERS.find(t=>!restricted.allowedSpecies.includes(t));const incompatible=!BondUpgradeNotices.read(s).held.has('held:other');return unavailable&&available&&incompatible;}"""))
        page.locator('[data-collection-mode="formation"]').click()
        check('Companion substitution and Dummy test live with Formation',page.locator('[data-slot="1"]').count()==1 and page.locator('#fight').is_visible())
        page.locator('[data-slot="1"]').click();check('Formation opens the owned companion picker',page.locator('#companion-picker').is_visible());page.keyboard.press('Escape')
        for width in [320,390,768,1440]:
            page.set_viewport_size({'width':width,'height':844 if width<1000 else 1000});page.evaluate("BondApp.switchTab('loadout');BondMenu.open('companions')")
            check(f'Companion overview fits {width}px',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
            if width in [390,1440]:page.locator('#panel-loadout').screenshot(path=str(ARTIFACTS/f'companion-overview-{width}.png'))
            page.evaluate("BondCityView.resident(atService('moves'))")
            check(f'Tutor stays inside the game frame at {width}px',page.evaluate("()=>{const r=document.querySelector('#companion-service-dialog').getBoundingClientRect(),f=document.querySelector('#game-frame').getBoundingClientRect();return r.left>=f.left&&r.right<=f.right&&r.top>=f.top-1&&r.bottom<=f.bottom+1;}"))
            page.locator('[data-service-close]').click()
        page.reload();page.wait_for_function('!!window.BondApp')
        check('Move knowledge survives reload',page.evaluate("BondProfile.companions('acornboar')[0].taughtMoves.includes('general-greater-heal')"))
        check('Normal browser save remains untouched',page.evaluate("localStorage.getItem('bond-bolt-profile-v7')==='normal-save-sentinel'"))
    except Exception:errors.append(traceback.format_exc())
    check('No browser or harness errors',not errors);browser.close()
server.shutdown();ARTIFACTS.mkdir(exist_ok=True)
(ARTIFACTS/'companion-services.json').write_text(json.dumps({'checks':checks,'errors':errors},indent=2),encoding='utf-8')
print(json.dumps(errors,indent=2));raise SystemExit(0 if not errors and all(c['pass'] for c in checks) else 1)
