'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({});
for(const file of JSON.parse(fs.readFileSync(path.join(root,'data/simulator-modules.json'),'utf8')))vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
let checks=0;function check(code,label){assert.equal(vm.runInContext(code,ctx),true,label);checks++;console.log('PASS '+label);}
vm.runInContext(`function fixture(type='swordsman'){return {character:{name:'Gear test'},progression:{specialization:type},trainerXP:BondProgress.threshold(60),inventory:{},equipment:{},companions:[],attributes:{str:19,agi:10,vit:10,int:10,dex:10,leadership:10}};}`,ctx);
check('Object.values(BondItemCatalog.items).length===200&&Object.values(BondItemCatalog.drops).every(ids=>ids.length===2&&ids.every(id=>BondItemCatalog.items[id].dropChanceBP===100))','All 200 sheet items have independent 1% source definitions');
check(`(()=>{const s=fixture(),id='equipment:acornboar';s.inventory[id]=1;return !BondEquipment.command(s,'swordsman',id,'weapon')&&BondEquipment.command(s,'swordsman',id,'offhand')&&BondEquipment.free(s,id)===0&&BondEquipment.command(s,'swordsman',null,'offhand')&&s.inventory[id]===1;})()`,'Slots reserve and release one owned copy without minting or destroying it');
check(`(()=>{const s=fixture('mage'),id='equipment:acornboar';s.inventory[id]=1;return !BondEquipment.command(s,'mage',id,'offhand');})()`,'Equipment enforces the sheet class restriction');
check(`(()=>{const s=fixture(),id='equipment:acornboar';s.trainerXP=0;s.inventory[id]=1;return !BondEquipment.command(s,'swordsman',id,'offhand');})()`,'Equipment enforces minimum level');
check(`(()=>{const s=fixture(),id='held:acornboar';s.inventory[id]=1;s.companions=[{id:'a',type:'acornboar'},{id:'b',type:'acornboar'}];return BondEquipment.command(s,'a',id)&&!BondEquipment.command(s,'b',id)&&BondEquipment.command(s,'a',null)&&BondEquipment.command(s,'b',id);})()`,'Repeated species have independent held slots and cannot share a copy');
check(`(()=>{const s=fixture(),before=BondProgress.derived('acornboar',s,BondContent.UNITS.acornboar),id='equipment:emberfox';s.inventory[id]=1;s.equipment.body=id;const after=BondProgress.derived('acornboar',s,BondContent.UNITS.acornboar);return JSON.stringify(before)===JSON.stringify(after)&&BondProgress.derived('swordsman',s).effective.str===21;})()`,'Trainer equipment crosses STR thresholds personally without increasing Leadership sharing');
check(`(()=>{const s=fixture(),id='equipment:acornboar';s.inventory[id]=1;s.equipment.offhand=id;const now=BondProgress.derived('swordsman',s),old=BondProgress.derived('swordsman',s,{...BondContent.UNITS.swordsman,equipment:false});return now.hp>old.hp&&now.hardDefense===.06&&old.hardDefense===0;})()`,'Equipment HP and hard defense are excluded from legacy encounter stats');
check(`(()=>{let e=0,h=0,both=0;for(let i=0;i<100000;i++){const loot=BondEquipment.loot('acornboar',i);e+=!!loot['equipment:acornboar'];h+=!!loot['held:acornboar'];both+=!!loot['equipment:acornboar']&&!!loot['held:acornboar'];if(JSON.stringify(loot)!==JSON.stringify(BondEquipment.loot('acornboar',i)))return false;}return e>850&&e<1150&&h>850&&h<1150&&both>0&&both<30;})()`,'Deterministic salted rolls independently produce equipment, held items, both and neither');
check(`(()=>{const b=new BondGame.Battle(BondGame.defaultBuild());b.run();return b.ended&&b.units.every(u=>Number.isFinite(u.hp));})()`,'An unequipped battle still completes normally');
vm.runInContext(`
function gearFixture(kind,number){
 const item=Object.values(BondItemCatalog.items).find(i=>i.kind===kind&&i.number===number),type=kind==='equipment'?item.classes.find(t=>t!=='apprentice'):'druid',p=fixture(type),species=kind==='held'?(item.allowedSpecies[0]||item.dropSpecies):'acornboar';
 p.inventory[item.id]=1;if(kind==='equipment')p.equipment[item.slot]=item.id;
 p.companions=[{id:'a',type:species,xp:BondProgress.threshold(60),growth:{},heldItem:kind==='held'?item.id:null},{id:'b',type:'bloomslime',xp:BondProgress.threshold(60),growth:{}}];
 const build=BondGame.defaultBuild();build[0]=[{type,skills:[...BondContent.UNITS[type].default]},...p.companions.map(m=>({type:m.type,instanceId:m.id,skills:[...BondContent.UNITS[m.type].default]}))];
 const b=new BondGame.Battle(build,{profile:p,enemyLevel:60,seed:32767});const u=b.units.find(u=>u.side===0&&u.slot===(kind==='held'?1:0));
 return {b,f:b.effects,u,item,p,foe:b.units.find(v=>v.side===1&&v.slot===1),tr:b.units.find(v=>v.side===0&&v.slot===0),ally:b.units.find(v=>v.side===0&&v.slot===2)};
}
function packet(f,u,t,amount=100,extra={}){return f.direct(u,t,amount,'Contract attack',{basic:true,primary:true,category:'melee',guaranteed:true,ignoreRange:true,noCritical:true,...extra});}
function equipmentEvent(x,event,...args){BondEquipmentEffects.each(x.f,event,...args);}
`,ctx);
check(`Object.keys(BondEquipmentEffects.definitions).length===200`,'Every catalog row has an explicit effect definition');
if(!process.argv.includes('--fast'))check(`(()=>{for(const kind of ['equipment','held'])for(let n=1;n<=100;n++){const x=gearFixture(kind,n);if(x.u.gear.items.length!==1)throw Error('Not equipped '+kind+n);x.b.run();if(!x.b.ended||x.b.units.some(u=>!Number.isFinite(u.hp)||u.hp<0))throw Error('Invalid battle '+kind+n);}return true;})()`,'All 200 items complete real battles in eligible class or companion loadouts');
check(`(()=>{const x=gearFixture('equipment',16),base=x.u.interval;return Math.abs(x.f.basicInterval(x.u)-1/.85)<1e-9&&x.u.interval===base;})()`,'Attack-rate penalties change basic cadence without changing ASPD or active cadence');
check(`(()=>{const x=gearFixture('held',69),before=x.f.basicInterval(x.u);x.u.gear.items=[];return Math.abs(before/x.f.basicInterval(x.u)-1/.8)<1e-9;})()`,'Prism Pincer multiplies the species existing basic-rate penalty by its own penalty');
check(`(()=>{const x=gearFixture('equipment',35);const recipients=x.b.units.filter(u=>u.pools.some(p=>p.label===x.item.name));return recipients.length===1&&recipients[0].slot>0&&recipients[0].side===0;})()`,'Held Pebble shields exactly one monster, never the trainer');
check(`(()=>{const x=gearFixture('equipment',11);x.foe.maxHp=x.foe.hp=1000;x.foe.pools=[];x.f.shield(x.foe,x.foe,135,5,'Test shield');const p=x.f.absorb(x.foe,200,x.u,{primary:true,category:'melee'});return p.absorbed===100&&p.remaining===100&&BondEquipmentEffects.change(x.f,'beforeHP',p.remaining,x.u,x.foe,{primary:true,category:'melee'})===95;})()`,'Faultglass splits shield-capacity damage and HP damage at a shield break');
check(`(()=>{const x=gearFixture('equipment',1);x.u.pools=[];x.f.shield(x.u,x.u,80,5,'Own shield');const p=x.f.absorb(x.u,150,x.foe,{primary:true,basic:true,category:'melee'});return p.absorbed===100&&p.remaining===50;})()`,'Acorn-Cup spends reduced self-shield capacity while leaving HP overflow unscaled');
check(`(()=>{const x=gearFixture('equipment',4),d={basic:true,primary:true,category:'melee'},E=BondEquipmentEffects;return E.change(x.f,'incoming',100,x.foe,x.u,{active:true})===100&&E.change(x.f,'incoming',100,x.foe,x.u,d)===50&&E.change(x.f,'incoming',100,x.foe,x.u,d)===100;})()`,'Opening basic protection survives active hits and is spent exactly once');
check(`(()=>{const x=gearFixture('held',4),E=BondEquipmentEffects,d={active:true,primary:true,category:'melee',castId:'enemy:a1'};return E.change(x.f,'incoming',100,x.foe,x.u,{basic:true})===100&&E.change(x.f,'incoming',100,x.foe,x.u,d)===65&&E.change(x.f,'incoming',100,x.foe,x.u,{...d,secondary:true,primary:false})===65&&E.change(x.f,'incoming',100,x.foe,x.u,{...d,castId:'enemy:a2'})===100;})()`,'First-Fang protects every hit of one active cast, then expires');
check(`(()=>{const x=gearFixture('held',100),a={basic:true,primary:true,category:'melee'},b={...a};x.u.shield=1;equipmentEvent(x,'launch',x.foe,x.u,a);equipmentEvent(x,'launch',x.u,x.foe,b);const c={active:true,primary:true,category:'melee'};equipmentEvent(x,'launch',x.foe,x.u,c);return a.noCritical&&b.noCritical&&!c.noCritical;})()`,'Backward Spiral blocks only the specified criticals');
check(`(()=>{const x=gearFixture('held',30),a={basic:true,primary:true,category:'melee'};equipmentEvent(x,'launch',x.foe,x.u,a);const b={...a,noCritical:false};equipmentEvent(x,'launch',x.foe,x.u,b);return a.noCritical&&!b.noCritical;})()`,'Wingveil consumes its first-attack protection at launch, including a miss');
check(`(()=>{const x=gearFixture('equipment',2),d={primary:true,active:true,category:'magic'};equipmentEvent(x,'landed',x.u,x.foe,{damage:1},d);const old=x.foe.hp;BondEquipmentEffects.H.bonus(x.f,x.u,x.foe,10,'magic',x.item);return x.u.gear.items[0].state.q&&x.foe.hp<old;})()`,'Item-generated damage cannot consume or recursively trigger a stored item charge');
check(`(()=>{const x=gearFixture('equipment',2);equipmentEvent(x,'landed',x.u,x.foe,{damage:1},{primary:true,active:true});BondEquipmentEffects.H.isolated(x.f,()=>x.f.later(x.u,x.foe,.1,()=>equipmentEvent(x,'landed',x.u,x.foe,{damage:1},{primary:true,basic:true})));x.b.time=.1;x.f.tick();return !!x.u.gear.items[0].state.q;})()`,'Delayed item effects retain their nonrecursive origin');
check(`(()=>{const x=gearFixture('held',31),H=BondEquipmentEffects.H;H.rate(x.f,x.u,x.ally,x.item,.1,2);H.rate(x.f,x.tr,x.ally,x.item,.1,3);return Object.values(x.ally.effects).filter(e=>e.kind==='itemRate').length===1&&Math.abs(x.f.basicInterval(x.ally)-1/1.1)<1e-9;})()`,'Same-name buffs from multiple sources refresh one ledger entry');
check(`(()=>{const x=gearFixture('held',26),p={source:x.u,delay:1,amount:100};equipmentEvent(x,'delayed',p);const q={source:x.u,delay:.8,amount:100};equipmentEvent(x,'delayed',q);return p.delay===1.5&&p.amount===130&&q.delay===.8&&q.amount===100;})()`,'Forecast Slip changes only primary impacts already delayed at least one second');
check(`(()=>{const x=gearFixture('equipment',26),p={source:x.u,delay:1,amount:100};equipmentEvent(x,'delayed',p);return p.retarget===.6;})()`,'Amber-Rib Focus transfers only the unresolved delayed primary packet at sixty percent');
check(`(()=>{const x=gearFixture('held',46),H=BondEquipmentEffects.H;const fake={...x.ally,id:'summon',temporary:true,slot:1000};x.f.entities.push(fake);return H.core(x.f,x.u).length===3&&!H.core(x.f,x.u).includes(fake)&&H.stats(x.f,x.u).P===(x.u.basicCategory==='magic'?H.stats(x.f,x.u).M:H.stats(x.f,x.u).A);})()`,'Core membership excludes summons and primary scaling follows the designated attack category');
console.log('PASS '+checks+' equipment contracts');
check(`(()=>{const x=gearFixture('held',85);x.f.sharedShield(x.u,[x.tr,x.ally],100,3,'Shared test',{active:true,itemPrimary:true});return Object.values(x.tr.effects).some(e=>e.key.includes(x.item.name))&&!Object.values(x.ally.effects).some(e=>e.key.includes(x.item.name));})()`,'A shared shield has one primary recipient for held-item rider buffs');
check(`(()=>{const x=gearFixture('equipment',12),E=BondEquipmentEffects,H=E.H,before=H.stats(x.f,x.u).M,d={basic:true,primary:true,category:'melee'};const hits=[1,2,3].map(()=>E.change(x.f,'incoming',100,x.foe,x.u,d));return hits.every(n=>n===80)&&E.change(x.f,'incoming',100,x.foe,x.u,d)===100&&H.stats(x.f,x.u).M===before+15;})()`,'Rib Halo spends three protections and then grants flat MATK');
check(`(()=>{const x=gearFixture('held',42);x.f.dot(x.u,x.foe,'Little Embers',90,3,'magic');const e=x.foe.effects['Little Embers'],d={dot:true,dotKey:e.key,dotEffect:e,category:'magic'},E=BondEquipmentEffects;const first=E.change(x.f,'damageAmount',100,x.u,x.foe,d);x.f.dot(x.u,x.foe,'Little Embers',90,3,'magic');d.dotEffect=x.foe.effects['Little Embers'];return first===160&&E.change(x.f,'damageAmount',100,x.u,x.foe,d)===85;})()`,'Refreshing an existing burn cannot regenerate Coal-Cheek first-tick damage');
check(`(()=>{const x=gearFixture('held',6);x.b.effect(x.u,x.foe,'slow',4);const initial=x.f.value(x.foe,'hit');delete x.foe.status.slow;return initial===-20&&x.f.value(x.foe,'hit')===0;})()`,'Rate-debuff linked accuracy expires immediately when its legacy slow is removed');
check(`(()=>{const x=gearFixture('equipment',86);x.ally.hp=100;const before=x.ally.hp,M=x.f.stats(x.u).M;x.f.heal(x.u,x.ally,100,'Active heal',{active:true,itemPrimary:true,castId:'split'});const immediate=x.ally.hp-before;x.b.time=1;x.f.tick();return immediate===80&&x.ally.hp>=before+100+Math.round(.3*M);})()`,'Hollow-Trunk resolves the eighty/twenty split and delayed MATK healing');
check(`(()=>{const x=gearFixture('equipment',92),E=BondEquipmentEffects,H=x.u.maxHp,at=.2*H,first=E.change(x.f,'beforeHP',at,x.foe,x.u,{direct:true}),second=E.change(x.f,'beforeHP',at,x.foe,x.u,{direct:true});return Math.abs(first-(at-.3*(at-.12*H)))<1e-8&&second===at;})()`,'Heartamber reduces only excess pending HP damage and activates once');
check(`(()=>{const x=gearFixture('held',87),E=BondEquipmentEffects,base={master:x.u,structure:false};const innate={...base},first={...base,deploymentCast:'cast1'},second={...base,deploymentCast:'cast1'};E.each(x.f,'entityCreated',x.u,innate,{});E.each(x.f,'entityCreated',x.u,first,{});E.each(x.f,'entityCreated',x.u,second,{});return !innate.itemSeed&&first.itemSeed===.35*x.f.stats(x.u).P&&!second.itemSeed;})()`,'Only the first entity of an actual deployment gets Unopened Emberseed');
check(`(()=>{const x=gearFixture('held',5),c=new BondCombatKits.Context(x.f,x.u,{id:x.u.skills[0],kind:'hit'});equipmentEvent(x,'beforeCast',c);BondEquipmentEffects.H.enhance(c,x.item,{noSplash:true});const before=x.foe.hp;const r=packet(x.f,x.u,x.foe,100,{active:true,basic:false,primary:false,secondary:true,area:true,castId:c.itemCastId});return r.damage===0&&x.foe.hp===before;})()`,'Suppressed splash cannot leak minimum one-point damage through armor');
console.log('PASS '+checks+' equipment contracts including detailed effects');

check(`(()=>{for(const type of ['swordsman','hunter','mage','druid']){const s=fixture(type),id='weapon:class:'+type,item=BondEquipment.get(id);s.inventory[id]=1;BondEquipment.clean(s,s);s.trainerXP=BondProgress.threshold(19);if(BondEquipment.command(s,type,id,'weapon'))return false;s.trainerXP=BondProgress.threshold(20);if(!BondEquipment.command(s,type,id,'weapon'))return false;const d=BondProgress.derived(type,s);if(!BondEquipment.equipped(s,null,type,20).includes(id)||item.stats[type==='mage'||type==='druid'?'matk':'atk']!==12||d.itemStats[item.stats.atk?'atk':'matk']!==12)return false;const raw=JSON.parse(JSON.stringify(s));BondEquipment.clean(s,raw);if(s.equipment.weapon!==id||!BondEquipment.command(s,type,null,'weapon')||s.inventory[id]!==1)return false;if(BondEquipment.allowed(item,type==='mage'?'druid':'mage',60))return false;}return BondEquipment.list().length===204&&!Object.values(BondItemCatalog.drops).flat().some(id=>id.startsWith('weapon:'));})()`,'Existing quest weapons equip at level twenty for their own class and never enter monster drops');
check(`(()=>{const x=gearFixture('held',97),E=BondEquipmentEffects;for(const id of ['A','B','A'])E.each(x.f,'damaged',x.foe,x.u,10,0,{active:true,primary:true,category:'magic',castId:id});const state=x.u.gear.items[0].state;return state.n===2&&state.cast.length===2;})()`,'Interleaved hits count each enemy cast only once');
check(`(()=>{const x=gearFixture('equipment',66),E=BondEquipmentEffects;E.each(x.f,'damaged',x.foe,x.u,10,0,{basic:true,primary:true});x.b.time=.5;E.each(x.f,'damaged',{...x.foe,id:'another-enemy'},x.u,10,0,{basic:true,primary:true});x.b.time=1;E.each(x.f,'damaged',x.foe,x.u,10,0,{basic:true,primary:true});return x.u.gear.items[0].state.q?.target===x.foe.id;})()`,'Two quick hits from one enemy still count when another enemy attacks between them');
check(`(()=>{const x=gearFixture('held',61),s={id:'structure',master:x.u,structure:true,spec:{radius:10},pulseIndex:2};equipmentEvent(x,'entityLanded',s,x.foe,{damage:10},{entityPulse:1});equipmentEvent(x,'entityLanded',s,x.tr,{damage:10},{entityPulse:2});return x.f.value(x.foe,'hit')===-15&&x.f.value(x.tr,'hit')===0;})()`,'Area riders use the pulse that launched a deferred hit');
check(`(()=>{const x=gearFixture('held',92),H=BondEquipmentEffects.H;x.f.put(x.tr,x.u,'Blessing','healReceived',.2,5);x.f.put(x.foe,x.u,'Wound','healReceived',-.3,5);H.charge(x.f,x.u.gear.items[0].state,'q',3);const result=BondEquipmentEffects.change(x.f,'healAmount',90,x.tr,x.u,{active:true,itemBaseHeal:100});return Math.abs(result-115)<1e-8;})()`,'Healing penalty relief preserves a simultaneous positive healing bonus');
console.log('PASS '+checks+' complete equipment contracts');
