"""Disposable settings/audio, Inner Sea ownership/export and narrow UI regressions."""
import argparse,functools,hashlib,json,threading,traceback
from http.server import ThreadingHTTPServer
from browser_check import ROOT,ARTIFACTS,QuietServer,find_browser,sync_playwright,legacy_adventure

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--browser',default='chrome',choices=['chrome','edge']);args=parser.parse_args()
    server=ThreadingHTTPServer(('127.0.0.1',0),functools.partial(QuietServer,directory=str(ROOT)))
    threading.Thread(target=server.serve_forever,daemon=True).start()
    checks=[];errors=[];missing=[]
    hashes=lambda:{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted([*ROOT.glob('*.js'),*ROOT.glob('*.css'),ROOT/'index.html'])}
    source=hashes()
    def check(name,value):
        checks.append({'name':name,'pass':bool(value)});print(('PASS ' if value else 'FAIL ')+name,flush=True)
    try:
        with sync_playwright() as pw:
            browser=pw.chromium.launch(executable_path=find_browser(args.browser),headless=True)
            context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
            page=context.new_page();legacy_adventure(page)
            page.on('pageerror',lambda e:errors.append(str(e)))
            page.on('response',lambda r:missing.append(r.url) if r.status>=400 else None)
            page.goto(f'http://127.0.0.1:{server.server_port}/?test=1');page.wait_for_function('!!window.BondApp')
            check('Audio remains locked/muted on first load',page.evaluate('BondAudio.inspect().state==="uninitialized"&&BondSettings.snapshot().muted'))
            check('25 original cue definitions, three lazy loops',page.evaluate('Object.keys(BondAudio.cues).length===25&&Object.keys(BondAudio.loops).length===3&&!performance.getEntriesByType("resource").some(x=>x.name.includes("assets/audio"))'))
            page.locator('#open-settings').click();page.locator('[data-setting="muted"]').uncheck()
            page.wait_for_function('BondAudio.inspect().state==="running"&&BondAudio.inspect().loops===1')
            check('User gesture unlocks one exploration loop',page.evaluate('BondAudio.inspect().scene==="explore"'))
            page.locator('[data-setting="music"]').fill('23');page.locator('[data-setting="effects"]').fill('41')
            page.locator('[data-setting="quiet"]').check();page.locator('[data-setting="reduced"]').check();page.locator('[data-setting="shake"]').uncheck();page.locator('[data-setting="flashes"]').uncheck()
            check('Visual options update the combat and document presentation',page.evaluate('CombatView.inspect().quietFX&&BondSettings.reduced()&&document.documentElement.classList.contains("no-flashes")'))
            page.locator('#settings-close').click();check('Settings restores keyboard focus',page.locator('#open-settings').evaluate('(e)=>document.activeElement===e'))
            page.reload();page.wait_for_function('!!window.BondApp')
            check('Device settings survive reload with sandbox isolation',page.evaluate('BondSettings.snapshot().music===23&&BondSettings.snapshot().effects===41&&!BondSettings.snapshot().shake&&!localStorage.getItem("bond-bolt-settings-v1")'))
            page.locator('#open-settings').click();page.locator('[data-setting="muted"]').check();page.wait_for_function('BondAudio.inspect().state==="suspended"')
            check('Mute removes all active sources',page.evaluate('BondAudio.inspect().loops===0&&BondAudio.inspect().voices===0'))
            page.locator('[data-setting="muted"]').uncheck();page.locator('#settings-close').click()
            page.evaluate('BondApp.switchTab("loadout")');page.locator('#fight').click()
            page.wait_for_function('BondAudio.inspect().state==="running"&&BondAudio.inspect().scene==="combat"')
            check('Combat selects its own music without duplicate beds',page.evaluate('BondAudio.inspect().loops<=2'))
            page.locator('#pause').click();page.wait_for_function('BondAudio.inspect().state==="suspended"')
            check('Explicit pause removes loops and transient sources',page.evaluate('!BondAudio.inspect().loops&&!BondAudio.inspect().voices'))
            page.evaluate('BondApp.switchTab("loadout");BondMenu.open("collection")');page.wait_for_function('BondAudio.inspect().scene==="innersea"')
            check('Inner Sea resumes one selected scene',page.evaluate('BondAudio.inspect().desired==="innersea"'))
            page.evaluate('Object.defineProperty(document,"hidden",{configurable:true,get:()=>true});document.dispatchEvent(new Event("visibilitychange"))')
            page.wait_for_function('BondAudio.inspect().state==="suspended"')
            check('Hidden-page policy clears all audio sources',page.evaluate('!BondAudio.inspect().loops&&!BondAudio.inspect().voices'))
            page.evaluate('delete document.hidden;document.dispatchEvent(new Event("visibilitychange"));BondSettings.set({muted:true})')
            page.locator('#open-settings').click()
            with page.expect_download() as dl:page.locator('#settings-export').click()
            save=json.loads(dl.value.path().read_text(encoding='utf-8'))
            check('Explicit download exports the current local profile',save['version']==7 and save['companions']==[])
            page.locator('#settings-close').click()
            page.evaluate('BondApp.switchTab("loadout");BondMenu.open("collection")')
            page.wait_for_function('document.querySelector("#haven-scene").dataset.ready==="true"')
            check('Empty-owned scene renders a trainer without inventing companions',page.evaluate('BondProfile.snapshot().companions.length===0&&BondProfile.snapshot().haven.companions.every(x=>x===null)'))
            check('Locked decorations and foreign individuals cannot be saved',page.evaluate('!BondProfile.setHaven({version:1,style:"dawn",slots:["lantern",null,null],companions:[null,null]})&&!BondProfile.setHaven({version:1,style:"dawn",slots:[null,null,null],companions:["foreign",null]})'))
            page.evaluate('''()=>{let s=BondProfile.snapshot();s.tutorial.kills=1;s.sights=BondAtlas.maps.flatMap(m=>m.landmarks).slice(0,3).map(l=>l.id);BondProfile.testing.replace(s);for(let i=0;i<2;i++){const e=BondProfile.testing.grantEcho('emberfox',5);BondProfile.summon('emberfox','druid',e);}BondApp.switchTab('loadout');BondMenu.open('collection');}''')
            page.locator('[data-haven-edit]').click()
            check('Exactly three sockets and all three earned decorations',page.locator('[data-haven-slot]').count()==3 and page.evaluate('BondHaven.available(BondProfile.snapshot()).length===3'))
            page.locator('#haven-style').select_option('dusk')
            for i,name in enumerate(['cairn','lantern','bloom']):page.locator(f'[data-haven-slot="{i}"]').select_option(name)
            # Exercise the same draft selector callback through the actual portrait picker.
            page.locator('[data-haven-companion="0"]').click()
            selector=page.evaluate('BondProfile.companions()[0].id')
            # Picker buttons use data-pick-ref; keep the contract visible in failures.
            page.locator(f'[data-pick="{selector}"]').click()
            page.locator('[data-haven-companion="1"]').click()
            selector=page.evaluate('BondProfile.companions()[1].id');page.locator(f'[data-pick="{selector}"]').click()
            page.locator('[data-haven-save]').click()
            check('Independent same-species companions and three decorations save',page.evaluate('BondProfile.snapshot().haven.style==="dusk"&&BondProfile.snapshot().haven.companions.every(Boolean)&&new Set(BondProfile.snapshot().haven.companions).size===2&&BondProfile.snapshot().haven.slots.filter(Boolean).length===3'))
            chosen=page.evaluate('BondProfile.snapshot().haven')
            page.locator('[data-haven-edit]').click();page.locator('#haven-style').select_option('dawn');page.locator('[data-haven-slot="0"]').select_option('');page.locator('[data-haven-cancel]').click()
            check('Cancel discards the entire preview',page.evaluate('BondProfile.snapshot().haven')==chosen)
            invariant=page.evaluate('''()=>{const build=BondGame.defaultBuild(),s=BondProfile.snapshot();const snap=p=>{const b=new BondGame.Battle(build,{seed:891,profile:{...p,companions:undefined,owned:BondGame.MONSTERS}}).run();return JSON.stringify({tick:b.tick,units:b.units,events:b.events,winner:b.winner});};const a=snap(s);s.haven=BondHaven.fresh();return a===snap(s);}''')
            check('Decorations have no effect on canonical combat',invariant)
            page.wait_for_function('document.querySelector("#haven-scene").dataset.ready==="true"')
            page.locator('#haven-scene').screenshot(path=str(ARTIFACTS/f'inner-sea-{args.browser}.png'))
            with page.expect_download() as dl:page.locator('[data-haven-export]').click()
            data=dl.value.path().read_bytes();check('Scene exports a real local PNG',data.startswith(b'\x89PNG\r\n\x1a\n') and len(data)>10000)
            page.reload();page.wait_for_function('!!window.BondApp');page.evaluate('BondApp.switchTab("loadout");BondMenu.open("collection")')
            check('Saved scene survives reload',page.evaluate('BondProfile.snapshot().haven')==chosen)
            before=page.evaluate('BondProfile.export()')
            page.evaluate('''()=>{window.qaWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('quota');};const s=BondProfile.snapshot().haven;s.style='dawn';window.qaRejected=!BondProfile.setHaven(s);Storage.prototype.setItem=qaWrite;}''')
            check('Failed critical scene write leaves progress untouched',page.evaluate('qaRejected') and page.evaluate('BondProfile.export()')==before)
            for width in [320,390,768,1440]:
                page.set_viewport_size({'width':width,'height':1000})
                check(f'{width}px Inner Sea page has no overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
                page.locator('#open-settings').click()
                check(f'{width}px settings has no page overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
                page.keyboard.press('Escape');page.locator('[data-haven-edit]').click()
                check(f'{width}px scene editor controls fit',page.locator('#haven-dialog').evaluate('(d)=>d.scrollWidth<=d.clientWidth+1'))
                page.keyboard.press('Escape')
            page.set_viewport_size({'width':390,'height':1000});page.locator('[data-haven-edit]').click();page.screenshot(path=str(ARTIFACTS/f'inner-sea-phone-{args.browser}.png'));page.keyboard.press('Escape')
            check('No normal progress or settings keys touched',page.evaluate('!localStorage.getItem("bond-bolt-profile-v7")&&!localStorage.getItem("bond-bolt-build-v4")&&!localStorage.getItem("bond-bolt-settings-v1")'))
            browser.close()
    except Exception:errors.append(traceback.format_exc())
    finally:server.shutdown();server.server_close()
    check('No browser/test errors',not errors);check('No missing assets',not missing);check('Runtime unchanged during tests',source==hashes())
    report={'checks':checks,'errors':errors,'missing':missing,'source_sha256':source}
    (ARTIFACTS/f'experience-{args.browser}.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
    print(json.dumps({'passed':sum(x['pass'] for x in checks),'total':len(checks),'failures':[x for x in checks if not x['pass']],'errors':errors},indent=2))
    return 0 if checks and all(x['pass'] for x in checks) else 1
if __name__=='__main__':raise SystemExit(main())
