"""Four classes and farm progression in a disposable browser profile."""
import argparse, functools, hashlib, json, threading, traceback
from datetime import datetime, timedelta, timezone
from http.server import ThreadingHTTPServer
from browser_check import ROOT, ARTIFACTS, QuietServer, find_browser, sync_playwright

parser=argparse.ArgumentParser()
parser.add_argument('--browser', default='chrome', choices=['chrome','edge'])
args=parser.parse_args()
server=ThreadingHTTPServer(('127.0.0.1',0),functools.partial(QuietServer,directory=str(ROOT)))
threading.Thread(target=server.serve_forever,daemon=True).start()
checks=[];errors=[];missing=[]
hashes=lambda:{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted([*ROOT.glob('*.js'),*ROOT.glob('*.css'),ROOT/'index.html'])}
source=hashes()
def check(name,value): checks.append({'name':name,'pass':bool(value)})
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=find_browser(args.browser),headless=True)
    page=browser.new_page(viewport={'width':1440,'height':1100})
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('response',lambda r:missing.append(r.url) if r.status>=400 else None)
    now=datetime.now(timezone.utc);page.clock.install(time=now);page.clock.pause_at(now+timedelta(seconds=2))
    try:
        page.goto(f'http://127.0.0.1:{server.server_port}/?test=1')
        page.wait_for_function('!!window.BondApp')
        checks.extend(page.evaluate((ROOT/'tests/farm_classes_cases.js').read_text(encoding='utf-8')))
        page.reload();page.wait_for_function('!!window.BondApp')
        page.evaluate("BondApp.switchTab('loadout');BondMenu.open('collection')")
        page.wait_for_function('document.querySelector("#haven-scene").dataset.ready==="true"')
        check('Farm shows five habitats and five separate defense slots',page.locator('.farm-habitats article').count()==5 and page.locator('[data-farm-defender]').count()==5)
        page.locator('[data-farm-defender="0"]').click()
        page.locator('[data-pick="farm:0"]').click()
        check('Actual portrait picker assigns an owned defender',page.evaluate('BondProfile.snapshot().farm.defenders[0]==="farm:0"'))
        page.locator('[data-farm-action="buy"][data-farm-value="timber"]').click()
        page.locator('[data-farm-action="buy"][data-farm-value="timber"]').click()
        page.locator('[data-farm-action="upgrade"][data-farm-value="barn"]').click()
        check('UI upgrades only the chosen habitat',page.evaluate('BondProfile.snapshot().farm.levels.barn===2&&BondProfile.snapshot().farm.levels.pond===1'))
        page.locator('[data-farm-action="clean"]').click()
        page.locator('.haven-display').screenshot(path=str(ARTIFACTS/f'farm-desktop-{args.browser}.png'))
        saved=page.evaluate('BondProfile.snapshot().farm')
        page.reload();page.wait_for_function('!!window.BondApp')
        check('Farm ownership, defenders and upgrades survive reload',page.evaluate('BondProfile.snapshot().farm.defenders')==saved['defenders'] and page.evaluate('BondProfile.snapshot().farm.levels')==saved['levels'])
        page.evaluate("""()=>{const s=BondProfile.snapshot();BondFarm.attack(s,Date.now());BondProfile.testing.replace(s);BondApp.switchTab('loadout');BondMenu.open('collection');}""")
        before=page.evaluate('BondProfile.snapshot().farm.lastDefense')
        items=page.evaluate('JSON.stringify([BondProfile.snapshot().coins,BondProfile.snapshot().inventory,BondProfile.snapshot().companions])')
        page.locator('[data-farm-replay]').click()
        check('Defense replay contains only monsters',page.locator('#farm-replay .farm-replay-sides article').count()==len(before['actors']) and page.evaluate('BondProfile.snapshot().farm.lastDefense.actors.every(a=>BondContent.UNITS[a.type].role!=="Trainer")'))
        page.locator('[data-replay-play]').click();page.clock.run_for(1200)
        check('Replay playback advances',float(page.locator('[data-replay-range]').input_value())>0)
        page.locator('[data-replay-close]').click()
        check('Watching a defense never grants loot or removes XP again',page.evaluate('JSON.stringify([BondProfile.snapshot().coins,BondProfile.snapshot().inventory,BondProfile.snapshot().companions])')==items)
        for width in [320,390,768,1440]:
            page.set_viewport_size({'width':width,'height':1100})
            check(f'{width}px farm fits the screen',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        page.set_viewport_size({'width':390,'height':1100})
        page.locator('.haven-display').screenshot(path=str(ARTIFACTS/f'farm-phone-{args.browser}.png'))
        page.set_viewport_size({'width':1440,'height':1100})
        page.evaluate("""()=>{const P=BondProfile,s=P.snapshot();s.progression.specialization=null;s.trainerXP=BondProgress.threshold(19);s.journey.early.demonstrations=Object.values(BondCampaign.DEMONSTRATIONS);s.journey.early.tidecrown=true;s.journey.early.mageGate=true;s.journey.early.trials.hunter=false;P.testing.replace(s);BondApp.changeUnit(0,1,'farm:0');BondApp.changeUnit(0,2,'farm:1');const e=P.encounter('early:master:hunter');P.travel(e.map,e);BondApp.switchTab('region');}""")
        page.clock.run_for(300);page.locator('[data-object="early:master:hunter"]').click();page.clock.run_for(300)
        check('Hunter master gives the explicit easy acceptance challenge',"Defeat me in battle and I'll accept you as a Hunter" in page.locator('#npc-dialogue').inner_text() and not page.locator('#trial-skill-controls').is_visible())
        check('Hunter master field and dialogue use the painted class portrait',page.locator('[data-object="early:master:hunter"] [data-painted-portrait]').count()==1 and page.locator('#npc-portrait [data-character="hunter"] image').count()==1)
        page.locator('#npc-dialog').screenshot(path=str(ARTIFACTS/f'hunter-master-{args.browser}.png'))
        page.keyboard.press('Escape')
        page.evaluate("()=>{const s=BondProfile.snapshot();s.journey.early.trials.mage=true;s.journey.early.trialRewarded=true;BondProfile.testing.replace(s);}")
        page.locator('[data-object="early:master:hunter"]').click();page.clock.run_for(300)
        check('A second master does not promise the shared trainer XP again',' 0 trainer XP' in page.locator('#npc-reward').inner_text())
        page.locator('#npc-fight').click();page.clock.run_for(200)
        check('Master battle keeps the real Apprentice build',page.evaluate('BondApp.battle().units.find(u=>u.side===0&&u.slot===0).type==="apprentice"') if page.evaluate('typeof BondApp.battle==="function"') else page.evaluate('BondProfile.snapshot().encounterSave.build[0][0].type==="apprentice"'))
        check('Class master battle keeps class art',page.evaluate('BondApp.getBattle().trainer(1).appearance==="hunter"'))
        page.evaluate("""()=>{BondApp.cancelRegionBattle();const P=BondProfile,s=P.snapshot();s.journey.early.introFightWon=true;s.journey.early.mageGate=true;s.vitality={};P.testing.replace(s);const e=P.encounter('story:clearing:0');P.travel(e.map,e);BondApp.switchTab('region');}""")
        page.clock.run_for(300)
        check('Regular world NPC uses civilian art',page.locator('[data-object="story:clearing:0"] .civilian-sprite').count()==1)
        page.locator('[data-object="story:clearing:0"]').click();page.clock.run_for(300)
        check('Regular NPC dialogue and team preview use civilians',page.locator('#npc-portrait .civilian-sprite').count()==1 and page.locator('#npc-team .civilian-sprite').count()==1)
        page.locator('#npc-dialog').screenshot(path=str(ARTIFACTS/f'civilian-npc-{args.browser}.png'))
        page.locator('#npc-fight').click();page.clock.run_for(200)
        check('Regular NPC battle uses the same civilian appearance',page.evaluate("BondApp.getBattle().trainer(1).appearance===CharacterRig.npcAppearance(BondProfile.encounter('story:clearing:0'))"))
        page.evaluate('BondApp.cancelRegionBattle()')
        for class_type in ('hunter','swordsman'):
            check(f'{class_type} renders and exports the Inner Sea portrait',page.evaluate("""async type=>{const s=BondProfile.snapshot();s.progression.specialization=type;s.trainerXP=BondProgress.threshold(25);BondProfile.testing.replace(s);const canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;const profile=BondProfile.snapshot();const ok=await BondInnerSea.draw(canvas,profile.haven,profile);return ok&&canvas.dataset.ready==='true'&&canvas.toDataURL('image/png').length>10000;}""",class_type))
    except Exception: errors.append(traceback.format_exc())
    check('No browser or test errors',not errors);check('No missing assets',not missing);check('Source stayed unchanged during verification',source==hashes())
    browser.close()
server.shutdown()
report={'checks':checks,'errors':errors,'missing':missing,'source_sha256':source}
(ARTIFACTS/f'farm-classes-{args.browser}.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print(json.dumps({'passed':sum(c['pass'] for c in checks),'total':len(checks),'failures':[c for c in checks if not c['pass']],'errors':errors},indent=2),flush=True)
raise SystemExit(0 if checks and all(c['pass'] for c in checks) else 1)
