/* Independent outcomes and persistence boundaries for classes and Inner Sea. */
(()=>{
 const P=BondProfile,F=BondFarm,R=BondProgress,G=BondGame,C=BondContent,out=[];
 const check=(name,fn)=>{try{out.push({name,pass:!!fn()});}catch(e){out.push({name,pass:false,error:e.message});}};
 const at=Date.UTC(2026,8,11,3,27),clone=s=>JSON.parse(JSON.stringify(s));
 function fixture(level=25){const s=P.fresh();s.character={name:'Farm Tester',weapon:'dagger',look:BondOpening.defaultLook};s.trainerXP=R.threshold(level);s.coins=1000;
 s.companions=['emberfox','stonehorn','bloomslime','stormowl','lumimoth','emberfox'].map((type,i)=>({id:'farm:'+i,type,ordinal:i===5?2:1,xp:R.threshold(25),growth:{},skills:[...C.UNITS[type].default],pact:{map:'clearing-0',trainerClass:'apprentice'}}));return s;}
 check('All four classes have distinct five-skill kits and valid three-skill builds',()=>C.CLASSES.length===4&&C.CLASSES.every(type=>C.UNITS[type].skills.length===5&&G.validBuild(G.soloBuild(type)))&&C.UNITS.hunter.basicCategory==='ranged'&&C.UNITS.swordsman.basicCategory==='melee'&&!BondRules.validate().length);
 check('Four demonstrations show four different classes',()=>new Set(Object.keys(BondCampaign.DEMONSTRATIONS).map(id=>P.encounter(id).team[0].type)).size===4);
 check('All four masters fight as the class they offer',()=>C.CLASSES.every(type=>{const e=P.encounter('early:master:'+type);return e.team[0].type===type&&e.greeting.includes("Defeat me in battle")&&e.greeting.includes(C.UNITS[type].name)&&e.protectedEncounter;}));
 check('Only class masters use class appearances among human NPCs',()=>Object.entries(BondWorld.NPCS).filter(([,e])=>!e.kind).every(([id,e])=>{const appearance=CharacterRig.npcAppearance(e,id);return e.masterClass?appearance===e.masterClass:appearance.startsWith('npc-');}));
 check('Civilian appearance is stable and keeps monster identities intact',()=>CharacterRig.npcAppearance({kind:'guide'})==='npc-keeper'&&CharacterRig.npcAppearance(P.encounter('early:forest-mage'))==='npc-keeper'&&CharacterRig.npcAppearance({kind:'boss',type:'elderroot'})==='elderroot'&&CharacterRig.npcAppearance({id:'example',appearance:'mage'})===CharacterRig.npcAppearance({id:'example',appearance:'druid'}));
 for(const type of C.CLASSES)check(type+' accepts the current Apprentice party and grants XP only once',()=>{let s=fixture(15);s.journey.early.demonstrations=Object.values(BondCampaign.DEMONSTRATIONS);s.journey.early.tidecrown=true;s.journey.early.mageGate=true;P.testing.replace(s);const e=P.encounter('early:master:'+type);P.travel(e.map);s=P.snapshot();const build=[[BondOpening.build(s.character),...s.companions.slice(0,2).map(m=>({type:m.type,instanceId:m.id,skills:m.skills}))],e.team],options={profile:s,enemyLevel:e.level,seed:e.seed},b=new G.Battle(build,options);if(!P.reserveBattle(b,e.id,options))return false;b.run();if(b.winner!==0)return false;const receipt=P.complete(b,e.id),xp=P.snapshot().trainerXP;P.complete(b,e.id);return receipt.trainerXP===8500&&P.snapshot().trainerXP===xp&&P.specialize(type)?.type===type&&P.normalize(P.snapshot()).progression.specialization===type&&P.migrateParty(build[0])[0].type===type&&!P.specialize(C.CLASSES.find(t=>t!==type));});
 check('Different masters share one trainer XP reward before class confirmation',()=>{const s=fixture(15);s.journey.early.demonstrations=Object.values(BondCampaign.DEMONSTRATIONS);s.journey.early.tidecrown=true;s.journey.early.mageGate=true;P.testing.replace(s);const earned=[];for(const type of C.CLASSES){const e=P.encounter('early:master:'+type);P.travel(e.map);const p=P.snapshot(),build=[[BondOpening.build(p.character),...p.companions.slice(0,2).map(m=>({type:m.type,instanceId:m.id,skills:m.skills}))],e.team],options={profile:p,enemyLevel:e.level,seed:e.seed},b=new G.Battle(build,options);if(!P.reserveBattle(b,e.id,options))return false;b.run();if(b.winner!==0)return false;earned.push(P.complete(b,e.id).trainerXP);}return earned.join(',')==='8500,0,0,0'&&P.snapshot().trainerXP===s.trainerXP+8500&&!P.snapshot().progression.specialization;});
 check('Legacy demonstration receipts migrate without forcing repeats',()=>{const s=fixture();s.journey.early.demonstrations=['druid-sustain','mage-control','druid-area','mage-bypass'];return P.normalize(s).journey.early.demonstrations.length===4;});
 check('Ownership requires Lv25 and establishes once',()=>{const s=fixture(24);if(F.command(s,'establish',null,at))return false;s.trainerXP=R.threshold(25);return F.command(s,'establish',null,at)&&s.inventory.repairkit===2&&!F.command(s,'establish',null,at);});
 check('Malformed farm report and defender fields do not erase the collection',()=>{const s=fixture();s.farm={version:1,owned:true,defenders:['foreign'],lastDefense:{at,actors:[{id:'bad',type:'mage'}]},levels:{barn:-8}};const n=P.normalize(s);return n.companions.length===6&&n.farm.lastDefense===null&&n.farm.levels.barn===1&&n.farm.defenders.every(x=>x===null);});
 check('Power counts each species once and first tied individual wins',()=>{const s=fixture();s.companions[5].xp=R.threshold(30);if(F.power(s)!==130||F.strongest(s).emberfox.id!=='farm:5')return false;s.companions[0].xp=R.threshold(30);return F.power(s)===130&&F.strongest(s).emberfox.id==='farm:0';});
 check('Habitats choose one highest-level resident and stable ties',()=>{const s=fixture();s.companions[5].xp=R.threshold(30);const h=F.habitat('emberfox');if(F.residents(s)[h].id!=='farm:5')return false;s.companions[0].xp=R.threshold(30);return F.residents(s)[h].id==='farm:0'&&F.habitat('stormowl')==='aviary'&&F.habitat('lumimoth')==='garden';});
 check('NASA new and full moon instants produce weak and strong attacks',()=>{const a=F.moon(at),b=F.moon(Date.UTC(2026,8,26,16,49));return a.name==='New moon'&&a.count===3&&a.illumination<.00001&&b.name==='Full moon'&&b.count===5&&b.illumination>.99999;});
 check('Haunted cellar uses current ghost and fiend families before old animal shapes',()=>F.habitats.cellar.name==='Haunted cellar'&&['emberfox','stonehorn','ashporcupine','rillrook','volcanomoth','kitejelly'].every(t=>F.habitat(t)==='cellar')&&F.habitat('coalbadger')==='barn'&&F.habitat('mudmole')==='barn');
 check('Haunted cellar retains saved upgrades and selects only compatible residents',()=>{const s=fixture();F.command(s,'establish',null,at);s.farm.levels.cellar=4;const saved=P.normalize(s);return saved.farm.levels.cellar===4&&F.residents(saved).cellar.id==='farm:0'&&F.habitat(F.residents(saved).cellar.type)==='cellar';});
 check('Training covers bag duplicates without trainer XP or repeated elapsed time',()=>{const s=fixture();F.command(s,'establish',null,at);const xp=s.trainerXP,old=s.companions.map(m=>m.xp);F.advance(s,at+60*F.MINUTE);const after=JSON.stringify(s);F.advance(s,at+60*F.MINUTE);return s.trainerXP===xp&&s.companions.every((m,i)=>m.xp===old[i]+60)&&JSON.stringify(s)===after;});
 check('Fractional elapsed time survives settlement and clock rollback earns nothing',()=>{const s=fixture();F.command(s,'establish',null,at);const xp=s.companions[0].xp;F.advance(s,at+30000);F.advance(s,at+15000);F.advance(s,at+60000);return s.companions[0].xp===xp+1;});
 check('Dirty and damaged farms stop training, repair consumes an item',()=>{const s=fixture();F.command(s,'establish',null,at);s.farm.cleanUntil=at+60000;s.farm.nextAttack=at+10*F.DAY;const xp=s.companions[0].xp;F.advance(s,at+3*F.MINUTE);if(s.companions[0].xp!==xp+1)return false;s.farm.damaged=true;F.advance(s,at+4*F.MINUTE);return F.bonuses(s).hp===0&&F.bonuses(s).defense===0&&s.companions[0].xp===xp+1&&F.command(s,'repair',null,at+4*F.MINUTE)&&s.inventory.repairkit===1&&F.bonuses(s).hp>0;});
 check('Each habitat upgrades independently and validates timber costs',()=>{const s=fixture();F.command(s,'establish',null,at);s.inventory.timber=2;if(!F.command(s,'upgrade','barn',at))return false;return s.inventory.timber===0&&s.farm.levels.barn===2&&s.farm.levels.pond===1&&!F.command(s,'upgrade','pond',at)&&!F.command(s,'upgrade','fake',at);});
 check('Defenders are five owned unique individuals and may include duplicate species',()=>{const s=fixture();F.command(s,'establish',null,at);return F.command(s,'defenders',['farm:0','farm:5',null,null,null],at)&&!F.command(s,'defenders',['farm:0','farm:0',null,null,null],at)&&!F.command(s,'defenders',['foreign',null,null,null,null],at);});
 check('Defense has five monsters, no trainer, and is deterministic',()=>{const s=fixture();F.command(s,'establish',null,at);s.farm.defenders=s.companions.slice(0,5).map(m=>m.id);const a=F.attack(clone(s),at),b=F.attack(clone(s),at);return a.actors.filter(u=>u.side===0).length===5&&a.actors.every(u=>C.UNITS[u.type].role!=='Trainer')&&JSON.stringify(a)===JSON.stringify(b);});
 check('Guard protects an allied defender without a trainer',()=>{const s=fixture();F.command(s,'establish',null,at);const ds=s.companions.slice(0,2).map(m=>({type:m.type,instanceId:m.id,skills:m.skills})),b=new G.Battle(G.soloBuild(),{profile:s,defenders:ds,encounter:{kind:'pack',enemies:[{type:'emberfox',skills:C.UNITS.emberfox.default}]} }),guard=b.units.find(u=>u.type==='stonehorn'&&u.side===0),target=b.units.find(u=>u.instanceId==='farm:0');b.effect(guard,guard,'guard',10);b.damage(b.team(1)[0],target,100,'fixture');return b.events.some(e=>e.kind==='guard')&&!b.trainer(0)&&!b.requestEscape();});
 check('Failed defense removes XP from every owned copy and suspends farm bonuses',()=>{const s=fixture(60);F.command(s,'establish',null,at);s.farm.defenders=['farm:0',null,null,null,null];s.companions[0].xp=100;const old=s.companions.map(m=>m.xp),trainer=s.trainerXP,r=F.attack(s,at);return !r.won&&r.level===60&&s.companions.every((m,i)=>m.xp<old[i])&&Object.keys(r.xpLost).length===6&&s.trainerXP===trainer&&s.farm.damaged&&F.bonuses(s).hp===0;});
 check('XP loss preserves already-earned tree budget through reload',()=>{const s=fixture(60);F.command(s,'establish',null,at);const m=s.companions[0],budget=BondGrowth.budget(s,m.id);s.farm.defenders=[m.id,null,null,null,null];F.attack(s,at);return s.farm.damaged&&BondGrowth.budget(s,m.id)===budget&&BondGrowth.budget(P.normalize(s),m.id)===budget;});
 check('Victory pays attacker loot once across reload and repeated settlement',()=>{const s=fixture();F.command(s,'establish',null,at);s.trainerXP=0;s.companions.forEach(m=>m.xp=R.threshold(60));s.farm.defenders=s.companions.slice(0,5).map(m=>m.id);s.farm.nextAttack=at+F.MINUTE;F.advance(s,at+F.MINUTE);if(!s.farm.lastDefense.won||s.farm.lastDefense.loot.coins<=0)return false;const saved=P.normalize(s),before=JSON.stringify(saved);F.advance(saved,at+F.MINUTE);return JSON.stringify(saved)===before&&saved.farm.lastDefense.actors.length===8;});
 check('Unattended attacks remain queued and never pay more than once',()=>{const s=fixture();F.command(s,'establish',null,at);s.trainerXP=0;s.companions.forEach(m=>m.xp=R.threshold(60));s.farm.defenders=s.companions.slice(0,5).map(m=>m.id);const end=at+12*F.DAY;F.advance(s,end);if(s.farm.nextAttack>end)return false;F.advance(s,end);const coins=s.coins;F.advance(s,end);return s.farm.nextAttack>end&&coins===s.coins;});
 check('Account HP bonus affects own fighters once, never enemies or decorative changes',()=>{const s=fixture();F.command(s,'establish',null,at);const base=R.derived('hunter',s),enemy=R.derived('hunter',s,C.UNITS.hunter,25);s.farm.damaged=true;const damaged=R.derived('hunter',s);return base.hp>damaged.hp&&enemy.hp===R.derived('hunter',s,C.UNITS.hunter,25).hp;});
 check('Failed farm save preserves items, upgrades and XP',()=>{P.testing.replace(fixture());P.farmAction('establish');let s=P.snapshot();s.inventory.timber=2;P.testing.replace(s);const old=P.export(),write=Storage.prototype.setItem;try{Storage.prototype.setItem=function(){throw Error('quota');};return !P.farmAction('upgrade','barn')&&P.export()===old;}finally{Storage.prototype.setItem=write;}});
 return out;
})();
