"""Actual in-frame Bag/Inner Sea navigation in disposable desktop and phone saves."""
import argparse, functools, hashlib, json, threading, traceback
from datetime import datetime, timedelta, timezone
from http.server import ThreadingHTTPServer
from browser_check import ROOT, ARTIFACTS, QuietServer, find_browser, sync_playwright

parser = argparse.ArgumentParser()
parser.add_argument('--browser', default='chrome', choices=['chrome', 'edge'])
args = parser.parse_args()
server = ThreadingHTTPServer(('127.0.0.1', 0), functools.partial(QuietServer, directory=str(ROOT)))
threading.Thread(target=server.serve_forever, daemon=True).start()
checks, errors, missing = [], [], []
hashes = lambda: {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in [*ROOT.glob('*.js'), *ROOT.glob('*.css'), ROOT/'index.html', ROOT/'assets/inner-sea/homestead.png']}
source = hashes()
def check(name, value):
    checks.append({'name': name, 'pass': bool(value)})
def contained(page, selector, parent='#game-frame'):
    return page.evaluate('''([selector,parent])=>{const a=document.querySelector(selector).getBoundingClientRect(),b=document.querySelector(parent).getBoundingClientRect();return a.width>0&&a.height>0&&a.left>=b.left-1&&a.right<=b.right+1&&a.top>=b.top-1&&a.bottom<=b.bottom+1;}''', [selector, parent])

try:
    with sync_playwright() as pw:
        browser = pw.chromium.launch(executable_path=find_browser(args.browser), headless=True)
        page = browser.new_page(viewport={'width': 1440, 'height': 1000})
        page.on('pageerror', lambda e: errors.append(str(e)))
        page.on('response', lambda r: missing.append(r.url) if r.status >= 400 else None)
        now = datetime.now(timezone.utc)
        page.clock.install(time=now)
        page.clock.pause_at(now+timedelta(seconds=2))
        page.goto(f'http://127.0.0.1:{server.server_port}/?test=1')
        page.wait_for_function('!!window.BondApp')
        page.locator('#character-name').fill('Skye')
        page.locator('#create-character').click()
        page.locator('[data-world-menu="collection"]').click()
        page.wait_for_function('document.querySelector("#haven-scene").dataset.ready==="true"')
        check('Locked farm is an in-frame preview with establishment still gated', contained(page, '#panel-loadout') and page.locator('[data-farm-action="establish"]').is_disabled())
        page.keyboard.press('Escape')
        check('Escape returns focus to the Inner Sea field button', page.evaluate('BondApp.getTab()==="region"&&document.activeElement.dataset.worldMenu==="collection"'))
        page.evaluate('''()=>{const P=BondProfile,s=P.snapshot();s.trainerXP=BondProgress.threshold(30);s.coins=400;s.journey.early.mageGate=true;s.journey.early.introFightWon=true;
        s.companions=['coalbadger','emberfox','stormowl','lumimoth','kitejelly'].map((type,i)=>({id:'frame:'+i,type,ordinal:1,xp:BondProgress.threshold(30),growth:{},skills:[...BondContent.UNITS[type].default]}));
        s.inventory.timber=6;s.inventory.biscuit=2;P.testing.replace(s);P.farmAction('establish');P.testing.grantEcho('emberfox',5);P.travel('clearing-hub',BondAtlas.get('clearing-hub').guide);BondApp.switchTab('region');}''')
        review_save = page.evaluate('BondProfile.snapshot()')
        field = page.locator('#region-map').bounding_box()
        field['y'] += page.evaluate('scrollY')
        position = page.evaluate('BondRegion.inspect().position')
        page.locator('[data-world-menu="inventory"]').click()
        bag = page.locator('#panel-loadout').bounding_box()
        bag['y'] += page.evaluate('scrollY')
        check('Bag occupies the exact exploration rectangle', bag == field)
        check('Inventory remains under the shared game frame', page.locator('#game-frame #panel-loadout .satchel-layout').count() == 1 and not page.locator('#region-map').is_visible())
        page.keyboard.down('d'); page.clock.run_for(600); page.keyboard.up('d')
        check('Menu keyboard input cannot move the hidden player', page.evaluate('BondRegion.inspect().position') == position)
        page.locator('[data-item="echo:emberfox"]').click()
        page.locator('#game-frame').screenshot(path=str(ARTIFACTS/f'frame-inventory-desktop-{args.browser}.png'))
        page.locator('[data-summon="emberfox"]').click()
        check('Summon confirmation stays within the game frame', contained(page, '#summon-dialog'))
        page.keyboard.press('Escape')
        check('Escape dismisses the confirmation without leaving Bag', page.evaluate('BondApp.getTab()==="loadout"&&BondMenu.current()==="inventory"&&!document.querySelector("#summon-dialog").open'))
        before = page.evaluate('BondProfile.companions().length')
        page.locator('[data-summon="emberfox"]').click(); page.locator('#confirm-summon').click()
        check('Summoning consumes its Echo once and shows the new individual in frame', page.evaluate('BondProfile.companions().length') == before+1 and page.evaluate('!BondProfile.snapshot().inventory["echo:emberfox"]') and page.locator('#game-frame [data-instance]').count() == before+1)
        page.locator('[data-collection-mode="farm"]').click()
        page.wait_for_function('document.querySelector("#haven-scene").dataset.ready==="true"')
        check('Homestead uses the painted image and five habitat buttons', page.evaluate('BondFarmView.background().then(img=>img.complete&&img.naturalWidth>1000)') and page.locator('[data-sea-habitat]').count() == 5)
        page.locator('[data-sea-habitat="cellar"]').click()
        check('Clicking a habitat focuses its management card', page.evaluate('document.activeElement.dataset.habitat==="cellar"'))
        page.locator('[data-farm-action="upgrade"][data-farm-value="cellar"]').click()
        check('Framed upgrade affects only its habitat', page.evaluate('BondProfile.snapshot().farm.levels.cellar===2&&BondProfile.snapshot().farm.levels.barn===1'))
        page.locator('[data-farm-defender="0"]').click()
        check('Defender picker stays within the game frame', contained(page, '#companion-picker'))
        page.locator('[data-pick="frame:0"]').click()
        check('Defender selection commits an owned individual', page.evaluate('BondProfile.snapshot().farm.defenders[0]==="frame:0"'))
        page.evaluate('document.querySelector("#farm-panel").scrollTop=0;document.querySelector(".menu-content").scrollTop=0')
        page.locator('#game-frame').screenshot(path=str(ARTIFACTS/f'frame-farm-desktop-{args.browser}.png'))
        page.locator('[data-haven-edit]').click()
        check('Scene editor stays within the frame', contained(page, '#haven-dialog'))
        page.locator('#haven-style').select_option('dusk'); page.locator('[data-haven-cancel]').click()
        check('Cancel keeps the saved scene unchanged and restores focus', page.evaluate('BondProfile.snapshot().haven.style==="dawn"&&document.activeElement.hasAttribute("data-haven-edit")'))
        for width in [320, 390, 768, 1440]:
            page.set_viewport_size({'width': width, 'height': 844})
            page.evaluate('document.querySelector(".menu-content").scrollTop=0')
            check(f'{width}px farm and navigation remain in frame without page overflow', contained(page, '#panel-loadout') and contained(page, '.frame-destinations') and page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
            page.locator('[data-frame-menu="inventory"]').click()
            if width <= 600 and page.locator('[data-bag-back]').is_visible(): page.locator('[data-bag-back]').click()
            page.locator('[data-bag-filter="All"]').click()
            page.locator('[data-item="biscuit"]').click()
            check(f'{width}px selected item actions are visible in frame', contained(page, '.satchel-detail'))
            if width <= 600:
                page.locator('[data-bag-back]').click()
                check(f'{width}px Back to items restores the selected slot', page.evaluate('document.activeElement.dataset.item==="biscuit"') and page.locator('.satchel-storage').is_visible())
            page.locator('[data-frame-menu="collection"]').click()
            page.wait_for_function('document.querySelector("#haven-scene").dataset.ready==="true"')
            if width == 390: page.locator('#game-frame').screenshot(path=str(ARTIFACTS/f'frame-farm-phone-{args.browser}.png'))
        page.locator('.frame-close').click()
        check('Close returns to the same field position', page.evaluate('BondRegion.inspect().position') == position)
        page.evaluate('''()=>{const P=BondProfile;P.travel('clearing-0',BondAtlas.get('clearing-0').guide);BondApp.switchTab('region');const target=P.population().find(p=>p.present&&p.type==='emberfox');BondApp.startRegionBattle(P.beginHunt(target.id).id);}''')
        page.locator('#edit-build').click(); page.locator('[data-menu="inventory"]').click()
        tick = page.evaluate('BondApp.getBattle().tick'); page.clock.run_for(600)
        check('Combat keeps advancing behind the framed menu', page.evaluate('BondApp.getBattle().tick') > tick)
        page.evaluate('BondApp.getBattle().run();BondApp.renderBattle();BondApp.finish()')
        check('Background battle settlement does not pull the player out of Bag', page.evaluate('BondApp.getTab()==="loadout"&&BondMenu.current()==="inventory"'))
        check('Normal browser save keys remain untouched', page.evaluate('!localStorage.getItem("bond-bolt-profile-v7")&&!localStorage.getItem("bond-bolt-build-v4")'))
        # A different disposable browser context verifies the ordinary play layout.
        normal = browser.new_page(viewport={'width': 1440, 'height': 1000})
        normal.add_init_script('localStorage.setItem("bond-bolt-profile-v7",'+json.dumps(json.dumps(review_save))+')')
        normal.on('pageerror', lambda e: errors.append(str(e)))
        normal.on('response', lambda r: missing.append(r.url) if r.status >= 400 else None)
        normal.goto(f'http://127.0.0.1:{server.server_port}/')
        normal.wait_for_function('!!window.BondApp')
        normal.locator('[data-world-menu="inventory"]').click()
        normal.locator('[data-item="echo:emberfox"]').click()
        check('Ordinary play also contains Bag without QA controls', contained(normal, '#panel-loadout') and normal.locator('.test-controls').count() == 0)
        normal.locator('#game-frame').screenshot(path=str(ARTIFACTS/f'frame-inventory-desktop-{args.browser}.png'))
        normal.locator('[data-frame-menu="collection"]').click()
        normal.wait_for_function('document.querySelector("#haven-scene").dataset.ready==="true"')
        check('Ordinary desktop frame fits the viewport', normal.evaluate('document.querySelector("#game-frame").getBoundingClientRect().bottom<=innerHeight'))
        normal.locator('#game-frame').screenshot(path=str(ARTIFACTS/f'frame-farm-desktop-{args.browser}.png'))
        normal.set_viewport_size({'width': 390, 'height': 844})
        check('Ordinary phone frame fits the viewport', normal.evaluate('document.querySelector("#game-frame").getBoundingClientRect().bottom<=innerHeight'))
        normal.locator('#game-frame').screenshot(path=str(ARTIFACTS/f'frame-farm-phone-{args.browser}.png'))
        normal.locator('[data-frame-menu="inventory"]').click()
        normal.locator('#game-frame').screenshot(path=str(ARTIFACTS/f'frame-inventory-phone-{args.browser}.png'))
        browser.close()
except Exception:
    errors.append(traceback.format_exc())
finally:
    server.shutdown(); server.server_close()
check('No browser errors or missing assets', not errors and not missing)
check('Source stayed unchanged during the checks', source == hashes())
(ARTIFACTS/f'game-frame-{args.browser}.json').write_text(json.dumps({'checks':checks,'errors':errors,'missing':missing,'source_sha256':source},indent=2),encoding='utf-8')
print(json.dumps({'passed':sum(c['pass'] for c in checks),'total':len(checks),'failures':[c for c in checks if not c['pass']],'errors':errors},indent=2))
raise SystemExit(0 if checks and all(c['pass'] for c in checks) else 1)
