()=>{
'use strict';
const P=BondProfile,O=BondOpening,G=BondGame,T=BondAdventure,A=BondAtlas,out=[],original=P.snapshot();
const check=(name,fn)=>{try{out.push({name:'Opening '+name,pass:!!fn()});}catch(e){out.push({name:'Opening '+name,pass:false,error:e.stack});}};
const reset=()=>P.testing.replace(P.fresh());
const create=weapon=>{reset();return P.createCharacter({name:'Rowan',weapon,look:{hair:'braid',face:'bright',hairColor:3,skinColor:4}});};
function fight(type='emberfox',weapon='dagger'){
 create(weapon);const sp=P.population().find(x=>x.present&&x.type===type),e=P.beginHunt(sp.id),build=G.soloBuild('apprentice');build[0][0]=O.build(P.snapshot().character);
 const options={profile:P.snapshot(),adventure:true,seed:e.seed,encounter:e},b=new G.Battle(build,options);
 if(!P.reserveBattle(b,e.id,options))throw Error('reservation failed');return {b,e,sp};
}
try{
 check('Names trim and normalize safely',()=>O.name('  Éli   Rowan  ')==='Éli Rowan'&&O.validName("Éli O'Rowan")&&O.validName('月光')&&!O.validName('<img src=x>')&&!O.validName('a')&&!O.validName('x'.repeat(21))&&!O.validName('ab\u202ecd'));
 check('Cosmetics use fixed palettes, not arbitrary CSS or markup',()=>{const x=O.look({hair:'<script>',face:'bad',skinColor:-3,hairColor:999}),m=BondApprenticePreview.markup({hairColor:'red;'},'<img>');return x.hair==='sweep'&&x.face==='calm'&&x.skinColor===1&&x.hairColor===0&&!m.includes('<svg')&&m.includes('data-weapon="dagger"');});
 check('Creation grants starting supplies once and no monsters or Echo',()=>{create('bow');const before=P.export();return P.snapshot().inventory.leafdraught===2&&P.snapshot().coins===0&&!P.snapshot().companions.length&&Object.values(P.snapshot().echoes).every(e=>!e.length)&&!P.createCharacter({name:'Other',weapon:'dagger'})&&P.export()===before;});
 check('Invalid names and weapons do not mutate fresh state',()=>{reset();const before=P.export();return !P.createCharacter({name:'<b>',weapon:'bow'})&&!P.createCharacter({name:'Rowan',weapon:'laser'})&&P.export()===before;});
 check('Old v7 profile migrates as legacy without losing coins/monsters',()=>{const s=P.normalize({version:7,coins:17,inventory:{biscuit:3},companions:[{id:'kept',type:'emberfox',xp:600,skills:BondContent.UNITS.emberfox.default}]});return s.character.legacy&&s.coins===17&&s.inventory.biscuit===3&&s.companions[0].id==='kept'&&s.companions[0].xp===600;});
 check('Old v6 profile keeps migration IDs and requests only a name',()=>{const s=P.normalize({version:6,owned:['emberfox'],xp:{emberfox:600},coins:14});return s.character.legacy&&O.needsIdentity(s.character)&&s.companions[0].id==='legacy:emberfox'&&s.coins===14;});
 check('Legacy name claim is atomic, one-time and preserves progress',()=>{P.testing.replace({version:6,owned:['emberfox'],xp:{emberfox:600},coins:14});const before=P.snapshot(),named=P.nameCharacter('Ari'),after=P.snapshot(),saved=P.export();return named&&after.character.legacy&&after.character.name==='Ari'&&after.coins===before.coins&&after.companions[0].id===before.companions[0].id&&after.companions[0].xp===before.companions[0].xp&&!P.nameCharacter('Other')&&P.export()===saved;});
 check('Literal Apprentice placeholder can be named without changing its created build',()=>{P.testing.replace({version:7,character:{name:'Apprentice',weapon:'bow',look:{hair:'braid',face:'bright',hairColor:3,skinColor:4}},attributes:O.attributes('bow')});const before=P.snapshot(),ok=P.nameCharacter('Iris'),after=P.snapshot();return ok&&after.character.name==='Iris'&&after.character.weapon==='bow'&&JSON.stringify(after.character.look)===JSON.stringify(before.character.look)&&JSON.stringify(after.attributes)===JSON.stringify(before.attributes);});
 check('New identity survives normalization with every look choice',()=>{create('bow');return JSON.stringify(P.normalize(P.snapshot()).character)===JSON.stringify(P.snapshot().character);});
 check('Creation cannot overwrite an uncreated profile that has earned progress',()=>{reset();const s=P.snapshot();s.coins=7;P.testing.replace(s);const before=P.export();return !P.createCharacter({name:'Rowan',weapon:'bow'})&&P.export()===before;});
 check('Failed critical creation retains the original state',()=>{reset();const before=P.export(),write=Storage.prototype.setItem;try{Storage.prototype.setItem=function(){throw Error('fixture full storage');};return !P.createCharacter({name:'Rowan',weapon:'bow'})&&P.export()===before;}finally{Storage.prototype.setItem=write;}});
 for(const weapon of ['dagger','bow']){
  check(weapon+' produces a valid three-action solo build',()=>{create(weapon);return G.validBuild([P.migrateParty(G.soloBuild()[0]),G.defaultBuild()[1]])&&P.migrateParty(G.soloBuild()[0])[0].skills.join()===O.weapons[weapon].skills.join();});
  check(weapon+' keeps reasonable starting attributes within budget',()=>{create(weapon);const s=P.snapshot();return BondProgress.validAttributes(s.attributes,1)&&s.attributes[weapon==='bow'?'dex':'str']===12&&BondProgress.trainerLevel(s)===1;});
  // Classic hit rolls allow lucky low-damage wins; preserve guaranteed victory and
  // assess injury across the seeded sample instead of forcing damage on every seed.
  check(weapon+' wins all 30 introductory hunts with bounded time and meaningful average injury',()=>{
   create(weapon);const profile=P.snapshot(),build=G.soloBuild('apprentice');build[0][0]=O.build(profile.character);
   const rows=Array.from({length:30},(_,i)=>{const b=new G.Battle(build,{profile,adventure:true,seed:i+1,encounter:{kind:'wild',enemies:[{type:'emberfox',level:2,skills:BondContent.UNITS.emberfox.default,...T.wild('emberfox')}]}}).run();return {win:b.winner===0,hp:b.trainer(0).hp/b.trainer(0).maxHp,time:b.time,dodges:b.events.filter(e=>e.kind==='dodge').length};});
   const mean=rows.reduce((n,r)=>n+r.hp,0)/rows.length;
   return rows.every(r=>r.win&&r.hp>.25&&r.hp<=1&&r.time<40)&&mean>.25&&mean<.8&&rows.some(r=>r.dodges>0)&&new Set(rows.map(r=>r.hp)).size>5;
  });
  check(weapon+' uses the correct basic damage category and range',()=>{const {b}=fight('emberfox',weapon),u=b.trainer(0);return u.basicCategory===O.weapons[weapon].category&&u.range===O.weapons[weapon].range&&u.name==='Rowan';});
 }
 check('Bow cannot equip dagger-only skills',()=>{const b=G.soloBuild('apprentice');b[0][0]=O.build({weapon:'bow'});b[0][0].skills[0]='trailcut';return !G.validBuild(b);});
 check('Apprentice cannot bypass specialization through the class picker',()=>{create('dagger');const before=P.export();return !BondApp.changeUnit(0,0,'mage')&&P.export()===before&&P.migrateParty(G.soloBuild('mage')[0])[0].type==='apprentice';});
 check('Starter hostile spawn clearance and exact per-map quotas',()=>{create('dagger');const m=A.get('clearing-0'),sp=P.population();return sp.length===BondPopulation.total(m)&&sp.filter(x=>['stonehorn','tideotter'].includes(x.type)).every(x=>Math.hypot(x.x-O.start.position.x,x.y-O.start.position.y)>850)&&sp.some(x=>x.type==='emberfox'&&Math.hypot(x.x-O.start.position.x,x.y-O.start.position.y)<600);});
 check('Near starter placement is stable across population seeds',()=>{const m=A.get('clearing-0');return Array.from({length:32},(_,i)=>BondPopulation.position(m,'clearing-0:emberfox:0',i*13499+7,[],null,true)).every(p=>p&&Math.hypot(p.x-O.start.position.x,p.y-O.start.position.y)<600);});
 const actor=()=>({type:'stonehorn',habitat:{map:'clearing-1'},x:1000,y:1000,homeX:1000,homeY:1000});
 check('Fresh spawn is at a reachable interior camp, away from map exits',()=>{create('bow');return !A.collision(O.start.map,O.start.position)&&Math.hypot(O.start.position.x-O.camp.x,O.start.position.y-O.camp.y)<150&&A.get(O.start.map).neighbors.every(g=>Math.hypot(g.x-O.start.position.x,g.y-O.start.position.y)>1000);});
 check('Firstlight has broad difficulty bands and no creatures inside the camp refuge',()=>{create('dagger');return P.population().every(p=>O.groundAllowed('clearing-0',p.id,p)&&Math.hypot(p.x-O.camp.x,p.y-O.camp.y)>=400);});
 check('Camp rest requires real proximity and does not discover the distant hero landmark',()=>{create('dagger');const s=P.snapshot();s.vitality.trainer=1000;P.testing.replace(s);P.position({x:190,y:5040});const denied=!P.rest();P.position(O.start.position);return denied&&P.rest()&&T.health(P.snapshot())===10000&&!P.snapshot().sights.includes(A.get('clearing-0').hero.id);});
 check('Unsafe old spawn positions move into their band without rerolling their life',()=>{create('dagger');const sp=P.population().find(p=>p.type==='stonehorn'),s=P.snapshot();s.spawns[sp.id].x=2200;s.spawns[sp.id].y=5140;P.testing.replace(s);const moved=P.population().find(p=>p.id===sp.id);return moved.x>=6500&&moved.life===sp.life&&moved.seed===sp.seed&&moved.roll===sp.roll;});
 check('A held old spawn is not relocated during its reserved fight',()=>{create('dagger');const sp=P.population().find(p=>p.type==='stonehorn'),e=P.beginHunt(sp.id),build=G.soloBuild('apprentice');build[0][0]=O.build(P.snapshot().character);const opts={profile:P.snapshot(),adventure:true,encounter:e,seed:e.seed},b=new G.Battle(build,opts);P.reserveBattle(b,e.id,opts);const s=P.snapshot();s.spawns[sp.id].x=2200;s.spawns[sp.id].y=5140;P.testing.replace(s);return P.population().find(p=>p.id===sp.id).x===2200&&!!P.restoreBattle(e.id);});
 check('Defeats after leaving Firstlight restore the party at its regional city',()=>{create('bow');P.travel('clearing-1');const s=P.snapshot();s.vitality.trainer=1;P.testing.replace(s);const sp=P.population().find(p=>p.type==='tideotter'),e=P.beginHunt(sp.id),build=G.soloBuild('apprentice');build[0][0]=O.build(s.character);const opts={profile:P.snapshot(),adventure:true,encounter:e,seed:e.seed},b=new G.Battle(build,opts);P.reserveBattle(b,e.id,opts);b.run();const result=P.complete(b,e.id);return result.rescued&&!result.campRecovery&&P.snapshot().map==='clearing-hub'&&T.health(P.snapshot())===10000;});
 check('All 288 first-map residents occupy distinct dry reachable ground',()=>{create('dagger');const sp=P.population();let nearest=Infinity,pair=[];for(let i=0;i<sp.length;i++)for(let j=i+1;j<sp.length;j++){const d=Math.hypot(sp[i].x-sp[j].x,sp[i].y-sp[j].y);if(d<nearest){nearest=d;pair=[sp[i].id,sp[j].id];}}const blocked=sp.filter(p=>A.collision('clearing-0',p,55)).map(p=>p.id),wet=sp.filter(p=>BondWorldLayout.waterAt(A.get('clearing-0'),p)).map(p=>p.id);const pass=sp.length===288&&!blocked.length&&!wet.length&&nearest>=178;if(!pass)throw Error(JSON.stringify({count:sp.length,nearest,pair,blocked,wet}));return true;});
 check('Saved integer spawn coordinates are validated after rounding at an obstacle boundary',()=>{
  const id='clearing-0:emberfox:rounding',seed=12345,m={id:'rounding-fixture',width:1000,height:1000,entry:{x:500,y:500},neighbors:[],roads:[]};
  let value=(seed^A.hash(id+':position'))>>>0;const random=()=>{value=(Math.imul(value,1664525)+1013904223)>>>0;return value/4294967296;};
  const candidate={x:200+random()*600,y:200+random()*600},obstacle={x:Math.round(candidate.x),y:Math.round(candidate.y)},radius=Math.hypot(candidate.x-obstacle.x,candidate.y-obstacle.y)/2;
  const collision=A.collision,water=BondWorldLayout.waterAt,ground=O.groundAllowed,clear=BondNav.clear;
  try{A.collision=(_id,p)=>Math.hypot(p.x-obstacle.x,p.y-obstacle.y)<=radius;BondWorldLayout.waterAt=()=>false;O.groundAllowed=()=>true;BondNav.clear=()=>true;
   const p=BondPopulation.position(m,id,seed);return p&&!A.collision(m.id,p);
  }finally{A.collision=collision;BondWorldLayout.waterAt=water;O.groundAllowed=ground;BondNav.clear=clear;}
 });
 check('Existing low-density save fills new slots without rerolling old lives',()=>{create('dagger');const raw=P.snapshot();P.population();Object.assign(raw.spawns,P.snapshot().spawns);for(const id of Object.keys(raw.spawns))if(Number(id.split(':').at(-1))>={emberfox:48,bloomslime:32,stonehorn:16}[id.split(':')[1]])delete raw.spawns[id];const kept=JSON.parse(JSON.stringify(raw.spawns));P.testing.replace(raw);const sp=P.population();return sp.length===288&&Object.entries(kept).every(([id,v])=>{const n=P.snapshot().spawns[id];return n.life===v.life&&n.seed===v.seed&&n.roll===v.roll&&n.x===v.x&&n.y===v.y;});});
 check('Tideotter follows its Sheet region while retaining its stable spawn identity',()=>A.get(A.home('tideotter').map).regionIndex===BondContent.UNITS.tideotter.region&&A.home('tideotter').id==='clearing-0:tideotter'&&A.get('clearing-0').habitats.every(h=>h.type!=='tideotter')&&!A.validate().length);
 for(const [type,oldLevel] of [['emberfox',1],['tideotter',10]])check('Reserved legacy '+type+' keeps its original source level, map and rewards',()=>{
  create('dagger');P.travel(A.home(type).map);const sp=P.population().find(x=>x.type===type);P.testing.setRoll(sp.id,0);const e=P.beginHunt(sp.id),build=G.soloBuild('apprentice');build[0][0]=O.build(P.snapshot().character);const options={profile:P.snapshot(),adventure:true,encounter:e,seed:e.seed},initial=new G.Battle(build,options);P.reserveBattle(initial,e.id,options);
  const raw=P.snapshot();raw.map='clearing-0';raw.position=O.start.position;raw.encounterSave.encounter.map='clearing-0';raw.encounterSave.encounter.enemies[0].level=oldLevel;raw.encounterSave.options.encounter=raw.encounterSave.encounter;P.testing.replace(raw);
  const b=P.restoreBattle(e.id);for(const u of b.units.filter(u=>u.side===1))u.hp=0;b.ended=true;b.winner=0;b.reason='Controlled migration receipt fixture';const result=P.complete(b,e.id),claim=P.snapshot().claims[sp.id+':'+sp.life];const after=P.export();P.complete(b,e.id);return result.kills===1&&claim.map==='clearing-0'&&claim.level===oldLevel&&claim.xp===T.xp(oldLevel)&&P.snapshot().echoes[type][0].level===oldLevel&&P.export()===after;
 });
 check('Every town fully heals and revives for zero coins and zero supplies',()=>{create('dagger');const id=P.summon('emberfox','apprentice',P.testing.grantEcho('emberfox',100)).instanceId;return A.maps.filter(m=>m.kind==='hub').every(m=>{const s=P.snapshot();s.map=m.id;s.area=m.region;s.position={...m.entry};s.coins=0;s.inventory={};s.vitality={trainer:0,companions:{[id]:0}};P.testing.replace(s);return !P.canService('sanctuary')&&T.health(P.snapshot())===10000&&T.health(P.snapshot(),id)===10000&&P.snapshot().coins===0&&Object.keys(P.snapshot().inventory).length===0;});});
 check('Only the starting map is passive at every player level',()=>A.maps.flatMap(m=>m.habitats).every(h=>{const a={type:h.type,habitat:h};return [1,h.level+9,h.level+10,60,100].every(level=>!!BondWildBehavior.policy(h.map,h.type,a,level)===(h.map!=='clearing-0'));}));
 check('A resident restored on the passive starting map returns home without contact',()=>['alert','chase'].every(mode=>{const a={...actor(),mode,x:1100,habitat:{map:'clearing-0',level:5}},p={x:1105,y:1000};const hit=BondWildBehavior.step(a,p,.05,{trainerLevel:15});if(hit||a.mode!=='return'||a.x>=1100)return false;for(let i=0;i<40;i++)if(BondWildBehavior.step(a,p,.05,{trainerLevel:15}))return false;return a.mode==='idle';}));
 check('Warning precedes pursuit and contact',()=>{const a=actor(),p={x:1200,y:1000};const first=BondWildBehavior.step(a,p,.05);if(first||a.mode!=='alert'||a.x!==1000)return false;for(let i=0;i<22;i++)BondWildBehavior.step(a,p,.05);return a.mode==='chase'&&a.x>1000;});
 check('Blocked sight prevents acquisition and attack',()=>{const a=actor();for(let i=0;i<100;i++)if(BondWildBehavior.step(a,{x:1040,y:1000},.05,{clear:()=>false}))return false;return a.mode==='idle';});
 check('Disabled pursuit cannot trigger an encounter',()=>{const a=actor();a.mode='chase';return !BondWildBehavior.step(a,{x:1005,y:1000},.05,{enabled:false})&&a.mode!=='chase';});
 check('Pursuit respects movement collision callback',()=>{const a=actor();a.mode='chase';for(let i=0;i<40;i++)BondWildBehavior.step(a,{x:1250,y:1000},.05,{move:(_q,p)=>p});return a.x===1000&&a.y===1000;});
 check('Leash returns actor home instead of chasing forever',()=>{const a=actor(),leash=BondWildBehavior.policy(a.habitat.map,a.type,a).leash;a.x=a.homeX+leash+20;a.mode='chase';const start=a.x;BondWildBehavior.step(a,{x:start+50,y:1000},.05);if(a.mode!=='return'||a.x>=start)return false;for(let i=0;i<200;i++)BondWildBehavior.step(a,{x:start+1000,y:1000},.05);return a.mode==='idle'&&Math.hypot(a.x-a.homeX,a.y-a.homeY)<8;});
 check('Contact raises a single normal encounter request condition',()=>{const a=actor();a.mode='chase';return BondWildBehavior.step(a,{x:1040,y:1000},.05);});
 check('Seeded supply drops repeat and do not depend on Echo roll',()=>JSON.stringify(O.loot('emberfox','clearing-0',72))===JSON.stringify(O.loot('emberfox','clearing-0',72))&&Object.keys(O.loot('emberfox','brook-0',72)).length===0);
 check('Supply drop distribution is close to the declared 35% over 10000 seeds',()=>{let hits=0;for(let i=0;i<10000;i++)hits+=O.loot('emberfox','clearing-0',i).leafdraught||0;return hits>3300&&hits<3700;});
 check('Accepted supply loot grants once and survives claim normalization/replay',()=>{const {b,e,sp}=fight();const raw=P.snapshot();let seed=1;while(!O.loot('emberfox','clearing-0',seed).leafdraught)seed++;raw.spawns[sp.id].seed=seed;P.testing.replace(raw);b.run();const before=P.snapshot().inventory.leafdraught,r=P.complete(b,e.id),after=P.snapshot();P.testing.replace(after);const again=P.complete(b,e.id);return r.loot.leafdraught===1&&P.snapshot().inventory.leafdraught===before+1&&JSON.stringify(r)===JSON.stringify(again)&&P.snapshot().claims[sp.id+':'+sp.life].loot.leafdraught===1;});
 check('Saved apprentice bow fight replays identical outcome and events',()=>{const {b,e}=fight('emberfox','bow');for(let i=0;i<90;i++)b.step();P.checkpoint(b);P.testing.replace(P.snapshot());const restored=P.restoreBattle(e.id);return restored.build[0][0].weapon==='bow'&&JSON.stringify(restored.events)===JSON.stringify(b.events)&&restored.trainer(0).hp===b.trainer(0).hp;});
 check('Firstlight defeat returns to camp fully recovered without losing accepted coins',()=>{create('bow');const s=P.snapshot();s.vitality.trainer=1;s.coins=13;P.testing.replace(s);const sp=P.population().find(x=>x.type==='stonehorn'),e=P.beginHunt(sp.id),build=G.soloBuild('apprentice');build[0][0]=O.build(s.character);const opts={profile:P.snapshot(),adventure:true,seed:sp.seed,encounter:e},b=new G.Battle(build,opts);P.reserveBattle(b,e.id,opts);b.trainer(0).actionRemaining=999;b.run();const r=P.complete(b,e.id);return b.winner!==0&&r.rescued&&r.campRecovery&&P.snapshot().map==='clearing-0'&&P.snapshot().coins===13&&T.health(P.snapshot())===10000&&P.canService('sanctuary')&&P.rest()&&T.health(P.snapshot())===10000;});
 check('Trainer and companion levels use the same curve without deriving from each other',()=>{const current=P.normalize({version:7,progression:{version:2},trainerXP:100,character:{name:'Iris',weapon:'dagger',look:O.defaultLook},companions:[{id:'high',type:'emberfox',xp:BondProgress.threshold(30),skills:BondContent.UNITS.emberfox.default}]}),legacy=P.normalize({version:7,character:{legacy:true,name:'Ari'},companions:[{id:'old',type:'emberfox',xp:BondProgress.threshold(30),skills:BondContent.UNITS.emberfox.default}]});return BondProgress.trainerLevel(current)===2&&BondProgress.monLevel(current,'high')===30&&BondProgress.trainerLevel(legacy)===30;});
 check('The first defeated Brimble grants one guaranteed Echo and exactly the Lv2 trainer threshold',()=>{create('dagger');const sp=P.population().find(x=>x.type==='emberfox'&&!x.id.endsWith(':0'));P.testing.setRoll(sp.id,9999);const e=P.beginHunt(sp.id),build=G.soloBuild('apprentice');build[0][0]=O.build(P.snapshot().character);const opts={profile:P.snapshot(),adventure:true,seed:e.seed,encounter:e},b=new G.Battle(build,opts);if(!P.reserveBattle(b,e.id,opts))return false;b.units.filter(u=>u.side===1).forEach(u=>u.hp=0);b.checkEnd();const r=P.complete(b,e.id),saved=P.snapshot(),before=P.export();P.complete(b,e.id);return r.echo&&r.trainerXP===100&&saved.trainerXP===BondProgress.threshold(2)&&saved.journey.early.introFightWon&&saved.echoes.emberfox.length===1&&P.export()===before;});
 check('Forest Mage meeting, two-companion trial and road gate are explicit milestones',()=>{create('dagger');let s=P.snapshot(),mage=P.encounter('early:forest-mage');if(A.unlocked(s,'clearing-hub')||BondCampaign.visible(mage,s))return false;s.journey.early.introFightWon=true;s.journey.early.firstSummon=true;P.testing.replace(s);if(!BondCampaign.visible(mage,P.snapshot())||!P.meetOpeningMage()||BondCampaign.earlyNext(P.snapshot()).id!=='ep:summon2'||A.unlocked(P.snapshot(),'clearing-hub'))return false;const a=P.summon('emberfox','apprentice',P.testing.grantEcho('emberfox',2)).instanceId,b=P.summon('bloomslime','apprentice',P.testing.grantEcho('bloomslime',3)).instanceId,party=[O.build(P.snapshot().character),{type:'emberfox',instanceId:a,skills:[...BondContent.UNITS.emberfox.default]},{type:'bloomslime',instanceId:b,skills:[...BondContent.UNITS.bloomslime.default]}];if(P.requirement(mage.id,party))return false;s=P.snapshot();BondCampaign.recordWin(s,mage);return s.journey.early.mageGate&&A.unlocked(s,'clearing-hub')&&BondCampaign.earlyNext(s).id==='story:clearing:0';});
 check('Quest markers distinguish offers from deliveries without marking unrelated NPCs',()=>{create('dagger');const mage=P.encounter('early:forest-mage'),unrelated=BondCampaign.trainers[0];let s=P.snapshot();s.journey.early.introFightWon=true;s.journey.early.firstSummon=true;P.testing.replace(s);s=P.snapshot();if(BondCampaign.questMarker(mage,s)!=='offer'||BondCampaign.questMarker(unrelated,s)!==null)return false;s.journey.early.mageMet=true;s.journey.early.secondSummon=true;P.testing.replace(s);s=P.snapshot();if(BondCampaign.questMarker(mage,s)!=='delivery')return false;BondCampaign.recordWin(s,mage);s.journey.wins['story:clearing:0']=1;return BondCampaign.questMarker(BondWorld.NPCS['story:brook:1'],s)==='offer';});
 check('Forest Mage trial is a short protected opening for either starting weapon',()=>['dagger','bow'].every(weapon=>{create(weapon);const a=P.summon('emberfox','apprentice',P.testing.grantEcho('emberfox',2)).instanceId,b=P.summon('bloomslime','apprentice',P.testing.grantEcho('bloomslime',3)).instanceId,mage=P.encounter('early:forest-mage'),team=[O.build(P.snapshot().character),{type:'emberfox',instanceId:a,skills:[...BondContent.UNITS.emberfox.default]},{type:'bloomslime',instanceId:b,skills:[...BondContent.UNITS.bloomslime.default]}],battle=new G.Battle([team,mage.team],{profile:P.snapshot(),adventure:true,enemyLevel:mage.level,seed:mage.seed});battle.run();return mage.protectedEncounter===true&&battle.winner===0&&battle.time<45;}));
 check('Second-role victory grants only the selected guaranteed Echo and reaches Lv4',()=>{create('dagger');let raw=P.snapshot();raw.journey.early.introFightWon=true;raw.trainerXP=100;P.testing.replace(raw);const fox=P.summon('emberfox','apprentice',P.testing.grantEcho('emberfox',2)).instanceId;const sp=P.population().find(x=>x.type==='bloomslime');P.testing.setRoll(sp.id,9999);const e=P.beginHunt(sp.id),team=[O.build(P.snapshot().character),{type:'emberfox',instanceId:fox,skills:[...BondContent.UNITS.emberfox.default]},null],opts={profile:P.snapshot(),adventure:true,seed:e.seed,encounter:e},b=new G.Battle([team,G.defaultBuild()[1]],opts);if(!P.reserveBattle(b,e.id,opts))return false;b.units.filter(u=>u.side===1).forEach(u=>u.hp=0);b.checkEnd();const r=P.complete(b,e.id),s=P.snapshot();return r.echo&&r.trainerXP===500&&s.journey.early.companionProof&&s.journey.early.secondChoice==='bloomslime'&&s.echoes.bloomslime.length===1&&!(s.echoes.stonehorn||[]).length&&BondProgress.trainerLevel(s)===4;});
 check('Early progression encounters validate and provide the exact authored Lv30 XP path',()=>{const E=BondCampaign.earlyEncounters,by=id=>E.find(e=>e.id===id),demos=['story:clearing:0','story:brook:1','story:brook:3','story:brook:4'].reduce((n,id)=>n+BondWorld.NPCS[id].trainerXP,600),post=['early:application:druid','early:counter','early:ability','early:resolution'],amber=['early:amber:1','early:amber:2','early:amber:3','early:boss:amber'];return !BondCampaign.validate().length&&demos===6600&&demos+by('early:boss:tidecrown').trainerXP===10500&&demos+by('early:boss:tidecrown').trainerXP+by('early:master:druid').trainerXP===19000&&post.reduce((n,id)=>n+by(id).trainerXP,19000)===30000&&amber.reduce((n,id)=>n+by(id).trainerXP,30000)===43500;});
 check('Tidecrown victory records the milestone that reveals both masters',()=>{const s=P.fresh();s.character={name:'Ari',weapon:'dagger',look:O.defaultLook};s.journey.early.demonstrations=Object.values(BondCampaign.DEMONSTRATIONS);const tide=BondCampaign.earlyEncounters.find(e=>e.id==='early:boss:tidecrown');BondCampaign.recordWin(s,tide);return s.journey.early.tidecrown&&BondCampaign.earlyEncounters.filter(e=>e.masterClass).every(e=>BondCampaign.visible(e,s));});
 check('Class trials are available before Lv20 but transformation waits for Lv20',()=>{create('dagger');let s=P.snapshot();s.journey.early.introFightWon=true;s.journey.early.demonstrations=Object.values(BondCampaign.DEMONSTRATIONS);s.journey.early.tidecrown=true;s.journey.early.trials.druid=true;s.trainerXP=BondProgress.threshold(19);P.testing.replace(s);if(P.canSpecialize('druid'))return false;s=P.snapshot();s.trainerXP=BondProgress.threshold(20);P.testing.replace(s);const result=P.specialize('druid'),build=P.migrateParty(G.soloBuild('mage')[0]);return result?.type==='druid'&&P.snapshot().progression.specialization==='druid'&&build[0].type==='druid'&&BondGrowth.unlocked(P.snapshot(),'druid')&&!P.specialize('mage');});
 check('Owned monster trees unlock immediately and stay independent per individual',()=>{create('dagger');const a=P.summon('emberfox','apprentice',P.testing.grantEcho('emberfox',2)).instanceId,b=P.summon('emberfox','apprentice',P.testing.grantEcho('emberfox',2)).instanceId,node=BondGrowth.nodes('emberfox')[0].id;const before=P.snapshot(),learned=P.learn(a,node),after=P.snapshot();return BondProgress.trainerLevel(before)===1&&BondGrowth.unlocked(before,a)&&BondGrowth.budget(before,a)===1&&learned&&after.companions.find(m=>m.id===a).growth[node]===1&&!after.companions.find(m=>m.id===b).growth[node];});
 check('Every monster tree exposes its 24 authored talents across three eight-node paths',()=>BondContent.MONSTERS.every(type=>{const nodes=BondGrowth.nodes(type),source=BondMonsterProgression.talents[type];return nodes.length===24&&['A','B','C'].every(branch=>nodes.filter(n=>n.branchId===branch).length===8)&&nodes.every((n,i)=>n.id===source[i].id&&n.name===source[i].name&&n.max===1)&&nodes.filter(n=>n.exclusive_with.length).length===3;}));
}finally{P.testing.replace(original);BondApp.switchTab('region');}
return out;
}
