"""Played Pass18 UI flows, isolated browser save, temporary localhost server."""
import argparse,functools,json,threading,hashlib,traceback
from datetime import datetime,timedelta,timezone
from http.server import ThreadingHTTPServer
from browser_check import legacy_adventure, ROOT,ARTIFACTS,QuietServer,find_browser,sync_playwright
parser=argparse.ArgumentParser();parser.add_argument('--browser',default='chrome');args=parser.parse_args()
server=ThreadingHTTPServer(('127.0.0.1',0),functools.partial(QuietServer,directory=str(ROOT)))
threading.Thread(target=server.serve_forever,daemon=True).start();url=f'http://127.0.0.1:{server.server_port}/?test=1'
hashes=lambda:{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted([*ROOT.glob('*.js'),*ROOT.glob('*.css'),ROOT/'index.html'])}
source=hashes();checks=[];errors=[];missing=[]
def check(name,value,detail=None):
    checks.append({'name':name,'pass':bool(value),'detail':detail})
    if not value:print('FAIL '+name,flush=True)
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=find_browser(args.browser),headless=True)
    context=browser.new_context(viewport={'width':1440,'height':1000});page=context.new_page()
    page.on('pageerror',lambda e:errors.append(str(e)));page.on('response',lambda r:missing.append(r.url) if r.status>=400 else None)
    now=datetime.now(timezone.utc);page.clock.install(time=now);page.clock.pause_at(now+timedelta(seconds=10))
    try:
        legacy_adventure(page)
        page.goto(url);page.wait_for_function('!!window.BondApp');page.wait_for_function('WorldRenderer.inspect().terrainReady')
        check('World hides backend tuning and shows current health',page.locator('.test-tuning').count()==0 and '100%' in page.locator('#field-vitality').inner_text())
        check('Successful scenery loading stays silent',page.locator('#world-load-state').inner_text()=='')
        check('Roaming wild creatures have no visible species nameplates',page.locator('.map-object.wild .world-label').count()==0)
        # Bridges now load on demand, not while creating a distant character.
        page.evaluate('''()=>{window.qaBridgeOrigin=BondProfile.snapshot().position;const m=BondAtlas.get(BondProfile.snapshot().map),b=m.bridges[0];BondProfile.position(BondAtlas.safePoint(m.id,{x:(b.a.x+b.b.x)/2,y:(b.a.y+b.b.y)/2}));BondApp.switchTab('region');}''')
        page.clock.run_for(300);page.wait_for_function('WorldRenderer.inspect().bridgeReady');page.clock.run_for(300)
        check('Approaching a bridge loads and paints its lossless sprite',page.evaluate('WorldRenderer.inspect().bridgesPainted>0&&WorldRenderer.inspect().bridgeAsset.endsWith(".webp")'))
        page.evaluate('BondProfile.position(qaBridgeOrigin);BondApp.switchTab("region")')
        page.evaluate("BondApp.changeUnit(0,0,'mage')")
        health=[]
        for attempt in range(2):
            spawn=page.evaluate("""()=>{const P=BondProfile,sp=P.population().find(x=>x.type==='emberfox'&&x.present);P.testing.setRoll(sp.id,1499);P.position(BondAtlas.safePoint(P.snapshot().map,{x:sp.x-170,y:sp.y}));BondApp.switchTab('region');return sp;}""")
            page.clock.run_for(200);page.locator('[data-object="'+spawn['id']+'"]').click();page.clock.run_for(4000)
            check('Wild contact starts immediately without a confirmation dialog '+str(attempt),not page.locator('#npc-dialog').is_visible() and page.evaluate('BondApp.isRunning()&&BondApp.getTab()==="battle"') and '15%' not in page.locator('#battle-description').inner_text())
            for _ in range(160):
                page.clock.run_for(250)
                if page.evaluate('BondApp.getBattle().ended'): break
            check('Played hunt returns immediately with drops '+str(attempt),page.evaluate('BondApp.getBattle().ended&&BondApp.getBattle().winner===0&&BondApp.getTab()==="region"') and page.locator('.loot-toast').count()>0)
            health.append(page.evaluate('BondAdventure.health(BondProfile.snapshot())'));page.evaluate("document.querySelectorAll('.loot-dismiss').forEach(b=>b.click())")
        check('Successive completed hunts auto-heal in test mode',health==[10000,10000],health)
        page.reload();page.wait_for_function('!!window.BondApp')
        check('Actual browser reload retains the automatic recovery',page.evaluate('BondAdventure.health(BondProfile.snapshot())')==10000)
        page.evaluate("BondApp.changeUnit(0,0,'druid');BondApp.switchTab('region')")
        check('Changing trainer class leaves the recovered health intact',page.evaluate('BondAdventure.health(BondProfile.snapshot())')==10000)
        # QA places the actor near a physical gate; the atlas performs the gate crossing.
        page.evaluate("""()=>{const P=BondProfile,s=P.snapshot();s.journey.early.mageMet=true;s.journey.early.mageGate=true;P.testing.replace(s);const m=BondAtlas.get('clearing-0'),g=m.neighbors.find(g=>g.to==='clearing-hub');P.position(BondAtlas.safePoint(m.id,{x:g.x,y:g.y+180}));BondApp.switchTab('region');}""")
        page.locator('#open-atlas').click();page.locator('[data-atlas-select="clearing-hub"]').focus();page.keyboard.press('Enter')
        check('Keyboard selects map destination without teleporting',page.evaluate('BondProfile.snapshot().map==="clearing-0"') and 'Mosslight Village' in page.locator('.atlas-destination').inner_text())
        check('Atlas roads exactly represent reciprocal graph edges',page.evaluate("""()=>{const edges=new Set(BondAtlas.maps.flatMap(m=>m.neighbors.map(g=>[m.id,g.to].sort().join('|'))));return document.querySelectorAll('[data-atlas-road]').length===edges.size&&[...document.querySelectorAll('[data-atlas-road]')].every(p=>edges.has(p.dataset.atlasRoad));}"""))
        check('Atlas derives six average wildlife levels and colors them against trainer level',page.evaluate("""()=>{const trainer=BondProgress.trainerLevel(BondProfile.snapshot()),lands=[...document.querySelectorAll('.atlas-land')];return lands.length===6&&lands.every((g,i)=>Number(g.dataset.atlasAverage)===BondWorldMap.average(i)&&g.classList.contains('threat-'+BondWorldMap.threat(Number(g.dataset.atlasAverage),trainer)))&&BondWorldMap.threat(10,10)==='safe'&&BondWorldMap.threat(15,10)==='caution'&&BondWorldMap.threat(16,10)==='danger';}"""))
        page.locator('[data-atlas-region="clearing"]').dispatch_event('mouseenter')
        page.clock.run_for(200)
        check('Hovering a reach reveals its colored average-level card',page.locator('[data-atlas-region="clearing"] .atlas-region-info').evaluate("e=>getComputedStyle(e).opacity==='1'") and 'AVG LV.' in page.locator('[data-atlas-region="clearing"] .atlas-region-info').text_content())
        page.screenshot(path=str(ARTIFACTS/f'pass18-atlas-ui-{args.browser}.png'),full_page=True)
        page.locator('[data-world-travel="clearing-hub"]').click();page.clock.run_for(6000)
        check('Atlas Walk here crosses the physical gate',page.evaluate('BondProfile.snapshot().map==="clearing-hub"'))
        page.evaluate("BondProfile.position(BondAdventure.service(BondAtlas.get('clearing-hub'),'shop'));BondApp.switchTab('region')");page.clock.run_for(200)
        page.screenshot(path=str(ARTIFACTS/f'pass18-tent-{args.browser}.png'),full_page=True)
        page.locator('.map-object.shop').click();page.clock.run_for(500)
        before=page.evaluate('BondProfile.snapshot().coins');potions=page.evaluate('BondProfile.snapshot().inventory.leafdraught||0');page.locator('[data-store-buy="leafdraught"]').click()
        check('Tent shop buys one cheap potion with earned hunt coins',page.evaluate('BondProfile.snapshot().coins')==before-3 and page.evaluate('BondProfile.snapshot().inventory.leafdraught')==potions+1)
        page.screenshot(path=str(ARTIFACTS/f'pass18-shop-ui-{args.browser}.png'),full_page=True);page.keyboard.press('Escape')
        page.evaluate("""()=>{const s=BondProfile.snapshot();s.vitality.trainer=5000;BondProfile.testing.replace(s);BondApp.switchTab('region');}""")
        page.locator('[data-world-menu="inventory"]').click();page.locator('.earned-supplies [data-open-recovery]').click();before=page.evaluate('BondAdventure.health(BondProfile.snapshot())');page.locator('[data-recovery-target="trainer"]').click()
        check('Field UI applies potion and consumes exactly one',page.evaluate('BondAdventure.health(BondProfile.snapshot())')==min(10000,before+4500) and page.evaluate('BondProfile.snapshot().inventory.leafdraught')==potions)
        page.keyboard.press('Escape')
        page.evaluate("""()=>{const s=BondProfile.snapshot();s.vitality.trainer=5000;BondProfile.testing.replace(s);BondProfile.position(BondAdventure.service(BondAtlas.get('clearing-hub'),'sanctuary'));BondApp.switchTab('region');}""")
        page.clock.run_for(200);page.locator('.map-object.sanctuary').click();page.clock.run_for(500);before=page.evaluate('BondProfile.snapshot().coins');page.locator('[data-sanctuary-rest]').click()
        check('Painted sanctuary heals for free, stays outside Loadout',page.evaluate('BondAdventure.health(BondProfile.snapshot())===10000&&BondApp.getTab()==="region"') and page.evaluate('BondProfile.snapshot().coins')==before)
        page.keyboard.press('Escape')
        sign=page.evaluate("""()=>{const m=BondAtlas.get('clearing-1'),l=m.landmarks.find(l=>l.kind==='lookout');BondProfile.travel(m.id,{x:l.x,y:l.y+160});BondApp.switchTab('region');return 'sight:'+l.id;}""")
        page.clock.run_for(300);page.screenshot(path=str(ARTIFACTS/f'pass18-sign-{args.browser}.png'),full_page=True)
        check('Entering a map does not display its authored description',page.locator('#world-status').inner_text()=='' and page.locator('#region-message').inner_text()=='' and page.evaluate("!document.body.innerText.includes(BondAtlas.get('clearing-1').info)"))
        check('Lookout is one direct sign hit target, no green marker',page.locator('[data-object="'+sign+'"].road-sign').count()==1 and page.locator('[data-object="'+sign+'"] .landmark-art').count()==0)
        page.evaluate("document.querySelector('#world-quality').click()");page.clock.run_for(200)
        check('Road sign remains painted in low-effects mode',page.evaluate("id=>!!WorldRenderer.bounds(id.slice(6))",sign))
        page.evaluate("document.querySelector('#world-quality').click()");page.clock.run_for(200)
        page.locator('[data-object="'+sign+'"]').click();page.clock.run_for(1000)
        check('Clicking road sign shows useful resident information without map prose or loot debug text',page.locator('#exploration-dialog').is_visible() and 'LOCAL INFORMATION' in page.locator('#exploration-dialog').inner_text() and 'Local residents' in page.locator('#exploration-dialog').inner_text() and page.evaluate("!document.querySelector('#exploration-dialog').innerText.includes(BondAtlas.get('clearing-1').info)") and '15%' not in page.locator('#exploration-dialog').inner_text() and 'immediate replacement' not in page.locator('#exploration-dialog').inner_text())
        page.keyboard.press('Escape')
        # A deliberately low-HP fixture verifies the played defeat/recovery handoff.
        page.evaluate("""()=>{BondApp.changeUnit(0,0,'mage');const P=BondProfile,s=P.snapshot();s.vitality.trainer=50;P.testing.replace(s);P.travel('clearing-0');const sp=P.population().find(x=>x.type==='stonehorn'&&x.present);P.position(BondAtlas.safePoint('clearing-0',{x:sp.x-170,y:sp.y}));BondApp.switchTab('region');if(!BondApp.startRegionBattle(P.beginHunt(sp.id).id))throw Error('QA defeat encounter did not start');}""")
        page.clock.run_for(80000)
        check('Played Firstlight defeat returns to the forest camp fully rested',page.evaluate('BondApp.getBattle().ended&&BondApp.getBattle().winner===1&&BondProfile.snapshot().map==="clearing-0"&&BondAdventure.health(BondProfile.snapshot())===10000'))
        check('Defeat now returns immediately to the region',page.evaluate('BondApp.getTab()==="region"'));page.clock.run_for(200);page.locator('.map-object.sanctuary').click();page.clock.run_for(300);page.locator('[data-sanctuary-rest]').click();page.keyboard.press('Escape')
        check('Rescued trainer can recover and continue',page.evaluate('BondAdventure.health(BondProfile.snapshot())===10000'))
        for width in [390,768]:
            page.set_viewport_size({'width':width,'height':844});page.clock.run_for(200);page.locator('#open-atlas').click();page.locator('[data-atlas-center="ashen"]').click()
            check(str(width)+'px atlas pans within dialog and keeps dangerous travel open',page.evaluate('document.documentElement.scrollWidth<=innerWidth+2') and not page.locator('.atlas-destination button').is_disabled())
            page.screenshot(path=str(ARTIFACTS/f'pass18-atlas-{width}-{args.browser}.png'),full_page=True)
            page.locator('[data-atlas-center="clearing"]').click()
            check(str(width)+'px region navigation centers the actual map place on both axes',page.evaluate("""()=>{const box=document.querySelector('.atlas-scroll').getBoundingClientRect(),p=document.querySelector('[data-atlas-select="clearing-0"]').getBoundingClientRect();return p.left>=box.left&&p.right<=box.right&&p.top>=box.top&&p.bottom<=box.bottom;}"""))
            page.keyboard.press('Escape')
            page.locator('[data-world-menu="inventory"]').click();page.locator('.earned-supplies [data-open-recovery]').click()
            check(str(width)+'px recovery fits screen',page.evaluate('document.documentElement.scrollWidth<=innerWidth+2&&document.querySelector("#recovery-dialog").scrollWidth<=document.querySelector("#recovery-dialog").clientWidth+2'))
            page.keyboard.press('Escape');page.evaluate("BondApp.switchTab('region')")
        page.set_viewport_size({'width':1440,'height':1000});page.evaluate("BondApp.switchTab('loadout');BondMenu.open('inventory')")
        check('Inventory offers field medicine, not remote purchasing',page.locator('.earned-supplies [data-open-recovery]').count()==1 and page.locator('[data-buy]').count()==0)
        page.evaluate("""()=>{const P=BondProfile,a=P.summon('emberfox','apprentice',P.testing.grantEcho('emberfox',15)).instanceId,b=P.summon('stonehorn','apprentice',P.testing.grantEcho('stonehorn',15)).instanceId;
          let s=P.snapshot();s.character={version:1,name:'Trial Tester',weapon:'dagger',look:BondOpening.defaultLook};s.progression={version:2,specialization:null,treeGrandfathered:false};s.trainerXP=BondProgress.threshold(19);s.journey.early.demonstrations=Object.values(BondCampaign.DEMONSTRATIONS);s.journey.early.tidecrown=true;P.testing.replace(s);
          BondApp.changeUnit(0,1,a);BondApp.changeUnit(0,2,b);const master=BondCampaign.earlyEncounters.find(e=>e.id==='early:master:druid');P.travel(master.map,master);BondApp.switchTab('region');}""")
        page.clock.run_for(300);page.locator('[data-object="early:master:druid"]').click();page.clock.run_for(300)
        check('Druid trial exposes a temporary three-of-five skill build',page.locator('#trial-skill-controls').is_visible() and page.locator('#trial-skill-controls select').count()==3 and page.locator('#trial-skill-controls select').first.locator('option').count()==5 and 'will not change' in page.locator('#trial-skill-controls').inner_text())
        page.locator('#npc-close').click();page.evaluate("""()=>{const s=BondProfile.snapshot();s.journey.early.trials.druid=true;BondProfile.testing.replace(s);BondApp.switchTab('region');}""");page.clock.run_for(300);page.locator('[data-object="early:master:druid"]').click()
        check('Completed class trial shows a disabled transformation before player Lv20',page.locator('#npc-transform').is_visible() and page.locator('#npc-transform').is_disabled())
        page.locator('#npc-close').click();page.evaluate("""()=>{const s=BondProfile.snapshot();s.trainerXP=BondProgress.threshold(20);BondProfile.testing.replace(s);BondApp.switchTab('region');}""");page.clock.run_for(300);page.locator('[data-object="early:master:druid"]').click()
        check('Player Lv20 enables the completed master transformation',page.locator('#npc-transform').is_visible() and not page.locator('#npc-transform').is_disabled())
        page.once('dialog',lambda d:d.accept());page.locator('#npc-transform').click();page.clock.run_for(300)
        check('Transformation atomically replaces Apprentice with the chosen class',page.evaluate("BondProfile.snapshot().progression.specialization==='druid'&&BondApp.getBuild()[0][0].type==='druid'"))
        page.evaluate('BondCampaignMenu.open()')
        check('Journey panel presents one current early objective and milestone progress',page.locator('#campaign-dialog .early-next').count()==1 and page.locator('#campaign-dialog .early-progress article').count()==7 and 'CURRENT' in page.locator('#campaign-dialog').inner_text())
        page.locator('#campaign-close').click()
    except Exception:errors.append(traceback.format_exc())
    check('No JavaScript/test errors',not errors);check('No missing assets',not missing);check('Runtime unchanged during verification',source==hashes());browser.close()
server.shutdown();report={'browser':args.browser,'checks':checks,'errors':errors,'missing':missing,'source_sha256':source}
(ARTIFACTS/f'pass18-ui-{args.browser}.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print(json.dumps({'passed':sum(c['pass'] for c in checks),'total':len(checks),'failures':[c for c in checks if not c['pass']],'errors':errors},indent=2),flush=True)
raise SystemExit(0 if checks and all(c['pass'] for c in checks) else 1)
