()=>{
'use strict';
const P=BondProfile,T=BondAdventure,A=BondAtlas,C=BondContent,G=BondGame,R=BondProgress,out=[];
const check=(name,fn)=>{try{out.push({name:'P18 '+name,pass:!!fn()});}catch(e){out.push({name:'P18 '+name,pass:false,error:e.stack});}};
const reset=()=>P.testing.replace(P.fresh()),mon=(type='emberfox',level=1)=>P.summon(type,'druid',P.testing.grantEcho(type,level)).instanceId;
const team=(trainer='mage',ids=[])=>{const b=G.soloBuild(trainer);ids.forEach((id,i)=>{const m=P.getCompanion(id);b[0][i+1]={type:m.type,instanceId:id,skills:[...m.skills]};});return b;};
function hunt(build=team(),type='emberfox'){
 const sp=P.population().find(x=>x.type===type&&x.present);P.testing.setRoll(sp.id,0);const e=P.beginHunt(sp.id),options={adventure:true,profile:P.snapshot(),encounter:e,seed:e.seed};
 const b=new G.Battle(build,options);if(!P.reserveBattle(b,e.id,options))throw Error('Could not reserve');return {b,e,sp};
}
check('15% means exactly 1500 of 10000 outcomes, boundary inclusive/exclusive',()=>Array.from({length:10000},(_,n)=>BondEchoes.qualifies(n,1500)).filter(Boolean).length===1500&&BondEchoes.qualifies(1499,1500)&&!BondEchoes.qualifies(1500,1500));
check('All 100 species and 94 habitats use test odds; release proposals retained',()=>C.MONSTERS.length===100&&C.MONSTERS.every(t=>C.UNITS[t].echoBP===1500&&[1,1000].includes(C.UNITS[t].releaseEchoBP))&&A.maps.flatMap(m=>m.habitats).every(h=>h.echoBP===1500));
check('Sheet creature identity fields cover all 100 stable IDs',()=>C.MONSTERS.every(t=>{const u=C.UNITS[t];return !!u.designRole&&!!u.combatIdentity&&['Strength-based','Dex-Based','Int-Based'].includes(u.attackBase)&&u.basicCategory==={"Strength-based":'melee',"Dex-Based":'ranged',"Int-Based":'magic'}[u.attackBase]&&Number.isInteger(u.region)&&u.region>=0&&u.region<6&&(u.source==='boss'?u.sourceWildLevel===null:Number.isInteger(u.sourceWildLevel));}));
check('Sheet regions and wild levels drive habitats except the explicit starter override',()=>A.maps.flatMap(m=>m.habitats.map(h=>({m,h}))).every(({m,h})=>{const u=C.UNITS[h.type];return m.regionIndex===u.region&&(m.id==='clearing-0'?h.level==={emberfox:2,bloomslime:3,stonehorn:5}[h.type]:h.level===u.sourceWildLevel);})&&C.MONSTERS.filter(t=>C.UNITS[t].source==='wild').every(t=>A.maps.flatMap(m=>m.habitats).filter(h=>h.type===t).length===1)&&C.MONSTERS.filter(t=>C.UNITS[t].source==='boss').every(t=>A.maps.filter(m=>m.kind==='boss'&&m.boss===t).length===1));
check('Firstlight has exactly three types at Lv2/3/5 and triple its old population',()=>A.get('clearing-0').habitats.length===3&&A.get('clearing-0').habitats.every(h=>h.level==={emberfox:2,bloomslime:3,stonehorn:5}[h.type]&&h.count==={emberfox:48,bloomslime:32,stonehorn:16}[h.type])&&BondPopulation.total(A.get('clearing-0'))===96);
check('Later wildlife uses full base stats and innate',()=>C.MONSTERS.filter(t=>t!=='emberfox').every(t=>T.wild(t).hp===C.UNITS[t].hp&&T.wild(t).power===C.UNITS[t].power&&T.wild(t).skillScale===1&&T.wild(t).passive===C.UNITS[t].passive));
check('Wild party pressure preserves solo opening and makes a three-actor party more than twice as hard to clear',()=>{const solo=T.wildScale(1),duo=T.wildScale(2),full=T.wildScale(3);return solo.hp===1&&solo.power===1&&duo.hp===1.8&&duo.power===1.15&&full.hp===2.6&&full.power===1.3;});
check('Adventure wild scaling changes enemy durability, basic power and skill pressure only when companions deploy',()=>{reset();const a=mon('emberfox',5),b=mon('stonehorn',5),u=C.UNITS.bloomslime,e={kind:'wild',enemies:[{type:'bloomslime',level:5,skills:[...u.default],...T.wild('bloomslime')}]},solo=new G.Battle(team('mage'),{adventure:true,profile:P.snapshot(),encounter:e,seed:9}),full=new G.Battle(team('mage',[a,b]),{adventure:true,profile:P.snapshot(),encounter:e,seed:9}),x=solo.team(1)[0],y=full.team(1)[0];return y.maxHp===Math.round(x.maxHp*2.6)&&y.power===Math.round(x.power*1.3)&&Math.abs(y.skillScale/x.skillScale-1.3)<1e-9;});
check('Legacy migration initializes health and preserves XP and coins',()=>{const s=P.normalize({version:6,owned:['emberfox'],xp:{emberfox:4500},coins:35});return T.health(s)===10000&&T.health(s,s.companions[0].id)===10000&&s.companions[0].xp===4500&&s.coins===35;});
check('Invalid HP fields normalize safely; zero remains zero',()=>{reset();const id=mon(),s=P.snapshot();s.vitality={trainer:0,companions:{[id]:-1,bogus:0}};const n=P.normalize(s);return T.health(n)===0&&T.health(n,id)===10000&&!Object.hasOwn(n.vitality.companions,'bogus');});
check('Distinct copies retain independent injuries, including benched units',()=>{reset();const a=mon(),b=mon(),s=P.snapshot();s.vitality={trainer:6500,companions:{[a]:2000,[b]:9000}};P.testing.replace(s);const x=new G.Battle(team('mage',[a,b]),{adventure:true,profile:P.snapshot()});return x.units[0].hp===Math.round(x.units[0].maxHp*.65)&&x.units[1].hp===Math.round(x.units[1].maxHp*.2)&&x.units[2].hp===Math.round(x.units[2].maxHp*.9);});
check('Class changes and level-up preserve trainer injury percentage',()=>{const s=P.snapshot();s.vitality.trainer=4000;P.testing.replace(s);const id=s.companions[0].id;P.testing.setXP(id,R.threshold(30));return ['druid','mage'].every(t=>{const b=new G.Battle(team(t),{adventure:true,profile:P.snapshot()});return Math.abs(b.trainer(0).hp/b.trainer(0).maxHp-.4)<.002;});});
check('Practice starts at full HP and never records adventure health',()=>{const s=P.snapshot(),before=JSON.stringify(s.vitality),b=new G.Battle(team(),{profile:s});const full=b.trainer(0).hp===b.trainer(0).maxHp;b.trainer(0).hp=1;T.record(s,b);return full&&JSON.stringify(s.vitality)===before;});
check('Checkpoint and replay restore identical HP, events, supply and injuries',()=>{reset();const s=P.snapshot();s.vitality.trainer=8500;s.inventory.battlefood=1;s.boost=true;P.testing.replace(s);const {b,e}=hunt();const receipt=P.consumePrepared(b);for(const u of b.team(0)){u.hp=Math.round(u.hp*1.1);u.maxHp=Math.round(u.maxHp*1.1);}for(let i=0;i<180;i++)b.step();P.checkpoint(b);const saved=P.snapshot();P.testing.replace(saved);const replay=P.restoreBattle(e.id);return receipt.ration&&replay.tick===b.tick&&replay.units.every((u,i)=>u.hp===b.units[i].hp&&u.maxHp===b.units[i].maxHp)&&JSON.stringify(replay.events)===JSON.stringify(b.events)&&T.health(saved)===Math.round(b.trainer(0).hp/b.trainer(0).maxHp*10000);});
check('Abandoning a checkpointed fight preserves damage',()=>{const before=T.health(P.snapshot());return before<8500&&P.abandonBattle()&&T.health(P.snapshot())===before&&!P.snapshot().encounterSave;});
check('Accepted kill grants fast XP and one 15% Echo receipt; completion persists HP',()=>{reset();const id=mon();const {b,e}=hunt(team('mage',[id]));b.run();const before=P.getCompanion(id).xp,r=P.complete(b,e.id),s=P.snapshot();return b.winner===0&&r.kills===1&&r.echo&&r.xp===500&&P.getCompanion(id).xp===before+500&&s.claims[e.spawnId+':'+e.life].echo&&T.health(s,id)<10000&&!s.encounterSave;});
check('Re-completion is idempotent, including health after city arrival',()=>{reset();const {b,e}=hunt();b.run();const r=P.complete(b,e.id);P.travel('clearing-hub');const before=P.export();return JSON.stringify(P.complete(b,e.id))===JSON.stringify(r)&&P.export()===before;});
check('One starter kill raises a new individual to Lv3; three to Lv5',()=>R.level(T.xp(1))===3&&R.level(T.xp(1)*3)===5);
check('Firstlight defeat returns to forest camp healed, keeping accepted rewards',()=>{reset();const s=P.snapshot();s.coins=27;s.vitality.trainer=50;P.testing.replace(s);const {b,e}=hunt();b.run();const r=P.complete(b,e.id),after=P.snapshot();return b.winner!==0&&r.rescued&&r.campRecovery&&after.map==='clearing-0'&&T.health(after)===10000&&after.coins===27&&P.canService('sanctuary')&&!after.encounterSave;});
check('Fallen trainer blocks adventures; free sanctuary prevents softlock',()=>{const s=P.snapshot();s.vitality.trainer=0;P.testing.replace(s);const reason=T.readiness(P.snapshot(),team()[0]);return !!reason&&P.rest()&&T.health(P.snapshot())===10000&&!T.readiness(P.snapshot(),team()[0]);});
check('A fallen sole companion is benched and cannot block or scale a wild encounter',()=>{reset();const id=mon(),s=P.snapshot();s.vitality.companions[id]=0;P.testing.replace(s);const selected=team('mage',[id])[0],deployed=T.deploy(P.snapshot(),selected),u=C.UNITS.emberfox,e={kind:'wild',enemies:[{type:'emberfox',level:2,skills:[...u.default],...T.wild('emberfox')}]},b=new G.Battle([deployed,G.defaultBuild()[1]],{adventure:true,profile:P.snapshot(),encounter:e,seed:18});return !T.readiness(P.snapshot(),selected)&&selected[1]?.instanceId===id&&deployed[1]===null&&b.wildPartySize===1&&b.units.filter(x=>x.side===0).length===1;});
check('Store cannot be used remotely; physical tent sells for 3/6 coins',()=>{reset();const s=P.snapshot();s.coins=20;P.testing.replace(s);const remote=!P.buy('leafdraught');P.travel('clearing-hub',T.service(A.get('clearing-hub'),'shop'));return remote&&P.buy('leafdraught')&&P.buy('revivalsalve')&&P.snapshot().coins===11&&P.snapshot().inventory.leafdraught===1&&P.snapshot().inventory.revivalsalve===1;});
check('No insufficient-funds, unknown-item or remote-sanctuary purchases',()=>{const s=P.snapshot();s.coins=2;P.testing.replace(s);return !P.buy('leafdraught')&&!P.buy('nonsense')&&P.snapshot().coins===2&&!P.rest();});
check('Failed storage cannot debit coins or grant inventory',()=>{const s=P.snapshot();s.coins=20;P.testing.replace(s);const before=P.export(),set=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('QA quota');};let ok;try{ok=P.buy('leafdraught');}finally{Storage.prototype.setItem=set;}return !ok&&P.export()===before;});
check('Field potion heals exactly 45%, caps at full, refuses useless consumption',()=>{P.travel('clearing-0');const s=P.snapshot();s.inventory.leafdraught=3;s.vitality.trainer=2000;P.testing.replace(s);P.travel('clearing-0');const a=P.recover('leafdraught','trainer')&&T.health(P.snapshot())===6500,b=P.recover('leafdraught','trainer')&&T.health(P.snapshot())===10000;return a&&b&&!P.recover('leafdraught','trainer')&&P.snapshot().inventory.leafdraught===1;});
check('Only salve revives, only fallen targets; copies do not share healing',()=>{const a=mon(),b=mon(),s=P.snapshot();s.vitality.companions[a]=0;s.vitality.companions[b]=2300;s.inventory.revivalsalve=2;P.testing.replace(s);return !P.recover('leafdraught',a)&&P.recover('revivalsalve',a)&&T.health(P.snapshot(),a)===5000&&T.health(P.snapshot(),b)===2300&&!P.recover('revivalsalve',a)&&!P.recover('leafdraught','missing');});
check('Medicine and shopping blocked during a reserved encounter',()=>{const s=P.snapshot();s.vitality.trainer=5000;s.inventory.leafdraught=2;P.testing.replace(s);hunt();const before=P.snapshot().inventory.leafdraught;const blocked=!P.recover('leafdraught','trainer')&&!P.buy('leafdraught')&&!P.rest();P.abandonBattle();return blocked&&P.snapshot().inventory.leafdraught===before;});
check('All six cities have reachable shop doors and automatic recovery instead of sanctuary actions',()=>A.maps.filter(m=>m.kind==='hub').every(m=>{const p=T.service(m,'shop');return !T.service(m,'sanctuary')&&!A.collision(m.id,p)&&BondNav.find(m.id,m.entry,p).ok;}));
check('Normal map populations still conserve per-map counts and distant replacements',()=>{reset();const {b,e,sp}=hunt();b.run();P.complete(b,e.id);const pop=P.population(),after=pop.find(x=>x.id===sp.id);return after.life===sp.life+1&&Math.hypot(after.x-sp.x,after.y-sp.y)>=900&&pop.filter(x=>x.present&&x.type==='emberfox').length===48;});
check('Rare residents still wait60s despite test Echo odds',()=>A.maps.flatMap(m=>m.habitats).filter(h=>['Rare','Very rare'].includes(h.rarity)).every(h=>h.count===1&&h.respawnSeconds===60&&h.echoBP===1500));
reset();return out;
}
