"""Import the two inert item sheets, preserving stable species IDs and source bytes."""
import argparse,csv,hashlib,json,re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCES=['docs/Huntaria - Equipment.csv','docs/Huntaria - Held_Items.csv']
CLASSES={'Knight':'swordsman','Mage':'mage','Druid':'druid','Hunter':'hunter'}
SLOTS={'Weapon':'weapon','Off-hand':'offhand','Head':'head','Body':'body','Feet':'feet','Accessory':'accessory'}
FAMILIES={
 'Haunted object or Afterlife spirit families only.':['Haunted object','Afterlife spirit'],
 'Construct or Skeletal / undead families only.':['Construct','Skeletal / undead'],
 'Demon / fiend or Afterlife spirit families only.':['Demon / fiend','Afterlife spirit'],
 **{f'{name} family only.':[name] for name in ['Construct','Skeletal / undead','Invertebrate','Aquatic','Plant / fungus','Reptile / amphibian','Elemental / abstract']}
}
def quest_items():
    rewards=[('swordsman','Oathkeeper Blade','Sword','Earth',{'atk':12,'str':2}),
             ('hunter','Watchkeeper Bow','Bow','Wind',{'atk':12,'dex':2}),
             ('mage','Emberglass Wand','Wand','Fire',{'matk':12,'int':2}),
             ('druid',"Warden's Branch",'Staff','Earth',{'matk':12,'int':2})]
    return {f'weapon:class:{kind}':{'id':f'weapon:class:{kind}','kind':'equipment','number':101+n,
            'name':name,'effect':'None','slot':'weapon','subtype':subtype,'classes':[kind],
            'level':20,'stats':stats,'icon':f'assets/items/quest-{kind}.svg','element':element,
            'source':'relic-quest','dropChanceBP':0}
            for n,(kind,name,subtype,element,stats) in enumerate(rewards)}

def catalog():
    creatures=json.loads((ROOT/'data/creature-reference.json').read_text(encoding='utf-8'))['creatures']
    names={c['name']:c for c in creatures};items={};drops={}
    for source in SOURCES:
        rows=list(csv.DictReader((ROOT/source).open(encoding='utf-8-sig',newline='')))
        assert len(rows)==100,source
        equipment='Equipment' in rows[0];seen=set()
        for number,row in enumerate(rows,1):
            assert row['Who drops it'] in names,row
            mon=names[row['Who drops it']];species=mon['id'];assert species not in seen;seen.add(species)
            kind='equipment' if equipment else 'held';key=f'{kind}:{species}'
            item={'id':key,'kind':kind,'number':number,'name':row['Equipment' if equipment else 'Item'],'effect':row['Effect'],
                  'dropSpecies':species,'dropChanceBP':100,'icon':f'assets/items/{kind}-{species}.svg','element':mon['element']}
            if equipment:
                match=re.fullmatch(r'Slot: (.+) \((.+)\); Classes: (.+); Minimum level: (\d+)',row['Requirements']);assert match,row
                slot,subtype,classes,level=match.groups();assert slot in SLOTS
                stats={}
                for part in row['Stats'].split(';'):
                    match=re.fullmatch(r'\s*(STR|AGI|VIT|INT|DEX|ATK|MATK|DEF|MDEF|HIT|FLEE|CRIT|Max HP) ([+-]\d+)\s*',part);assert match,part
                    stat,amount=match.groups();stats[{'Max HP':'hp'}.get(stat,stat.lower())]=int(amount)
                item.update(slot=SLOTS[slot],subtype=subtype,classes=['apprentice',*CLASSES.values()] if classes=='All' else [CLASSES[c] for c in classes.split(' / ')],level=int(level),stats=stats,statsText=row['Stats'],requirements=row['Requirements'])
            else:
                restriction=row['Restrictions'];allowed=[]
                if restriction.startswith('Birds only:'):
                    allowed=[names[n.strip()]['id'] for n in restriction.split(':',1)[1].strip().removesuffix('.').split(',')]
                elif restriction!='None':
                    assert restriction in FAMILIES,restriction
                    allowed=[c['id'] for c in creatures if c.get('visualFamily',c['family']) in FAMILIES[restriction]]
                    assert allowed,restriction
                item.update(restriction=restriction,allowedSpecies=allowed,role=row['Class'],level=1,stats={})
            items[key]=item;drops.setdefault(species,[]).append(key)
    assert len(items)==200 and len(drops)==100 and all(len(ids)==2 for ids in drops.values())
    return {'version':1,'source':[{'path':p,'sha256':hashlib.sha256((ROOT/p).read_bytes()).hexdigest()} for p in SOURCES],
            'slots':SLOTS,'items':items,'questItems':quest_items(),'drops':drops}
def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    data=catalog();text='/* Generated by scripts/equipment_catalog.py; CSV prose is data, never code. */\n(function(root){\n\"use strict\";\nroot.BondItemCatalog='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n})(globalThis);\n'
    path=ROOT/'item-catalog.js'
    if args.check:assert path.read_text(encoding='utf-8')==text,'Stale item catalog; run scripts/equipment_catalog.py'
    else:path.write_text(text,encoding='utf-8',newline='\n')
    print('PASS: 100 equipment, 100 held items, six slots, explicit restrictions and 100 paired 1% drop sources')
if __name__=='__main__':main()
