"""Generate the stable-ID -> supplied PNG/name overlay; never change combat balance.
The reviewed Google Sheet snapshot, not similar-looking legacy creatures, defines identity.
Original PNGs remain untouched. No network or image-editing dependency is required.
"""
import argparse
import hashlib
import json
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build():
    source = json.loads((ROOT / "data/monster-roster.json").read_text(encoding="utf-8"))
    authority = source["source"]
    assert authority["authority"] == "Google Sheets"
    assert authority["googleSpreadsheetId"] == "16cPx2V69RCrvfmTmqYtP1zUBezq9zvl_UUiVE7Osqho"
    assert authority["sheet"] == "Roster" and authority["snapshotRows"] == 100
    assert authority["snapshotRange"] == "A1:S101" and authority["reviewedRevision"].isdigit()
    assert re.fullmatch(r"[a-f0-9]{8}", authority["snapshotFNV1a32"])
    rows = source["rows"]
    assert len(rows) == 100 and {r[0] for r in rows} == set(range(1, 101))
    assert len({r[17] for r in rows}) == 100
    attack_by_id = {species: label for label, species_ids in source["attackBaseGroups"].items()
                    for species in species_ids}
    assert set(attack_by_id) == {r[17] for r in rows}
    categories = {"Strength-based": "melee", "Dex-Based": "ranged", "Int-Based": "magic"}
    regions = {"Mosslight": 0, "Willowbrook": 1, "Amber Hollow": 2,
               "Moonwell": 3, "Windstep": 4, "Ashen Reach": 5}
    files = {}
    for path in (ROOT / "assets/monsters").glob("*.png"):
        match = re.fullmatch(r"(\d+)(?:-[^/]+)?\.png", path.name)
        assert match, path.name
        number = int(match[1])
        assert number not in files, f"Duplicate sprite number {number}"
        with path.open("rb") as stream:
            header = stream.read(26)
        assert header[:8] == b"\x89PNG\r\n\x1a\n", path.name
        width, height = struct.unpack(">II", header[16:24])
        assert width == height and 256 <= width <= 4096, path.name
        files[number] = path.relative_to(ROOT).as_posix()
    assert set(files) == set(range(1, 101)), "Expected exactly 100 numbered PNGs"
    entries = []
    for row in rows:
        number, name, description = row[:3]
        assert re.fullmatch("[a-z]+", row[17])
        assert not any(x in name + description + row[6] for x in '<>&"')
        entries.append(dict(number=number, id=row[17], name=name,
                            originalName=row[16], description=description,
                            designRole=row[3], combatIdentity=row[8], element=row[9],
                            region=regions[row[10]], sourceWildLevel=row[11],
                            encounterSource=row[12], rarity=row[13],
                            attackBase=attack_by_id[row[17]], basicCategory=categories[attack_by_id[row[17]]],
                            family=row[6], body=row[7], src=files[number],
                            nativeFacing=1))
    encoded = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    return """/* Generated by scripts/monster_sprites.py. Do not hand-edit.
   Reviewed Sheet identity only: stable IDs, stats, skills and saved individuals stay intact. */
(function(root){
  'use strict';
  const entries=__ENTRIES__;
  const byId=new Map(entries.map(entry=>[entry.id,Object.freeze(entry)]));
  for(const entry of entries){
    const unit=BondContent.UNITS[entry.id];
    if(!unit||!BondContent.MONSTERS.includes(entry.id))throw Error('Unmapped supplied monster: '+entry.id);
    unit.name=entry.name;
    unit.subtitle=entry.description;
    unit.visualFamily=entry.family;
    unit.designRole=entry.designRole;
    unit.combatIdentity=entry.combatIdentity;
    unit.element=entry.element;
    unit.region=entry.region;
    unit.source=entry.encounterSource.startsWith('Boss')?'boss':'wild';
    unit.sourceWildLevel=entry.sourceWildLevel;
    unit.encounterSource=entry.encounterSource;
    unit.rarity=entry.rarity;
    unit.attackBase=entry.attackBase;
    unit.basicCategory=entry.basicCategory;
  }
  root.BondMonsterSprites=Object.freeze({
    get:type=>byId.get(type),
    manifest:()=>entries.map(entry=>({...entry}))
  });
})(globalThis);
""".replace("__ENTRIES__", encoded)


def publish_reference():
    """Publish explicitly authorized names/art metadata against a fresh runtime export."""
    live = json.loads((ROOT / 'tests/artifacts/pass18-reference-chrome.json').read_text(encoding='utf-8'))
    for name, digest in live['source_sha256'].items():
        assert hashlib.sha256((ROOT / name).read_bytes()).hexdigest() == digest, 'Stale runtime export: ' + name
    source = json.loads((ROOT / 'data/monster-roster.json').read_text(encoding='utf-8'))
    lookup = {r[17]: r for r in source['rows']}
    actual = {r['id']: r for r in live['species']}
    target = ROOT / 'data/creature-reference.json'
    data = json.loads(target.read_text(encoding='utf-8'))
    assert set(lookup) == set(actual) == {r['id'] for r in data['creatures']}
    for r in data['creatures']:
        row, u = lookup[r['id']], actual[r['id']]
        assert row[1] == u['name'] and row[6] == u['visualFamily']
        assert (r['base']['hp'], r['base']['attack'], r['role'], r['element']) == (u['hp'], u['power'], u['role'], u['element'])
        if r['name'] != row[1]:
            r['previousNames'] = list(dict.fromkeys(r.get('previousNames', []) + [r['name']]))
        r['name'] = row[1]
        r['visualFamily'] = row[6]
        r['visualBody'] = row[7]
        r.setdefault('legacyDesign', r['design'].copy())
        r['design'].update(status='SUPPLIED_SINGLE_POSE_REVIEW_PENDING', silhouette=row[2],
                           animation='Single supplied pose with transform-based motion; authored frame animation pending.',
                           assetStatus='Supplied PNG integrated; commercial art/motion review pending')
    if 'monster-sprites.js' not in data['sourceFiles']:
        data['sourceFiles'].append('monster-sprites.js')
    data['revision'] = 7
    for key in ('soloIntroduction', 'firstMap'):
        if key in data.get('temporaryTestTuning', {}):
            for old, new in [('Emberfox', 'Brimble'), ('Stonehorn', 'Rattlebit')]:
                data['temporaryTestTuning'][key] = data['temporaryTestTuning'][key].replace(old, new)
    target.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    print('Published supplied names/art metadata; kept balance, kits, source levels and loot unchanged.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--publish-reference", action="store_true")
    args = parser.parse_args()
    output = build()
    target = ROOT / "monster-sprites.js"
    if args.write:
        target.write_text(output, encoding="utf-8", newline="\n")
    if args.check:
        assert target.read_text(encoding="utf-8") == output, "Stale monster-sprites.js"
    if args.publish_reference:
        publish_reference()
    print("PASS: 100 unique stable IDs and numbered square PNGs; names match the supplied roster.")


if __name__ == "__main__":
    main()
