"""Focused, generated feature guides and exact task routing; no runtime writes."""
from __future__ import annotations

from pathlib import Path
import re

MAP = "FEATURE_MAP.md"
CONNECTIONS = "docs/architecture/CONNECTIONS.md"
MODULES = "docs/architecture/MODULE_GRAPH.md"
CONTAINERS = ("docs/README.md", "scripts/README.md", "tests/README.md",
              "assets/README.md", "data/README.md", "features/delivery/OPERATIONS.md",
              "features/persistence/SAVES.md")
README_HEADINGS = ("Start", "Find the feature", "Run and check", "Other routes")


def guide(feature):
    return f"features/{feature}/README.md"


def link(label, path, prefix=""):
    return f"[{label}](<{prefix}{path}>)"


def code(value):
    return chr(96) + value + chr(96)


def finish(lines):
    return "\n".join(lines) + "\n"


def related(model, feature):
    return [c for c in model["connections"] if feature in (c["from"], c["to"])]


def gate_routes(root, features):
    import review_gates
    return [g for g in review_gates.load(root)["gates"] if set(features) & set(g["features"])]


def render_map(root, model, observed):
    out = ["# Feature map — choose a route", "",
           "Generated by `python scripts/project.py map --write`. Source: "
           "[architecture manifest](docs/architecture.json). Do not hand-edit.",
           "Read one feature guide, not every file. Local status is not commercial acceptance.", "",
           "## Features", "",
           "| Feature | Responsibility and connection | Status |",
           "| --- | --- | --- |"]
    for f in model["features"]:
        # Preserve old FEATURE_MAP#feature links without retaining the long sections.
        out.append(f'| <a id="{f["id"]}"></a>{link(f["id"], guide(f["id"]))} | '
                   f'{f.get("summary", f["title"])} | {f["status"]} |')
    out += ["", "## Symptoms", "",
            "| Symptom | Start here | If the fault crosses the boundary |",
            "| --- | --- | --- |"]
    for symptom, owner, connection, _ in model["symptoms"]:
        out.append(f"| {symptom} | {link(owner, guide(owner))} | "
                   f"{link(connection, CONNECTIONS + '#' + connection)} |")
    out += ["", "## Connections and commands", "",
            "- " + link("Boundary contracts and shared interface shapes", CONNECTIONS),
            "- " + link("Observed boot graph and CSS order", MODULES),
            "- " + link("Run, test, backup and content publication", "features/delivery/OPERATIONS.md"),
            "- " + link("Owner decisions before dependent production", "OWNER_REVIEWS.md"),
            "", "`python scripts/project.py context combat` returns the focused route.",
            "Also accepts a source path, exported global, F-### card or connection ID.",
            "`python scripts/project.py impact game.js` expands the affected consumers/tests.",
            "Current acceptance cards remain in [FEATURE_BACKLOG](FEATURE_BACKLOG.md);",
            "each feature guide lists its cards. This index does not accept any criterion.", "",
            "Regenerate with `python scripts/project.py map --write` after ownership,",
            "interface or test-routing changes; `python scripts/project.py check` detects drift."]
    return finish(out)


def render_feature(root, model, observed, feature):
    f = feature
    fid = f["id"]
    pre = "../../"
    ref = lambda label, path: link(label, path, pre)
    owned = set(f["files"])
    deps = sorted({observed["owners"].get(dep, dep) for source in owned
                   for dep in observed["dependencies"].get(source, []) if dep not in owned})
    consumers = sorted({observed["owners"].get(source, source)
                        for source, ds in observed["dependencies"].items()
                        if set(ds) & owned and source not in owned})
    out = [f"# {f['title']}", "",
           "Generated from " + ref("architecture.json", "docs/architecture.json") +
           "; edit that source, then `python scripts/project.py map --write`.",
           ref("All features", MAP) + " · " + ref("Workflow", "AGENTS.md"), "",
           f"Status: **{f['status']}**. {f.get('summary', '')}", "",
           "## Entry and responsibility", "", code(f["entry"]), "", f["contract"], "",
           "These are ownership containers, not duplicate runtime implementations.",
           "The links below point to the actual source; root browser paths remain in use.", "",
           "## Implementation", "", "| File | Observed exports / role |",
           "| --- | --- |"]
    for name in f["files"]:
        exports = observed["exports"].get(name, [])
        out.append(f"| {ref(name, name)} | {', '.join(code(s) for s in exports) or 'Owned source/configuration; inspect before editing.'} |")
    if not owned:
        out.append("| No runtime implementation | Planned boundary; do not claim it exists. |")
    out += ["", "## Connections", "",
            "Observed references include optional and late callbacks, not only boot dependencies.", "",
            "- Uses: " + (", ".join(ref(n, guide(n)) for n in deps) or "None observed."),
            "- Used by: " + (", ".join(ref(n, guide(n)) for n in consumers) or "None observed."), ""]
    connections = related(model, fid)
    for c in connections:
        out += ["- " + ref(c["id"], CONNECTIONS + "#" + c["id"]) +
                f" ({c['from']} → {c['to']}): {c['contract']}"]
    if not connections:
        out.append("No explicit cross-feature connection recorded; check the observed dependencies above.")
    interfaces = [(i, value) for i, value in enumerate(model.get("interfaces", []), 1)
                  if fid in value.get("features", [])]
    if interfaces:
        out += ["", "Shared shapes: " + ", ".join(
            ref(v["name"], CONNECTIONS + f"#interface-{i}") for i, v in interfaces) + "."]
    symptoms = [s for s in model["symptoms"] if s[1] == fid or s[2] in {c["id"] for c in connections}]
    if symptoms:
        out += ["", "## Diagnose here", ""]
        for symptom, owner, connection, diagnostic in symptoms:
            out.append(f"- {symptom}: {diagnostic} First owner: {ref(owner, guide(owner))}.")
    out += ["", "## Validate", "",
            "Commands run from the project root. Use disposable saves. These suites",
            "cover this feature and shared boundaries; they are not isolated unit tests.", ""]
    for suite in f["tests"]:
        d = model["suites"][suite]
        command = "python " + " ".join(d["command"]) + (" --browser chrome" if d.get("browser") else "")
        out.append(f"- {code(command)} — {d['purpose']}.")
    if not f["tests"]:
        out.append("No implemented test suite yet. Define service/acceptance tests with implementation.")
    out += ["", "For a cross-feature change, run " + code("python scripts/project.py verify --browser chrome") +
            "; see " + ref("validation setup and limits", "features/delivery/OPERATIONS.md") + ".", "",
            "## Specifications and decisions", ""]
    for name in f["docs"]:
        out.append("- " + ref(name, name))
    for name in model["assets"].get(fid, []):
        out.append("- Art and provenance: " + ref(name, name))
    out.append("- Commercial cards: " + (", ".join(ref(c, "FEATURE_BACKLOG.md") for c in f["backlog"]) or
               "Cross-cutting implementation; no separate acceptance card."))
    gates = gate_routes(root, [fid])
    out.append("- Owner review routes: " + (", ".join(ref(g["id"], "OWNER_REVIEWS.md#" + g["id"].lower())
                for g in gates) or "Shared release policy applies.") +
               " Use the live board/preflight for status, not an approval copied here.")
    return finish(out)


def render_connections(model):
    pre = "../../"
    ref = lambda label, path: link(label, path, pre)
    out = ["# Cross-feature contracts", "", "Generated from " +
           ref("architecture.json", "docs/architecture.json") + ". " + ref("Feature index", MAP) + ".",
           "Read the relevant connection only. Contracts are reviewed intent; source is the implementation."]
    for c in model["connections"]:
        out += ["", f'<a id="{c["id"]}"></a>', f"## {c['id']}", "",
                ref(c["from"], guide(c["from"])) + " → " + ref(c["to"], guide(c["to"])),
                "", c["contract"], "",
                "Trace through: " + " → ".join(ref(n, n) for n in c["via"]) + "."]
    out += ["", "## Shared interface shapes", ""]
    for i, c in enumerate(model.get("interfaces", []), 1):
        out += [f'<a id="interface-{i}"></a>', f"### {c['name']}", "",
                c["shape"], "", c["rule"], "",
                "Relevant features: " + ", ".join(ref(f, guide(f)) for f in c.get("features", [])) + ".", ""]
    return finish(out)


def render_modules(model, observed):
    ref = lambda label, path: link(label, path, "../../")
    out = ["# Observed browser module graph", "",
           "Generated from " + ref("architecture.json", "docs/architecture.json") +
           " and current source. " + ref("Feature index", MAP) + ".", "",
           "Lexical references include optional/late callbacks; they are not proof of all dependencies.",
           "Only boot prerequisites require earlier providers. Later CSS overrides earlier CSS.", "",
           "| Boot | Module | Owner | Exports | References | Boot prerequisites | Signals |",
           "| --- | --- | --- | --- | --- | --- | --- |"]
    for i, (name, _) in enumerate(observed["entry"].scripts, 1):
        owner = observed["owners"].get(name, "UNOWNED")
        out.append(f"| {i} | {ref(name, name)} | {ref(owner, guide(owner))} | "
                   f"{', '.join(observed['exports'].get(name, []))} | "
                   f"{', '.join(observed['dependencies'].get(name, [])) or '—'} | "
                   f"{', '.join(model['boot_requires'].get(name, [])) or '—'} | "
                   f"{', '.join(observed['events'].get(name, [])) or '—'} |")
    out += ["", "Unloaded legacy JS: " + ", ".join(ref(n, n) for n in model["unloaded"]) + ".",
            "", "CSS override order: " + " → ".join(ref(n, n) for n in observed["entry"].styles) + "."]
    return finish(out)


def documents(root, model, observed):
    result = {MAP: render_map(root, model, observed),
              CONNECTIONS: render_connections(model), MODULES: render_modules(model, observed)}
    result.update({guide(f["id"]): render_feature(root, model, observed, f) for f in model["features"]})
    return result


def context(query, root, model, observed):
    value = query.replace("\\", "/").removeprefix("./")
    path = Path(value)
    if path.is_absolute():
        try:
            value = path.resolve().relative_to(root.resolve()).as_posix()
        except ValueError:
            raise ValueError("Context path is outside this project") from None
    ids = {f["id"] for f in model["features"]}
    selected = set()
    match = None
    if value in ids:
        selected, match = {value}, "feature"
    elif value in observed["owners"]:
        selected, match = {observed["owners"][value]}, "owned file"
    elif value in observed["providers"]:
        selected, match = {observed["owners"][observed["providers"][value]]}, "exported global"
    else:
        for f in model["features"]:
            if value in f["backlog"]:
                selected.add(f["id"])
                match = "acceptance card"
            elif value == guide(f["id"]) or value in f["docs"]:
                selected.add(f["id"])
                match = "feature document"
        for c in model["connections"]:
            if value == c["id"]:
                selected.update((c["from"], c["to"]))
                match = "connection"
    if not selected:
        raise ValueError("No exact route for " + query +
                         ". Use a feature ID, owned path, exported global, F-### card or connection ID; "
                         "see project.py context --list or FEATURE_MAP.md for symptoms.")
    features = [f for f in model["features"] if f["id"] in selected]
    connections = [c for c in model["connections"] if selected & {c["from"], c["to"]}]
    suites = sorted({s for f in features for s in f["tests"]})
    return {
        "query": query, "match": match,
        "start_here": [{"feature": f["id"], "purpose": f["summary"],
                        "guide": guide(f["id"]), "entry": f["entry"], "files": f["files"]}
                       for f in features],
        "inspect_if_crossing_boundary": [{"id": c["id"], "features": [c["from"], c["to"]],
                                        "contract": CONNECTIONS + "#" + c["id"], "via": c["via"]}
                                       for c in connections],
        "tests": {s: "python " + " ".join(model["suites"][s]["command"]) +
                  (" --browser chrome" if model["suites"][s].get("browser") else "") for s in suites},
        "owner_gates": [g["id"] for g in gate_routes(root, selected)],
        "note": "Read the selected guide and actual source first; use impact for transitive change validation."
    }


def validate_model(model):
    errors = []
    ids = {f["id"] for f in model["features"]}
    for f in model["features"]:
        if not re.fullmatch(r"[a-z][a-z0-9-]*", f["id"]):
            errors.append("Unsafe feature routing ID: " + f["id"])
        summary = f.get("summary", "")
        if not summary.strip() or len(summary) > 180 or "\n" in summary:
            errors.append(f"{f['id']}: routing summary must be one nonempty line <=180 characters")
    for interface in model.get("interfaces", []):
        if not interface.get("features") or not set(interface["features"]) <= ids:
            errors.append("Interface has missing/unknown feature routes: " + interface["name"])
    return errors


def validate(root, model, observed, freshness=True):
    errors = validate_model(model)
    if errors:
        return errors
    expected = documents(root, model, observed)
    maintained = {"README.md", "AGENTS.md", "docs/ENGINEERING.md", "OWNER_REVIEWS.md", *CONTAINERS}
    local_details = {name for f in model["features"] for name in f["docs"]
                     if name.startswith("features/") and name.endswith(".md")}
    maintained.update(local_details)
    for name in sorted(set(expected) | maintained):
        path = root / name
        if not path.is_file():
            errors.append("Missing routing document " + name)
            continue
        source = path.read_text(encoding="utf-8-sig")
        if freshness and name in expected and source != expected[name]:
            errors.append(name + " is stale; run project.py map --write")
        for raw in re.findall(r"\[[^\]]*\]\((<[^>]+>|[^)\s]+)\)", source):
            target = raw.strip("<>").split("#", 1)[0].split("?", 1)[0]
            if not target or re.match(r"^[a-z]+:", target):
                continue
            resolved = path.parent.joinpath(target).resolve()
            if not resolved.is_relative_to(root.resolve()) or not resolved.exists():
                errors.append(f"{name}: broken link {target}")
        if name == "README.md":
            if len(source.split()) > 600:
                errors.append("README routing budget exceeded (600 words); move detail to its feature")
            for heading in README_HEADINGS:
                if f"## {heading}\n" not in source:
                    errors.append("README missing routing heading " + heading)
        if name == MAP and len(source.split()) > 1300:
            errors.append("FEATURE_MAP routing budget exceeded (1300 words); move detail to feature guides")
    expected_guides = {guide(f["id"]) for f in model["features"]}
    for path in (root / "features").glob("*/README.md"):
        if path.relative_to(root).as_posix() not in expected_guides:
            errors.append("Unrouted feature container " + path.parent.name)
    for path in (root / "features").rglob("*.md"):
        name = path.relative_to(root).as_posix()
        if name not in expected_guides | local_details:
            errors.append("Unrouted feature detail " + name + "; register it in the owning feature docs")
    return errors
